Repository awslabs/graphstorm, pull requests merged in 2023-12, with the labels that each got.

#672 [Bug fix] Fix the read/delete contention bug when running distributed remaping result/emb
  python/graphstorm/gconstruct/remap_result.py
  tests/end2end-tests/data_process/test.sh
  tests/unit-tests/gconstruct/test_remap_result.py
Labels: ready

#680 [Bugfix] Fix a typo in one of the unit test
  tests/unit-tests/test_model_save_load.py
Labels: bug, ready

#681 Update builtin train/inference entries to accept unknown arguments
  examples/customized_models/HGT/hgt_nc.py
  examples/temporal_graph_learning/main_nc.py
  python/graphstorm/run/gsgnn_dt/distill_gnn.py
  python/graphstorm/run/gsgnn_emb/gsgnn_node_emb.py
  python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
  python/graphstorm/run/gsgnn_ep/ep_infer_lm.py
  python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
  python/graphstorm/run/gsgnn_ep/gsgnn_lm_ep.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
  python/graphstorm/run/gsgnn_np/gsgnn_np.py
  python/graphstorm/run/gsgnn_np/np_infer_gnn.py
  sagemaker/launch/launch_infer.py
Labels: ready, 0.2.2

#682 [Bug fix] Fix a bug when --column-names does not cover all builtin names
  python/graphstorm/gconstruct/remap_result.py
  tests/unit-tests/gconstruct/test_remap_result.py
Labels: bug, ready, 0.2.2

#683 [Homo Optmization] Add homogeneous graph optimization
  .github/workflow_scripts/e2e_check.sh
  python/graphstorm/gconstruct/construct_graph.py
  tests/end2end-tests/data_gen/movielens_homogeneous.json
  tests/end2end-tests/data_gen/process_movielens.py
  tests/end2end-tests/data_process/check_homogeneous.py
  tests/end2end-tests/data_process/homogeneous_test.sh
  tests/unit-tests/gconstruct/test_construct_graph.py
Labels: 0.3, ready

#689 Add flush operation
  .github/workflow_scripts/lint_check.sh
  python/graphstorm/distributed/__init__.py
  python/graphstorm/distributed/primitives.py
  python/graphstorm/model/gnn_encoder_base.py
  python/graphstorm/model/utils.py
  tests/end2end-tests/graphstorm-nc/mgpu_test.sh
Labels: ready

#686 [Homo Optimization] Optimization on GSF
  docs/source/configuration/configuration-run.rst
  python/graphstorm/config/argument.py
  python/graphstorm/dataloading/dataset.py
  tests/end2end-tests/data_process/homogeneous_test.sh
  tests/unit-tests/data_utils.py
  tests/unit-tests/test_config.py
  tests/unit-tests/test_dataloading.py
  training_scripts/gsgnn_ep/ml_ec_homogeneous.yaml
  training_scripts/gsgnn_np/ml_nc_homogeneous.yaml
Labels: ready

#684 Gconstruct hard negative
  docs/source/advanced/advanced-usages.rst
  python/graphstorm/gconstruct/construct_graph.py
  python/graphstorm/gconstruct/file_io.py
  python/graphstorm/gconstruct/id_map.py
  python/graphstorm/gconstruct/transform.py
  python/graphstorm/gconstruct/utils.py
  tests/end2end-tests/data_process/data_gen.py
  tests/end2end-tests/data_process/test_data.py
  tests/unit-tests/gconstruct/test_construct_graph.py
  tests/unit-tests/gconstruct/test_gconstruct_utils.py
  tests/unit-tests/gconstruct/test_transform.py
Labels: ready, 0.2.2

#694 Fix a bug in gconstruct when saving intermediate data on disks
  python/graphstorm/gconstruct/utils.py
  tests/unit-tests/gconstruct/test_gconstruct_utils.py
Labels: ready

#673 PEFT LLM training example
  examples/peft_llm_gnn/README.md
  examples/peft_llm_gnn/llm_gnn_model.py
  examples/peft_llm_gnn/main_nc.py
  examples/peft_llm_gnn/nc_config_Video_Games.yaml
  examples/peft_llm_gnn/preprocess_amazon_review.py
  python/graphstorm/eval/utils.py
Labels: ready

#695 Fix a bug in loading cached LM embeddings.
  python/graphstorm/model/lm_embed.py
  tests/unit-tests/test_embed.py
Labels: ready

#696 Fix a bug in inference code
  python/graphstorm/model/embed.py
  python/graphstorm/model/gnn_encoder_base.py
  python/graphstorm/model/lm_embed.py
Labels: ready
