Repository awslabs/graphstorm, pull requests merged in 2023-09, with the labels that each got.

#390 Using logging to print messages
  python/graphstorm/config/argument.py
  python/graphstorm/dataloading/dataset.py
  python/graphstorm/dataloading/utils.py
  python/graphstorm/eval/eval_func.py
  python/graphstorm/eval/evaluator.py
  python/graphstorm/gconstruct/construct_graph.py
  python/graphstorm/gsf.py
  python/graphstorm/model/embed.py
  python/graphstorm/model/gnn.py
  python/graphstorm/model/gnn_encoder_base.py
  python/graphstorm/model/lm_embed.py
  python/graphstorm/model/rgat_encoder.py
  python/graphstorm/model/rgcn_encoder.py
  python/graphstorm/model/utils.py
  python/graphstorm/run/gs_link_prediction.py
  python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
  python/graphstorm/run/gsgnn_ep/ep_infer_lm.py
  python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
  python/graphstorm/run/gsgnn_ep/gsgnn_lm_ep.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
  python/graphstorm/run/gsgnn_np/gsgnn_np.py
  python/graphstorm/run/gsgnn_np/np_infer_gnn.py
  python/graphstorm/run/launch.py
  python/graphstorm/tracker/sagemaker_tracker.py
  python/graphstorm/trainer/ep_trainer.py
  python/graphstorm/trainer/glem_np_trainer.py
  python/graphstorm/trainer/gsgnn_trainer.py
  python/graphstorm/trainer/lp_trainer.py
  python/graphstorm/trainer/np_trainer.py
  python/graphstorm/utils.py
  tests/end2end-tests/graphstorm-ec/mgpu_test.sh
  tests/end2end-tests/graphstorm-ec/test.sh
  tests/end2end-tests/graphstorm-er/test.sh
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
  tests/end2end-tests/graphstorm-lp/test.sh
  tests/end2end-tests/graphstorm-nc/mgpu_test.sh
  tests/end2end-tests/graphstorm-nc/test.sh
Labels: v0.2

#400 [DistProcessing] Initial commit for GSProcessing. Add project structure and config module.
  .github/workflow_scripts/lint_check.sh
  graphstorm-processing/.gitignore
  graphstorm-processing/README.md
  graphstorm-processing/graphstorm_processing/config/__init__.py
  graphstorm-processing/graphstorm_processing/config/config_conversion/__init__.py
  graphstorm-processing/graphstorm_processing/config/config_conversion/converter_base.py
  graphstorm-processing/graphstorm_processing/config/config_conversion/gconstruct_converter.py
  graphstorm-processing/graphstorm_processing/config/config_conversion/meta_configuration.py
  graphstorm-processing/graphstorm_processing/config/config_parser.py
  graphstorm-processing/graphstorm_processing/config/data_config_base.py
  graphstorm-processing/graphstorm_processing/config/feature_config_base.py
  graphstorm-processing/graphstorm_processing/config/label_config_base.py
  graphstorm-processing/mypy.ini
  graphstorm-processing/poetry.toml
  graphstorm-processing/pyproject.toml
  graphstorm-processing/pytest.ini
  graphstorm-processing/tests/test_converter.py
Labels: v0.2

#408 [GSProcessing] GSProcessing PR2: Entrypoint and SageMaker script for processing.
  graphstorm-processing/graphstorm_processing/constants.py
  graphstorm-processing/graphstorm_processing/distributed_executor.py
  graphstorm-processing/scripts/convert_gconstruct_config.py
  graphstorm-processing/scripts/run_distributed_processing.py
  graphstorm-processing/scripts/script_utils.py
  tests/lint/pylintrc
Labels: v0.2

#404 Add Gradient Clip
  docs/source/configuration/configuration-run.rst
  python/graphstorm/config/argument.py
  python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
  python/graphstorm/run/gsgnn_ep/gsgnn_lm_ep.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/run/gsgnn_np/gsgnn_np.py
  python/graphstorm/trainer/ep_trainer.py
  python/graphstorm/trainer/glem_np_trainer.py
  python/graphstorm/trainer/lp_trainer.py
  python/graphstorm/trainer/np_trainer.py
  tests/end2end-tests/graphstorm-lp/test.sh
  tests/end2end-tests/graphstorm-nc/test.sh
Labels: v0.2

#393 Add support for per edge type lp metric report
  python/graphstorm/config/argument.py
  python/graphstorm/config/config.py
  python/graphstorm/eval/__init__.py
  python/graphstorm/eval/evaluator.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/tracker/sagemaker_tracker.py
  tests/end2end-tests/create_data.sh
  tests/end2end-tests/data_gen/movielens_2etype_lp.json
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
  tests/unit-tests/test_config.py
  tests/unit-tests/test_evaluator.py
Labels: v0.2

#406 [SageMaker] Remove downloading of config file during partition launch.
  sagemaker/launch/launch_partition.py
Labels: v0.2

#237 Use the neighbors to compute the features of featureless nodes.
  python/graphstorm/config/argument.py
  python/graphstorm/dataloading/dataloading.py
  python/graphstorm/dataloading/dataset.py
  python/graphstorm/gsf.py
  python/graphstorm/model/edge_gnn.py
  python/graphstorm/model/embed.py
  python/graphstorm/model/gnn.py
  python/graphstorm/model/gnn_encoder_base.py
  python/graphstorm/model/gnn_with_reconstruct.py
  python/graphstorm/model/lp_gnn.py
  python/graphstorm/model/node_gnn.py
  python/graphstorm/model/rgcn_encoder.py
  python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
  python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/run/gsgnn_np/gsgnn_np.py
  python/graphstorm/run/gsgnn_np/np_infer_gnn.py
  tests/end2end-tests/graphstorm-ec/test.sh
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
  tests/end2end-tests/graphstorm-lp/test.sh
  tests/end2end-tests/graphstorm-nc/mgpu_test.sh
  tests/end2end-tests/graphstorm-nc/test.sh
  tests/unit-tests/data_utils.py
  tests/unit-tests/test_dataloading.py
  tests/unit-tests/test_embed.py
  tests/unit-tests/test_gnn.py
Labels: v0.2

#422 Fix metric printing for complex metric value
  python/graphstorm/tracker/sagemaker_tracker.py
Labels: bug, v0.2

#424 [Bugfix] Avoid trim data for validation and test datasets
  python/graphstorm/dataloading/dataloading.py
  python/graphstorm/dataloading/utils.py
  tests/unit-tests/test_dataloading.py
Labels: v0.2

#419 GSProcessing PR-3: Distributed Heterogeneous Graph Loader
  graphstorm-processing/graphstorm_processing/distributed_executor.py
  graphstorm-processing/graphstorm_processing/graph_loaders/__init__.py
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
  graphstorm-processing/graphstorm_processing/graph_loaders/heterogeneous_graphloader.py
  graphstorm-processing/graphstorm_processing/graph_loaders/loader_base.py
  graphstorm-processing/tests/test_dist_heterogenous_loader.py
Labels: v0.2

#401 Update GSgnnNodeModelInterface interface
  python/graphstorm/model/node_gnn.py
  tests/unit-tests/test_gnn.py
Labels: v0.2

#396 [Feature] Add HGT Encoder
  python/graphstorm/config/__init__.py
  python/graphstorm/config/argument.py
  python/graphstorm/config/config.py
  python/graphstorm/gsf.py
  python/graphstorm/model/hgt_encoder.py
  tests/end2end-tests/graphstorm-lp/test-cpu.sh
  tests/end2end-tests/graphstorm-nc/test-cpu.sh
  tests/end2end-tests/graphstorm-nc/test.sh
  tests/unit-tests/test_gnn.py
Labels: v0.2

#430 Fix categorical transform
  python/graphstorm/gconstruct/transform.py
  tests/unit-tests/gconstruct/test_transform.py
Labels: bug, v0.2

#425 Test PR
  .github/workflows/continuous-integration.yml
Labels: ready

#429 [feature] Setup API auto doc
  .readthedocs.yaml
  docs/requirements.txt
  docs/source/_templates/classtemplate.rst
  docs/source/api/graphstorm.customized.rst
  docs/source/api/graphstorm.dataloading.rst
  docs/source/api/graphstorm.evaluator.rst
  docs/source/api/graphstorm.inferer.rst
  docs/source/api/graphstorm.model.rst
  docs/source/api/graphstorm.rst
  docs/source/api/graphstorm.trainer.rst
  docs/source/conf.py
  docs/source/configuration/configuration-run.rst
  docs/source/index.rst
  python/graphstorm/__init__.py
  python/graphstorm/dataloading/dataloading.py
  python/graphstorm/eval/__init__.py
  python/graphstorm/eval/evaluator.py
  python/graphstorm/model/__init__.py
  python/graphstorm/model/sage_encoder.py
Labels: ready

#427 [GSProcessing] Add data transformations base and test resources.
  graphstorm-processing/graphstorm_processing/config/label_config_base.py
  graphstorm-processing/graphstorm_processing/constants.py
  graphstorm-processing/graphstorm_processing/data_transformations/__init__.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_feature_transformer.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_label_loader.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/__init__.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/base_dist_transformation.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_category_transformation.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_label_transformation.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_noop_transformation.py
  graphstorm-processing/graphstorm_processing/data_transformations/s3_utils.py
  graphstorm-processing/graphstorm_processing/data_transformations/spark_utils.py
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
  graphstorm-processing/tests/conftest.py
  graphstorm-processing/tests/resources/multi_num_numerical/multi_num.csv
  graphstorm-processing/tests/resources/small_heterogeneous_graph/edges/director-directed-movie.csv
  graphstorm-processing/tests/resources/small_heterogeneous_graph/edges/movie-included_in-genre.csv
  graphstorm-processing/tests/resources/small_heterogeneous_graph/edges/user-rated-movie.csv
  graphstorm-processing/tests/resources/small_heterogeneous_graph/gconstruct-config.json
  graphstorm-processing/tests/resources/small_heterogeneous_graph/gconstruct-no-labels-config.json
  graphstorm-processing/tests/resources/small_heterogeneous_graph/nodes/genre.csv
  graphstorm-processing/tests/resources/small_heterogeneous_graph/nodes/movie.csv
  graphstorm-processing/tests/resources/small_heterogeneous_graph/nodes/user.csv
  graphstorm-processing/tests/test_dist_category_transformation.py
  graphstorm-processing/tests/test_dist_heterogenous_loader.py
  graphstorm-processing/tests/test_dist_label_loader.py
  graphstorm-processing/tests/test_dist_noop_transformation.py
Labels: v0.2, ready

#403 Update GSgnnEdgeModelInterface interface
  python/graphstorm/inference/ep_infer.py
  python/graphstorm/model/edge_decoder.py
  python/graphstorm/model/edge_gnn.py
  python/graphstorm/model/node_gnn.py
  python/graphstorm/model/utils.py
  python/graphstorm/trainer/ep_trainer.py
  tests/unit-tests/test_gnn.py
Labels: v0.2, ready

#436 add labeled
  .github/workflows/continuous-integration.yml
Labels: ready

#423 Add version entry to gconsturct expected schema.
  docs/source/configuration/configuration-gconstruction.rst
  docs/source/tutorials/own-data.rst
  python/graphstorm/gconstruct/README.md
  python/graphstorm/gconstruct/construct_graph.py
  tests/end2end-tests/data_gen/movielens.json
  tests/end2end-tests/data_gen/movielens_2etype_lp.json
  tests/end2end-tests/data_gen/movielens_custom.json
  tests/end2end-tests/data_gen/movielens_er.json
  tests/end2end-tests/data_gen/movielens_lm_encoder.json
  tests/end2end-tests/data_gen/movielens_lm_encoder_lp.json
  tests/end2end-tests/data_gen/movielens_lp.json
  tests/end2end-tests/data_gen/movielens_roberta_encoder.json
  tests/end2end-tests/data_gen/movielens_text.json
  tests/end2end-tests/test_data_config/movielens_user_feat_movie_token.json
Labels: v0.2, ready

#428 [Wholegraph] Add wholgraph format conversion script
  tools/README.md
  tools/convert_feat_to_wholegraph.py
Labels: v0.2, ready

#439 Updated arguments names
  tools/README.md
  tools/gen_ogb_dataset.py
Labels: ready

#410 Multiple target node training with per node type decoder
  docs/source/advanced/advanced-usages.rst
  python/graphstorm/config/argument.py
  python/graphstorm/gsf.py
  python/graphstorm/model/gnn.py
  python/graphstorm/model/node_gnn.py
  python/graphstorm/run/gsgnn_np/gsgnn_np.py
  tests/end2end-tests/create_data.sh
  tests/end2end-tests/data_gen/movielens_multi_target_ntypes.json
  tests/end2end-tests/data_gen/process_movielens.py
  tests/end2end-tests/graphstorm-nc/test.sh
  training_scripts/gsgnn_np/ml_nc_multi_target_ntypes.yaml
  training_scripts/gsgnn_np/ml_nc_multi_target_ntypes_multilabel.yaml
Labels: ready

#435 [GSProcessing] Add Docker-related files and code utilities.
  graphstorm-processing/docker-entry.sh
  graphstorm-processing/docker/0.1.0/Dockerfile.cpu
  graphstorm-processing/docker/README.md
  graphstorm-processing/docker/build_gsprocessing_image.sh
  graphstorm-processing/docker/push_gsprocessing_image.sh
  graphstorm-processing/graphstorm_processing/data_transformations/s3_utils.py
  graphstorm-processing/graphstorm_processing/distributed_executor.py
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
  graphstorm-processing/graphstorm_processing/graph_loaders/row_count_utils.py
  graphstorm-processing/graphstorm_processing/graph_loaders/schema_utils.py
  graphstorm-processing/pyproject.toml
  graphstorm-processing/scripts/run_distributed_processing.py
Labels: v0.2, ready

#438 Bug fix for restoring optimizer to cpu
  python/graphstorm/model/utils.py
Labels: ready

#440 Fix yaml
  docs/source/tutorials/own-data.rst
  examples/use_your_own_data/acm_lm_nc.yaml
  examples/use_your_own_data/acm_nc.yaml
  inference_scripts/ep_infer/ml_ec_infer.yaml
  inference_scripts/ep_infer/ml_ec_text_infer.yaml
  inference_scripts/ep_infer/ml_er_infer.yaml
  inference_scripts/ep_infer/ml_lm_ec_infer.yaml
  inference_scripts/ep_infer/test_ec_infer.yaml
  inference_scripts/lp_infer/ml_lm_input_lp_infer.yaml
  inference_scripts/lp_infer/ml_lm_lp_infer.yaml
  inference_scripts/lp_infer/ml_lp_infer.yaml
  inference_scripts/lp_infer/ml_lp_none_train_etype_infer.yaml
  inference_scripts/lp_infer/ml_lp_text_infer.yaml
  inference_scripts/np_infer/ml_nc_infer.yaml
  inference_scripts/np_infer/ml_nc_text_infer.yaml
  tests/end2end-tests/data_process/ml_ec_text.yaml
  training_scripts/gsgnn_ep/ml_ec.yaml
  training_scripts/gsgnn_ep/ml_ec_text.yaml
  training_scripts/gsgnn_ep/ml_er.yaml
  training_scripts/gsgnn_ep/ml_lm_ec.yaml
  training_scripts/gsgnn_ep/test_ec.yaml
  training_scripts/gsgnn_lp/arxiv_lp.yaml
  training_scripts/gsgnn_lp/ml_lm_input_lp.yaml
  training_scripts/gsgnn_lp/ml_lm_lp.yaml
  training_scripts/gsgnn_lp/ml_lp.yaml
  training_scripts/gsgnn_lp/ml_lp_none_train_etype.yaml
  training_scripts/gsgnn_lp/ml_lp_text.yaml
  training_scripts/gsgnn_np/ml_nc.yaml
  training_scripts/gsgnn_np/ml_nc_mgpu.yaml
  training_scripts/gsgnn_np/ml_nc_utext.yaml
  training_scripts/gsgnn_np/ml_nc_utext_glem.yml
  training_scripts/gsgnn_np/ml_nc_utext_roberta.yaml
  training_scripts/gsgnn_np/ml_nr.yaml
Labels: v0.2, ready

#412 Update GSgnnLinkPredictionModelInterface and support mini-batch based full graph inference
  python/graphstorm/config/argument.py
  python/graphstorm/inference/lp_infer.py
  python/graphstorm/model/embed.py
  python/graphstorm/model/gnn.py
  python/graphstorm/model/gnn_encoder_base.py
  python/graphstorm/model/lp_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
  python/graphstorm/trainer/lp_trainer.py
  python/graphstorm/trainer/np_trainer.py
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
  tests/unit-tests/test_config.py
  tests/unit-tests/test_gnn.py
Labels: v0.2, ready

#442 argument num_classess > 0 instead of > 1
  python/graphstorm/config/argument.py
  tests/unit-tests/test_config.py
Labels: v0.2, ready

#441 Store bert embeddings with float16
  python/graphstorm/model/lm_embed.py
  tests/unit-tests/test_embed.py
Labels: ready

#420 Update the implementation of getting edge features for link prediction decoders.
  python/graphstorm/dataloading/__init__.py
  python/graphstorm/dataloading/dataloading.py
  python/graphstorm/dataloading/dataset.py
  python/graphstorm/model/edge_decoder.py
  python/graphstorm/model/gnn_encoder_base.py
  python/graphstorm/model/lp_gnn.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/trainer/lp_trainer.py
  tests/unit-tests/test_decoder.py
Labels: v0.2, ready

#418 Update the implementation of getting edge features for edge decoders.
  python/graphstorm/dataloading/__init__.py
  python/graphstorm/dataloading/dataloading.py
  python/graphstorm/dataloading/dataset.py
  python/graphstorm/model/edge_decoder.py
  python/graphstorm/model/edge_gnn.py
  python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
  python/graphstorm/run/gsgnn_ep/ep_infer_lm.py
  python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
  python/graphstorm/run/gsgnn_ep/gsgnn_lm_ep.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
  python/graphstorm/trainer/ep_trainer.py
  tests/unit-tests/test_decoder.py
  tests/unit-tests/test_gnn.py
Labels: v0.2, ready

#446 Remove unnecessary rank argument.
  docs/source/advanced/own-models.rst
  examples/customized_models/HGT/hgt_nc.py
  python/graphstorm/gsf.py
  python/graphstorm/inference/ep_infer.py
  python/graphstorm/inference/graphstorm_infer.py
  python/graphstorm/inference/lp_infer.py
  python/graphstorm/inference/np_infer.py
  python/graphstorm/model/utils.py
  python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
  python/graphstorm/run/gsgnn_ep/ep_infer_lm.py
  python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
  python/graphstorm/run/gsgnn_ep/gsgnn_lm_ep.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
  python/graphstorm/run/gsgnn_np/gsgnn_np.py
  python/graphstorm/run/gsgnn_np/np_infer_gnn.py
  python/graphstorm/tracker/graphstorm_tracker.py
  python/graphstorm/tracker/sagemaker_tracker.py
  python/graphstorm/trainer/ep_trainer.py
  python/graphstorm/trainer/glem_np_trainer.py
  python/graphstorm/trainer/gsgnn_trainer.py
  python/graphstorm/trainer/lp_trainer.py
  python/graphstorm/trainer/np_trainer.py
  tests/end2end-tests/custom-gnn/train.py
Labels: ready

#449 [GSProcessing] Move to Spark 3.3
  graphstorm-processing/docker/0.1.0/Dockerfile.cpu
  graphstorm-processing/docker/push_gsprocessing_image.sh
  graphstorm-processing/graphstorm_processing/distributed_executor.py
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
  graphstorm-processing/pyproject.toml
  graphstorm-processing/scripts/run_distributed_processing.py
Labels: v0.2, ready

#448 [Doc] rename Infer classes to Inferrer classes
  docs/source/api/graphstorm.inferer.rst
  docs/source/api/graphstorm.inferrer.rst
  docs/source/index.rst
  python/graphstorm/inference/__init__.py
  python/graphstorm/inference/ep_infer.py
  python/graphstorm/inference/graphstorm_infer.py
  python/graphstorm/inference/lp_infer.py
  python/graphstorm/inference/np_infer.py
  python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
  python/graphstorm/run/gsgnn_ep/ep_infer_lm.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
  python/graphstorm/run/gsgnn_np/np_infer_gnn.py
  python/graphstorm/sagemaker/utils.py
Labels: ready

#452 [Bug Fix] Fix separator \t for GConstruct
  python/graphstorm/gconstruct/file_io.py
  tests/unit-tests/gconstruct/test_construct_graph.py
Labels: ready

#453 Fix a bug in the default value of fanout
  python/graphstorm/config/argument.py
Labels: v0.2, ready

#432 Increased the speed and memory efficiency for GLEM in semi-supervised/pseudolabel setting
  python/graphstorm/dataloading/dataset.py
  python/graphstorm/dataloading/utils.py
  python/graphstorm/gsf.py
  python/graphstorm/model/node_glem.py
Labels: ready

#444 [GSProcessing] Add repartitioning code
  graphstorm-processing/graphstorm_processing/repartition_files.py
  graphstorm-processing/scripts/run_repartitioning.py
  graphstorm-processing/tests/resources/repartitioning/partitioned_metadata.json
  graphstorm-processing/tests/test_repartition_files.py
Labels: v0.2, ready

#405 Wholegraph integration
  python/graphstorm/dataloading/dataset.py
  python/graphstorm/dataloading/utils.py
  python/graphstorm/gsf.py
  python/graphstorm/model/edge_gnn.py
  python/graphstorm/model/gnn_encoder_base.py
  python/graphstorm/model/node_gnn.py
  python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/run/gsgnn_np/gsgnn_np.py
  python/graphstorm/utils.py
  tools/README.md
  tools/convert_feat_to_wholegraph.py
Labels: v0.2, ready

#445 Update the model save and restore API.
  python/graphstorm/model/gnn.py
  python/graphstorm/model/node_glem.py
  python/graphstorm/model/utils.py
  tests/unit-tests/test_model_save_load.py
Labels: ready

#407 Add first version for the workflow on GSProcessing
  .github/workflow_scripts/gsprocessing_lint.sh
  .github/workflow_scripts/gsprocessing_pytest.sh
  .github/workflow_scripts/lint_check.sh
  .github/workflows/continuous-integration.yml
  .github/workflows/gsprocessing-workflow.yml
  submitJob.py
Labels: v0.2, ready

#454 Fix BERT fine tune
  python/graphstorm/config/__init__.py
  python/graphstorm/config/argument.py
  python/graphstorm/config/config.py
  python/graphstorm/model/gnn.py
  python/graphstorm/model/lm_embed.py
  python/graphstorm/model/utils.py
  tests/unit-tests/test_config.py
  tests/unit-tests/test_embed.py
  tests/unit-tests/test_gnn.py
Labels: v0.2, ready

#458 [Wholegraph] Support multiple feature conversion in the script
  tools/README.md
  tools/convert_feat_to_wholegraph.py
Labels: v0.2, ready

#459 Fix logging
  python/graphstorm/config/argument.py
Labels: v0.2, ready

#464 Fix a bug in RGCN encoder
  python/graphstorm/model/rgcn_encoder.py
Labels: v0.2, ready

#461 [GSProcessing] Small improvements to version check and config download
  graphstorm-processing/graphstorm_processing/data_transformations/s3_utils.py
  graphstorm-processing/graphstorm_processing/distributed_executor.py
Labels: v0.2, ready

#462 [Bug Fix] Allow Double Asterisk
  .github/workflows/continuous-integration.yml
  .github/workflows/gsprocessing-workflow.yml
Labels: ready

#421 Add base classes for dataloader.
  python/graphstorm/dataloading/__init__.py
  python/graphstorm/dataloading/dataloading.py
Labels: v0.2, ready

#416 Add blog example for GraphStorm 0.2
  examples/mag/MAG_parser_v0.1.ipynb
  examples/mag/README.md
  examples/mag/mag_bert_ft.yaml
  examples/mag/mag_bert_nc.yaml
  examples/mag/mag_gnn_nc.yaml
  examples/mag/mag_v0.2.json
  python/graphstorm/gconstruct/utils.py
Labels: v0.2, ready

#468 Fix the case when some categories do not exist in transform_conf
  python/graphstorm/gconstruct/transform.py
  tests/unit-tests/gconstruct/test_transform.py
Labels: ready

#472 Fix the logging
  python/graphstorm/config/argument.py
  python/graphstorm/dataloading/dataset.py
  python/graphstorm/model/gnn.py
  python/graphstorm/run/launch.py
Labels: v0.2, ready

#463 Enable hdf5 embed writing
  python/graphstorm/config/argument.py
  python/graphstorm/gconstruct/file_io.py
  python/graphstorm/inference/ep_infer.py
  python/graphstorm/inference/lp_infer.py
  python/graphstorm/inference/np_infer.py
  python/graphstorm/model/utils.py
  python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
  python/graphstorm/run/gsgnn_ep/ep_infer_lm.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
  python/graphstorm/run/gsgnn_np/np_infer_gnn.py
  tests/unit-tests/test_utils.py
Labels: v0.2, ready

#473 Support load conf for min/max transformation.
  docs/source/configuration/configuration-gconstruction.rst
  python/graphstorm/gconstruct/transform.py
  tests/end2end-tests/data_process/compare_graphs.py
  tests/end2end-tests/data_process/data_gen.py
  tests/unit-tests/gconstruct/test_transform.py
Labels: v0.2, ready

#477 [Bug Fix] Disable storing embeddings when inferring on ec/er task
  python/graphstorm/inference/ep_infer.py
Labels: ready

#480 [GSProcessing] Improve handling of configs with unknown version.
  graphstorm-processing/graphstorm_processing/distributed_executor.py
Labels: ready

#474 Updated MAG example with GLEM instructions
  examples/mag/README.md
  examples/mag/mag_glem_nc.yaml
  examples/mag/mag_glem_w_pretrain.yml
Labels: ready

#460 [Doc] Reorg API Documentation part-1
  docs/source/_templates/dataloadertemplate.rst
  docs/source/_templates/datasettemplate.rst
  docs/source/_templates/evaltemplate.rst
  docs/source/_templates/inferencetemplate.rst
  docs/source/_templates/modeltemplate.rst
  docs/source/_templates/trainertemplate.rst
  docs/source/api/graphstorm.customized.rst
  docs/source/api/graphstorm.dataloading.rst
  docs/source/api/graphstorm.eval.rst
  docs/source/api/graphstorm.evaluator.rst
  docs/source/api/graphstorm.inference.rst
  docs/source/api/graphstorm.model.rst
  docs/source/api/graphstorm.rst
  docs/source/api/graphstorm.trainer.rst
  docs/source/index.rst
  python/graphstorm/gsf.py
  python/graphstorm/model/edge_gnn.py
  python/graphstorm/model/gnn.py
  python/graphstorm/model/lp_gnn.py
  python/graphstorm/model/node_gnn.py
  python/graphstorm/model/rgat_encoder.py
  python/graphstorm/utils.py
Labels: ready

#484 Enable nccl for embedding save
  python/graphstorm/data/utils.py
  python/graphstorm/eval/utils.py
  python/graphstorm/model/utils.py
  tests/unit-tests/test_utils.py
Labels: enhancement, 0.3, ready

#479 Use zfill to make sure the saved embeddings or prediction results are sortable.
  python/graphstorm/model/utils.py
  tests/unit-tests/test_model_save_load.py
  tests/unit-tests/test_utils.py
Labels: enhancement, ready

#491 [Bug Fix] Change on EC test
  python/graphstorm/model/edge_gnn.py
  python/graphstorm/trainer/ep_trainer.py
Labels: enhancement, ready

#489 [BugFix] Handle the case when user provides test_mask but do not want to do validation.
  python/graphstorm/dataloading/dataset.py
  python/graphstorm/run/gsgnn_np/np_infer_gnn.py
  tests/unit-tests/test_dataloading.py
Labels: bug, v0.2, ready

#493 Fix the problem of caching twice
  python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_np/np_infer_gnn.py
Labels: v0.2, ready

#490 [GSProcessing] Name reverse edges as `dst:relation-rev:src`
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
  graphstorm-processing/graphstorm_processing/repartition_files.py
  graphstorm-processing/tests/resources/repartitioning/partitioned_metadata.json
  graphstorm-processing/tests/test_dist_heterogenous_loader.py
  graphstorm-processing/tests/test_repartition_files.py
Labels: v0.2, ready

#496 Fix lint does not work with astroid==3.0 error.
  .github/workflow_scripts/lint_check.sh
Labels: ready

#485 [Wholegraph] Build docker image for WholeGraph-GraphStorm
  docker/build_docker_wholegraph.sh
  docker/wholegraph/Dockerfile
  docker/wholegraph/install_wholegraph.sh
Labels: v0.2

#497 [Bug Fix] Add test to EC
  tests/end2end-tests/graphstorm-ec/mgpu_test.sh
Labels: v0.2, ready

#467 [GSProcessing] Add documentation
  graphstorm-processing/docs/Makefile
  graphstorm-processing/docs/make.bat
  graphstorm-processing/docs/source/conf.py
  graphstorm-processing/docs/source/developer/developer-guide.rst
  graphstorm-processing/docs/source/developer/input-configuration.rst
  graphstorm-processing/docs/source/index.rst
  graphstorm-processing/docs/source/usage/amazon-sagemaker.rst
  graphstorm-processing/docs/source/usage/distributed-processing-setup.rst
  graphstorm-processing/docs/source/usage/example.rst
Labels: documentation, ready

#470 [Doc] Add Doc String for graphstorm.dataloading.dataset
  python/graphstorm/dataloading/dataset.py
Labels: documentation

#456 [Doc Model] Add Doc String for graphstorm.model
  python/graphstorm/model/embed.py
  python/graphstorm/model/hgt_encoder.py
  python/graphstorm/model/rgat_encoder.py
  python/graphstorm/model/rgcn_encoder.py
  python/graphstorm/model/sage_encoder.py
Labels: documentation, ready

#500 [Bug Fix] Fix HGT example's infer to inferrer
  examples/customized_models/HGT/hgt_nc.py
Labels: bug, v0.2, ready

#495 [Bug fix]Fix hgt_encoder no edge error
  python/graphstorm/model/hgt_encoder.py
Labels: bug, v0.2, ready

#487 Add a config to compute GNN embeddings for GNN inference.
  examples/mag/mag_gnn_infer.yaml
Labels: v0.2, ready

#507 Update contributors
  CONTRIBUTORS.md
Labels: documentation, v0.2

#504 [Doc] Add Doc String for graphstorm.dataloading.dataloading
  python/graphstorm/dataloading/dataloading.py
Labels: documentation, v0.2, ready

#503 [Doc] Add Doc String for graphstorm.dataloading.dataset
  python/graphstorm/dataloading/dataset.py
Labels: documentation, v0.2, ready

#488 [Doc] Add docstrings for trainer module user-facing classes
  python/graphstorm/trainer/ep_trainer.py
  python/graphstorm/trainer/glem_np_trainer.py
  python/graphstorm/trainer/gsgnn_trainer.py
  python/graphstorm/trainer/lp_trainer.py
  python/graphstorm/trainer/np_trainer.py
Labels: documentation, v0.2, ready

#505 [Doc] Improving instruction for a distributed setting
  README.md
  docker/README.md
  docs/source/install/env-setup.rst
  docs/source/scale/distributed.rst
Labels: documentation, v0.2, ready

#502 Move GSProcessing docs to main repo documentation.
  docs/source/gs-processing/developer/developer-guide.rst
  docs/source/gs-processing/developer/input-configuration.rst
  docs/source/gs-processing/gs-processing-getting-started.rst
  docs/source/gs-processing/usage/amazon-sagemaker.rst
  docs/source/gs-processing/usage/distributed-processing-setup.rst
  docs/source/gs-processing/usage/example.rst
  docs/source/index.rst
  graphstorm-processing/docker/build_gsprocessing_image.sh
  graphstorm-processing/docs/Makefile
  graphstorm-processing/docs/make.bat
  graphstorm-processing/docs/source/conf.py
Labels: documentation, v0.2

#387 add an temporal graph example
  docs/source/advanced/advanced-usages.rst
  examples/temporal_graph_learning/README.md
  examples/temporal_graph_learning/gen_graph.py
  examples/temporal_graph_learning/gnn_encoder.py
  examples/temporal_graph_learning/graphstorm_train_script_nc_config.yaml
  examples/temporal_graph_learning/input_encoder.py
  examples/temporal_graph_learning/ip_config.txt
  examples/temporal_graph_learning/main_nc.py
  examples/temporal_graph_learning/model_nc.py
  examples/temporal_graph_learning/model_utils.py
Labels: v0.2

#443 Step2 distill
  docs/source/configuration/configuration-run.rst
  python/graphstorm/config/argument.py
  python/graphstorm/dataloading/__init__.py
  python/graphstorm/dataloading/dataloading.py
  python/graphstorm/dataloading/dataset.py
  python/graphstorm/dataloading/sampler.py
  python/graphstorm/distiller/__init__.py
  python/graphstorm/distiller/distiller.py
  python/graphstorm/model/gnn_distill/__init__.py
  python/graphstorm/model/gnn_distill/student.py
  python/graphstorm/run/gs_gnn_distillation.py
  python/graphstorm/run/gsgnn_dt/__init__.py
  python/graphstorm/run/gsgnn_dt/distill_gnn.py
  tests/unit-tests/data_utils.py
  tests/unit-tests/test_config.py
  tests/unit-tests/test_dataloading.py
  training_scripts/gsgnn_dt/README.md
  training_scripts/gsgnn_dt/distill.yaml
Labels: v0.2, ready

#483 Glem restore bug fix
  examples/mag/README.md
  python/graphstorm/config/argument.py
  python/graphstorm/model/node_glem.py
  tests/end2end-tests/graphstorm-nc/mgpu_test.sh
Labels: bug, v0.2, ready

#469 Add another processing script for MAG
  examples/mag/MAG_parser_v0.2.ipynb
  examples/mag/README.md
Labels: v0.2, ready

#514 Add partition command and SageMaker parameters to SageMaker docs
  docs/source/scale/sagemaker.rst
Labels: documentation, v0.2

#498 Glem full graph inference
  python/graphstorm/model/gnn.py
  python/graphstorm/model/node_glem.py
  python/graphstorm/trainer/glem_np_trainer.py
  tests/end2end-tests/graphstorm-nc/mgpu_test.sh
Labels: bug, v0.2, ready
