Repository awslabs/graphstorm, pull requests merged in 2023-10, with the labels that each got.

#515 [Doc] Add wholegraph tutorial
  docs/source/advanced/advanced-usages.rst
  docs/source/advanced/advanced-wholegraph.rst
  docs/source/index.rst
  tutorial/wholegraph-nccl.png
  tutorial/wholegraph-signal.png
Labels: documentation, v0.2, ready

#518 Bump version to 0.3
  .github/workflow_scripts/lint_check.sh
  python/graphstorm/__init__.py
Labels: ready

#494 Add logging for debugging purpose.
  python/graphstorm/dataloading/dataset.py
  python/graphstorm/inference/ep_infer.py
  python/graphstorm/inference/np_infer.py
  python/graphstorm/model/edge_gnn.py
  python/graphstorm/model/embed.py
  python/graphstorm/model/gnn.py
  python/graphstorm/model/gnn_encoder_base.py
  python/graphstorm/model/lm_embed.py
  python/graphstorm/model/node_gnn.py
  python/graphstorm/utils.py
Labels: ready, 0.2.1

#524 Update save prediction
  .github/workflow_scripts/lint_check.sh
  python/graphstorm/inference/ep_infer.py
  python/graphstorm/inference/np_infer.py
  python/graphstorm/model/utils.py
  tests/unit-tests/gconstruct/test_transform.py
  tests/unit-tests/test_utils.py
Labels: ready

#527 Change the way how node embeddings are saved
  python/graphstorm/model/utils.py
  tests/end2end-tests/check_infer.py
  tests/unit-tests/test_utils.py
Labels: ready, 0.2.1

#536 [Doc] Add return_proba argument explanation
  docs/source/configuration/configuration-run.rst
Labels: documentation, ready, 0.2.1

#481 Change save prediction logic of edge prediction tasks
  python/graphstorm/inference/ep_infer.py
  python/graphstorm/model/utils.py
  tests/end2end-tests/graphstorm-ec/mgpu_test.sh
  tests/unit-tests/test_utils.py
Labels: ready, 0.2.1

#539 [Doc] Fix bolding font format error in the configuration-run rst file
  docs/source/configuration/configuration-run.rst
Labels: documentation, ready, 0.2.1

#537 Bug fix dist model save
  python/graphstorm/trainer/gsgnn_trainer.py
  tests/end2end-tests/graphstorm-nc/test.sh
Labels: ready

#538 Allow Sagemaker training jobs resume an existing checkpoint
  .github/workflow_scripts/lint_check.sh
  docs/source/scale/sagemaker.rst
  python/graphstorm/sagemaker/sagemaker_train.py
  sagemaker/README.md
  sagemaker/launch/launch_train.py
  sagemaker/run/train_entry.py
Labels: enhancement, ready, 0.2.1

#530 [Documentation] Standalone mode demo notebook
  examples/standalone_mode_demo.ipynb
  python/graphstorm/eval/evaluator.py
Labels: documentation, ready, 0.2.1

#523 Add the LM embedding cache
  examples/mag/mag_gnn_nc.yaml
  python/graphstorm/config/argument.py
  python/graphstorm/gsf.py
  python/graphstorm/model/lm_embed.py
  python/graphstorm/model/utils.py
  tests/end2end-tests/graphstorm-nc/mgpu_test.sh
  tests/unit-tests/data_utils.py
  tests/unit-tests/test_embed.py
Labels: ready

#525 Add Command Line for Embedding Generating
  python/graphstorm/inference/__init__.py
  python/graphstorm/inference/emb_infer.py
  python/graphstorm/run/gs_gen_node_embedding.py
  python/graphstorm/run/gsgnn_emb/__init__.py
  python/graphstorm/run/gsgnn_emb/gsgnn_node_emb.py
  python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/run/gsgnn_np/gsgnn_np.py
  python/graphstorm/run/launch.py
  tests/end2end-tests/graphstorm-ec/mgpu_test.sh
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
  tests/end2end-tests/graphstorm-nc/mgpu_test.sh
Labels: ready

#559 [Doc] Add docstring of evaluator's history
  docs/source/_templates/evaltemplate.rst
  python/graphstorm/eval/evaluator.py
Labels: documentation, ready, 0.2.1

#562 [Bug Fix] Fix RGAT when inputs of rgat.forward have shape (0, x)
  python/graphstorm/model/hgt_encoder.py
  python/graphstorm/model/rgat_encoder.py
  tests/unit-tests/test_nn_model.py
Labels: bug, ready, 0.2.1

#565 [Wholegraph-feature] Enable inference support using WholeGraph
  python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_np/np_infer_gnn.py
Labels: ready, 0.2.1

#585 Fix the bug when there are edges with missing src or dst nodes, the num edge features != num edges
  python/graphstorm/gconstruct/construct_graph.py
  python/graphstorm/gconstruct/id_map.py
  tests/unit-tests/gconstruct/test_construct_graph.py
Labels: bug, ready, 0.2.1

#580 Update the way of getting length of dataloader
  python/graphstorm/dataloading/dataloading.py
  python/graphstorm/model/edge_gnn.py
  python/graphstorm/model/gnn_encoder_base.py
  python/graphstorm/model/node_gnn.py
  tests/unit-tests/test_dataloading.py
Labels: ready, 0.2.1

#567 [Doc] Doc for Generating Node Embeddings
  docs/source/tutorials/quick-start.rst
Labels: ready

#584 Fix a bug in gconstruct
  python/graphstorm/gconstruct/construct_graph.py
  python/graphstorm/gconstruct/file_io.py
  tests/end2end-tests/data_process/data_gen.py
Labels: ready

#542 update first version cancel workflow
  .github/workflows/continuous-integration.yml
Labels: enhancement

#529 Num Bucket for GConstruct
  docs/source/configuration/configuration-gconstruction.rst
  python/graphstorm/gconstruct/transform.py
  tests/end2end-tests/data_process/data_gen.py
  tests/end2end-tests/data_process/test_data.py
  tests/unit-tests/gconstruct/test_transform.py
Labels: ready

#506 Allows customization of GLEM trainable parameters grouping
  python/graphstorm/config/argument.py
  python/graphstorm/dataloading/utils.py
  python/graphstorm/model/node_glem.py
  python/graphstorm/trainer/glem_np_trainer.py
  training_scripts/gsgnn_np/ml_nc_utext_glem.yml
Labels: ready

#589 Raise an error when gconstruct reads empty files.
  python/graphstorm/gconstruct/file_io.py
  tests/unit-tests/gconstruct/test_gconstruct_utils.py
Labels: ready

#569 fix no in-degree destination nodes error
  python/graphstorm/model/hgt_encoder.py
  tests/unit-tests/test_nn_model.py
Labels: bug, ready, 0.2.1

#587 Fix load embeding
  python/graphstorm/model/lm_embed.py
  python/graphstorm/model/utils.py
  python/graphstorm/utils.py
  tests/unit-tests/test_embed.py
Labels: bug, ready

#533 Add support for remapping edge prediction results.
  python/graphstorm/gconstruct/id_map.py
  python/graphstorm/gconstruct/remap_result.py
  python/graphstorm/gconstruct/utils.py
  python/graphstorm/model/utils.py
  python/graphstorm/run/gs_edge_classification.py
  python/graphstorm/run/gs_edge_regression.py
  python/graphstorm/run/launch.py
  tests/end2end-tests/data_process/check_edge_predict_remap.py
  tests/end2end-tests/data_process/gen_edge_predict_remap_test.py
  tests/end2end-tests/data_process/test.sh
  tests/end2end-tests/graphstorm-ec/mgpu_test.sh
  tests/unit-tests/gconstruct/test_construct_graph.py
  tests/unit-tests/gconstruct/test_remap_result.py
  tests/unit-tests/test_utils.py
Labels: ready, 0.2.1

#591 [Bug fix] Fix RGCN not support different dims issue and unify no in-degree behavior
  python/graphstorm/model/hgt_encoder.py
  python/graphstorm/model/rgat_encoder.py
  python/graphstorm/model/rgcn_encoder.py
  tests/unit-tests/test_nn_model.py
Labels: bug, ready, 0.2.1

#593 Speed up sampling for constructing node features.
  python/graphstorm/dataloading/dataloading.py
Labels: ready

#599 [Doc] Modify index page to add gprocessing contents
  docs/source/gs-processing/gs-processing-getting-started.rst
  docs/source/index.rst
Labels: documentation, ready, 0.2.1

#578 Add support for remapping node prediction results
  python/graphstorm/gconstruct/remap_result.py
  python/graphstorm/inference/np_infer.py
  python/graphstorm/run/gs_node_classification.py
  python/graphstorm/run/gs_node_regression.py
  tests/end2end-tests/data_process/check_node_predict_remap.py
  tests/end2end-tests/data_process/gen_node_predict_remap_test.py
  tests/end2end-tests/data_process/test.sh
  tests/end2end-tests/graphstorm-ec/mgpu_test.sh
  tests/end2end-tests/graphstorm-nc/mgpu_test.sh
  tests/end2end-tests/graphstorm-nc/test.sh
  tests/unit-tests/gconstruct/test_remap_result.py
Labels: ready, 0.2.1

#377 Update docker to Torch 2.1.0+CUDA11.8 to resolve multi-sampler issue
  README.md
  docker/Dockerfile.local
  docs/source/install/env-setup.rst
Labels: ready, 0.2.1

#553 Bug fix multiple lms
  python/graphstorm/model/lm_embed.py
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
  training_scripts/gsgnn_lp/ml_lp_text_multiple_lm_models.yaml
Labels: ready

#575 [GSProcessing] Add support for numerical and multi-numerical transformations.
  docs/source/gs-processing/developer/input-configuration.rst
  docs/source/index.rst
  graphstorm-processing/graphstorm_processing/config/config_conversion/converter_base.py
  graphstorm-processing/graphstorm_processing/config/config_conversion/gconstruct_converter.py
  graphstorm-processing/graphstorm_processing/config/config_parser.py
  graphstorm-processing/graphstorm_processing/config/feature_config_base.py
  graphstorm-processing/graphstorm_processing/config/numerical_configs.py
  graphstorm-processing/graphstorm_processing/constants.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_feature_transformer.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/__init__.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_numerical_transformation.py
  graphstorm-processing/graphstorm_processing/data_transformations/spark_utils.py
  graphstorm-processing/graphstorm_processing/graph_loaders/schema_utils.py
  graphstorm-processing/tests/resources/small_heterogeneous_graph/gsprocessing-config.json
  graphstorm-processing/tests/test_converter.py
  graphstorm-processing/tests/test_dist_heterogenous_loader.py
  graphstorm-processing/tests/test_dist_label_loader.py
  graphstorm-processing/tests/test_dist_numerical_transformation.py
Labels: ready, 0.2.1, gsprocessing

#594 [Bug Fix] Fix on max min bound
  python/graphstorm/gconstruct/transform.py
  tests/unit-tests/gconstruct/test_transform.py
Labels: ready

#596 Add support in-batch joint negative
  python/graphstorm/dataloading/__init__.py
  python/graphstorm/dataloading/dataloading.py
  python/graphstorm/dataloading/sampler.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  tests/unit-tests/test_dataloading.py
Labels: ready

#602 [Feature] Add gat_encoder
  python/graphstorm/model/gat_encoder.py
  tests/unit-tests/test_gnn.py
Labels: enhancement, ready, 0.2.1

#549 [Performance] Support NCCL backed for sparse embedding
  python/graphstorm/model/embed.py
Labels: ready, 0.2.1

#605 [Bug fix] Fix the error report when the input dir is empty
  python/graphstorm/gconstruct/file_io.py
  tests/unit-tests/gconstruct/test_gconstruct_utils.py
Labels: bug, ready

#598 [Wholegraph] Refactor wholegraph inference
  python/graphstorm/dataloading/dataset.py
  python/graphstorm/gsf.py
  python/graphstorm/model/edge_gnn.py
  python/graphstorm/model/gnn_encoder_base.py
  python/graphstorm/model/node_gnn.py
  python/graphstorm/utils.py
  tests/unit-tests/test_utils.py
Labels: ready, 0.2.1

#608 [Cleaning] Clean code for ACM example data
  examples/acm_data.py
  examples/utils.py
Labels: enhancement, ready
