Repository awslabs/graphstorm, pull requests merged in 2023-11, with the labels that each got.

#607 Enable GAT as builtin model
  docs/source/configuration/configuration-run.rst
  python/graphstorm/config/config.py
  python/graphstorm/gsf.py
Labels: ready

#583 [GSProcessing] Add support for bucket transformations
  docs/source/gs-processing/developer/input-configuration.rst
  graphstorm-processing/graphstorm_processing/config/config_conversion/gconstruct_converter.py
  graphstorm-processing/graphstorm_processing/config/config_parser.py
  graphstorm-processing/graphstorm_processing/config/numerical_configs.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_feature_transformer.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/__init__.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_bucket_numerical_transformation.py
  graphstorm-processing/graphstorm_processing/graph_loaders/schema_utils.py
  graphstorm-processing/tests/test_converter.py
  graphstorm-processing/tests/test_dist_bucket_transformation.py
Labels: ready, gsprocessing

#610 [Enhancement] Exclude docs folder from triggering CI
  .github/workflows/continuous-integration.yml
Labels: ready

#588 [Enhancement] Always cache LM when training GLEM GNN to speed up training
  python/graphstorm/config/argument.py
  python/graphstorm/model/lm_embed.py
  python/graphstorm/model/node_glem.py
  python/graphstorm/trainer/glem_np_trainer.py
  tests/end2end-tests/graphstorm-nc/mgpu_test.sh
Labels: ready

#611 Bug fix for GLEM LM forward pass with additional node feats
  python/graphstorm/model/node_glem.py
Labels: bug, ready

#581 [Wholegraph] Add support for edge feature
  python/graphstorm/dataloading/dataset.py
  python/graphstorm/model/edge_gnn.py
  python/graphstorm/model/gnn_encoder_base.py
  tests/unit-tests/test_utils.py
  tools/README.md
  tools/convert_feat_to_wholegraph.py
Labels: ready, 0.2.1

#601 Random select the subset of validation set in lp when validation set is huge
  docs/source/configuration/configuration-run.rst
  python/graphstorm/config/argument.py
  python/graphstorm/dataloading/dataloading.py
  python/graphstorm/dataloading/sampler.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  tests/unit-tests/test_dataloading.py
Labels: ready

#597 Add support to remap saved node embeddings into original node iD space.
  docs/source/configuration/configuration-run.rst
  python/graphstorm/gconstruct/remap_result.py
  python/graphstorm/inference/emb_infer.py
  python/graphstorm/inference/ep_infer.py
  python/graphstorm/inference/lp_infer.py
  python/graphstorm/model/utils.py
  python/graphstorm/run/gs_edge_classification.py
  python/graphstorm/run/gs_edge_regression.py
  python/graphstorm/run/gs_gen_node_embedding.py
  python/graphstorm/run/gs_node_classification.py
  python/graphstorm/run/gs_node_regression.py
  python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
  python/graphstorm/run/gsgnn_ep/gsgnn_lm_ep.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/run/gsgnn_np/gsgnn_np.py
  python/graphstorm/run/launch.py
  tests/end2end-tests/check_infer.py
  tests/end2end-tests/check_np_infer_emb.py
  tests/end2end-tests/data_process/check_emb_remap.py
  tests/end2end-tests/data_process/gen_emb_predict_remap_test.py
  tests/end2end-tests/data_process/test.sh
  tests/end2end-tests/graphstorm-ec/mgpu_test.sh
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
  tests/end2end-tests/graphstorm-nc/mgpu_test.sh
  tests/end2end-tests/graphstorm-nc/test.sh
  tests/unit-tests/gconstruct/test_remap_result.py
  tests/unit-tests/test_utils.py
Labels: ready, 0.2.1

#615 [GSProcessing] Add support for Rank-Gauss Feature Transformation
  docs/source/gs-processing/developer/input-configuration.rst
  graphstorm-processing/graphstorm_processing/config/config_conversion/gconstruct_converter.py
  graphstorm-processing/graphstorm_processing/config/numerical_configs.py
  graphstorm-processing/graphstorm_processing/constants.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_numerical_transformation.py
  graphstorm-processing/pyproject.toml
  graphstorm-processing/tests/test_converter.py
  graphstorm-processing/tests/test_dist_numerical_transformation.py
Labels: ready, 0.2.1, gsprocessing

#616 Add self-loop in message passing for GAT
  python/graphstorm/model/gat_encoder.py
  tests/unit-tests/test_gnn.py
Labels: ready, 0.2.1

#620 [Doc] Add LP Command in the Quick Start
  docs/source/tutorials/own-data.rst
  docs/source/tutorials/quick-start.rst
  tools/partition_graph_lp.py
  training_scripts/gsgnn_lp/arxiv_lp.yaml
Labels: documentation, enhancement, ready, 0.2.1

#613 [GSProcessing] Add support for EMR Serverless execution
  docs/source/gs-processing/developer/input-configuration.rst
  docs/source/gs-processing/gs-processing-getting-started.rst
  docs/source/gs-processing/usage/amazon-sagemaker.rst
  docs/source/gs-processing/usage/distributed-processing-setup.rst
  docs/source/gs-processing/usage/emr-serverless.rst
  docs/source/gs-processing/usage/example.rst
  docs/source/index.rst
  graphstorm-processing/docker/0.1.0/sagemaker/Dockerfile.cpu
  graphstorm-processing/docker/0.2.1/emr-serverless/Dockerfile.cpu
  graphstorm-processing/docker/build_gsprocessing_image.sh
  graphstorm-processing/docker/push_gsprocessing_image.sh
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_label_transformation.py
  graphstorm-processing/graphstorm_processing/data_transformations/s3_utils.py
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
  graphstorm-processing/tests/test_s3_utils.py
Labels: documentation, ready, 0.2.1, gsprocessing

#626 Change _N and _E to dgl.distributed.constants DEFAULT_NTYPE and DEFAULT_ETYPE
  python/graphstorm/data/ogbn_datasets.py
  python/graphstorm/gsf.py
  python/graphstorm/model/gat_encoder.py
  python/graphstorm/model/sage_encoder.py
  tests/unit-tests/data_utils.py
  tests/unit-tests/test_gnn.py
  tools/partition_graph.py
Labels: ready, 0.2.1

#617 Add more test for remap without shared file system setting
  python/graphstorm/gconstruct/remap_result.py
  python/graphstorm/run/launch.py
  tests/end2end-tests/check_predict_result.py
  tests/end2end-tests/graphstorm-ec/mgpu_test.sh
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
  tests/end2end-tests/graphstorm-nc/mgpu_test.sh
Labels: ready, 0.2.1

#619 Add contrastive loss for link prediction tasks.
  docs/source/configuration/configuration-run.rst
  python/graphstorm/config/__init__.py
  python/graphstorm/config/argument.py
  python/graphstorm/config/config.py
  python/graphstorm/gsf.py
  python/graphstorm/model/__init__.py
  python/graphstorm/model/edge_decoder.py
  python/graphstorm/model/loss_func.py
  python/graphstorm/model/lp_gnn.py
  tests/end2end-tests/graphstorm-lp/test.sh
  tests/unit-tests/test_decoder.py
Labels: ready

#606 [Wholegraph] Merge wholegraph dev to master
  .github/workflow_scripts/lint_check.sh
  docs/source/advanced/advanced-wholegraph.rst
  python/graphstorm/dataloading/dataset.py
  python/graphstorm/gsf.py
  python/graphstorm/model/edge_gnn.py
  python/graphstorm/model/gnn_encoder_base.py
  python/graphstorm/model/node_gnn.py
  python/graphstorm/utils.py
  tests/unit-tests/test_utils.py
  tools/README.md
  tools/convert_feat_to_wholegraph.py
Labels: ready, 0.2.1

#590 Multi Column Feature for Gconstruct
  docs/source/configuration/configuration-gconstruction.rst
  python/graphstorm/gconstruct/construct_graph.py
  python/graphstorm/gconstruct/file_io.py
  python/graphstorm/gconstruct/transform.py
  python/graphstorm/gconstruct/utils.py
  tests/end2end-tests/data_process/data_gen.py
  tests/end2end-tests/data_process/test_data.py
  tests/unit-tests/gconstruct/test_construct_graph.py
Labels: ready, 0.2.1

#623 [GSProcessing] Categorical Feature Transformation
  docs/source/gs-processing/developer/input-configuration.rst
  graphstorm-processing/graphstorm_processing/config/categorical_configs.py
  graphstorm-processing/graphstorm_processing/config/config_conversion/gconstruct_converter.py
  graphstorm-processing/graphstorm_processing/config/config_parser.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_feature_transformer.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_category_transformation.py
  graphstorm-processing/graphstorm_processing/graph_loaders/schema_utils.py
  graphstorm-processing/tests/test_converter.py
  graphstorm-processing/tests/test_dist_category_transformation.py
Labels: ready

#561 Fix bug in constructing node features from neighbor nodes with only BERT embeddings
  inference_scripts/np_infer/ml_nc_movie_text_infer.yaml
  python/graphstorm/dataloading/dataloading.py
  python/graphstorm/dataloading/dataset.py
  python/graphstorm/gconstruct/file_io.py
  python/graphstorm/gsf.py
  python/graphstorm/model/embed.py
  python/graphstorm/model/gnn.py
  python/graphstorm/model/lm_embed.py
  python/graphstorm/model/utils.py
  python/graphstorm/run/gsgnn_emb/gsgnn_node_emb.py
  python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
  python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_np/gsgnn_np.py
  python/graphstorm/run/gsgnn_np/np_infer_gnn.py
  python/graphstorm/utils.py
  tests/end2end-tests/check_infer.py
  tests/end2end-tests/create_data.sh
  tests/end2end-tests/data_gen/movielens_movie_lm_encoder.json
  tests/end2end-tests/graphstorm-nc/mgpu_test.sh
  tests/unit-tests/data_utils.py
  tests/unit-tests/test_gnn.py
  training_scripts/gsgnn_np/ml_nc_movie_utext.yaml
Labels: bug, ready, 0.2.1

#625 [Doc] Add Link Prediciton to Use Your Own Graph tutorial
  docs/source/tutorials/own-data.rst
  examples/acm_data.py
  examples/use_your_own_data/acm_lp.yaml
Labels: documentation, ready, 0.2.1

#627 [SageMaker] Move SageMaker partition job to use SageMaker Processing instead of Training
  docker/build_docker_sagemaker.sh
  docker/sagemaker/Dockerfile.sm
  python/graphstorm/sagemaker/sagemaker_partition.py
  sagemaker/launch/launch_partition.py
Labels: ready

#631 [GSProcessing] SagMaker Dockerfile for v0.2.1
  graphstorm-processing/docker/0.2.1/sagemaker/Dockerfile.cpu
Labels: ready

#628 [GSProcessing] Add thread-parallelism to in-memory repartition implementation.
  docs/source/gs-processing/usage/amazon-sagemaker.rst
  docs/source/gs-processing/usage/emr-serverless.rst
  docs/source/gs-processing/usage/example.rst
  docs/source/gs-processing/usage/row-count-alignment.rst
  graphstorm-processing/graphstorm_processing/repartition_files.py
  graphstorm-processing/scripts/run_repartitioning.py
  graphstorm-processing/tests/test_repartition_files.py
Labels: ready, gsprocessing

#630 [GSProcessing] Bump version to 0.2.1, add support for arm64 images for EMR Serverless
  docs/source/gs-processing/usage/amazon-sagemaker.rst
  docs/source/gs-processing/usage/distributed-processing-setup.rst
  docs/source/gs-processing/usage/emr-serverless.rst
  graphstorm-processing/docker/0.2.1/emr-serverless/Dockerfile.cpu
  graphstorm-processing/docker/build_gsprocessing_image.sh
  graphstorm-processing/docker/push_gsprocessing_image.sh
  graphstorm-processing/pyproject.toml
  graphstorm-processing/tests/resources/small_heterogeneous_graph/gsprocessing-config.json
Labels: documentation, ready, gsprocessing

#635 [GSProcessing] Don't produce masks when no labels present, other small fixes
  docs/source/gs-processing/developer/developer-guide.rst
  docs/source/gs-processing/developer/input-configuration.rst
  docs/source/gs-processing/gs-processing-getting-started.rst
  docs/source/gs-processing/usage/distributed-processing-setup.rst
  graphstorm-processing/docker/0.2.1/sagemaker/Dockerfile.cpu
  graphstorm-processing/docker/build_gsprocessing_image.sh
  graphstorm-processing/docker/push_gsprocessing_image.sh
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
  graphstorm-processing/graphstorm_processing/repartition_files.py
  graphstorm-processing/tests/test_dist_heterogenous_loader.py
Labels: documentation, ready, gsprocessing

#633 Update GraphStorm SageMaker solution to support Node ID remapping.
  python/graphstorm/config/__init__.py
  python/graphstorm/config/config.py
  python/graphstorm/run/launch.py
  python/graphstorm/sagemaker/sagemaker_infer.py
  python/graphstorm/sagemaker/sagemaker_train.py
  python/graphstorm/sagemaker/utils.py
  sagemaker/launch/common_parser.py
  sagemaker/launch/launch_infer.py
  sagemaker/run/infer_entry.py
Labels: ready

#640 Support load nid mapping from mapping files saved by dgl distpartition tools
  python/graphstorm/config/argument.py
  python/graphstorm/model/utils.py
  sagemaker/launch/launch_infer.py
  tests/unit-tests/test_config.py
  tests/unit-tests/test_utils.py
Labels: ready, 0.2.1

#634 Allow applying normalization to GNN embeddings for link prediction.
  docs/source/configuration/configuration-run.rst
  python/graphstorm/config/__init__.py
  python/graphstorm/config/argument.py
  python/graphstorm/config/config.py
  python/graphstorm/gsf.py
  python/graphstorm/inference/emb_infer.py
  python/graphstorm/inference/ep_infer.py
  python/graphstorm/inference/lp_infer.py
  python/graphstorm/inference/np_infer.py
  python/graphstorm/model/__init__.py
  python/graphstorm/model/edge_gnn.py
  python/graphstorm/model/gat_encoder.py
  python/graphstorm/model/gnn.py
  python/graphstorm/model/hgt_encoder.py
  python/graphstorm/model/lp_gnn.py
  python/graphstorm/model/node_glem.py
  python/graphstorm/model/node_gnn.py
  python/graphstorm/model/rgat_encoder.py
  python/graphstorm/model/rgcn_encoder.py
  python/graphstorm/model/sage_encoder.py
  python/graphstorm/model/utils.py
  python/graphstorm/trainer/ep_trainer.py
  python/graphstorm/trainer/lp_trainer.py
  python/graphstorm/trainer/np_trainer.py
  tests/end2end-tests/check_l2_norm_emb.py
  tests/end2end-tests/graphstorm-lp/test.sh
  tests/unit-tests/test_gnn.py
  tests/unit-tests/test_utils.py
Labels: ready, 0.2.1

#643 Version for V0.2.1
  python/graphstorm/__init__.py
Labels: ready

#647 [Bug Fix] Homogeneous Graph Construction
  python/graphstorm/data/ogbn_datasets.py
  python/graphstorm/gsf.py
Labels: ready

#637 Fix bug in constructing node features
  python/graphstorm/dataloading/dataloading.py
  python/graphstorm/model/gnn_encoder_base.py
  python/graphstorm/model/gnn_with_reconstruct.py
  python/graphstorm/run/gsgnn_np/gsgnn_np.py
  tests/unit-tests/data_utils.py
Labels: ready

#654 [Bug Fix] GC for ExtFeatureWrapper
  python/graphstorm/gconstruct/utils.py
Labels: ready, 0.2.1

#653 [Bug Fix] Fix bug when loading ID mapping generated by dgl convert_partition.py
  python/graphstorm/config/argument.py
  python/graphstorm/model/utils.py
  python/graphstorm/sagemaker/sagemaker_infer.py
  python/graphstorm/sagemaker/sagemaker_train.py
  python/graphstorm/sagemaker/utils.py
  tests/unit-tests/test_config.py
  tests/unit-tests/test_utils.py
Labels: ready, 0.2.1

#656 update the main readme
  README.md
Labels: documentation, 0.2.1

#660 Fix a bug in unfreeze
  python/graphstorm/model/lm_embed.py
Labels: ready, 0.2.1

#661 [Bugfix] Update temporal emb and prediction file names
  docs/source/tutorials/quick-start.rst
  python/graphstorm/gconstruct/remap_result.py
  python/graphstorm/model/utils.py
  tests/end2end-tests/check_infer.py
  tests/end2end-tests/check_np_infer_emb.py
  tests/end2end-tests/data_process/check_emb_remap.py
  tests/end2end-tests/data_process/gen_emb_predict_remap_test.py
  tests/end2end-tests/data_process/gen_node_predict_remap_test.py
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
  tests/end2end-tests/graphstorm-nc/mgpu_test.sh
  tests/end2end-tests/graphstorm-nc/test.sh
  tests/unit-tests/test_utils.py
Labels: ready, 0.2.1

#652 [Doc] Fix a few issues in the wholegraph tutorial
  docs/source/advanced/advanced-wholegraph.rst
  docs/source/configuration/configuration-run.rst
  docs/source/scale/distributed.rst
Labels: documentation, 0.2.1

#663 [Doc] Fix doc for Gen-Embedding
  docs/source/tutorials/quick-start.rst
Labels: ready

#665 [Document] Update doc about saved prediction results and embeddings
  docs/source/tutorials/quick-start.rst
  python/graphstorm/gconstruct/remap_result.py
Labels: documentation, 0.2.1

#639 Use external-memory arrays in the worker processes of gconstruct
  python/graphstorm/gconstruct/construct_graph.py
  python/graphstorm/gconstruct/utils.py
  tests/unit-tests/gconstruct/test_gconstruct_utils.py
Labels: ready

#645 Support output data in csv format in remap_result.py
  python/graphstorm/gconstruct/remap_result.py
  tests/end2end-tests/data_process/check_edge_predict_remap.py
  tests/end2end-tests/data_process/check_emb_remap.py
  tests/end2end-tests/data_process/test.sh
  tests/unit-tests/gconstruct/test_remap_result.py
Labels: ready

#669 [Doc] Modify the SageMaker rst title layers to make things clear
  docs/source/scale/sagemaker.rst
Labels: documentation, 0.3

#671 Make remap_result more robust to unknown input args
  python/graphstorm/gconstruct/remap_result.py
Labels: ready

#650 Refactor graphstorm.sagemaker logging printing
  python/graphstorm/model/utils.py
  python/graphstorm/sagemaker/sagemaker_infer.py
  python/graphstorm/sagemaker/sagemaker_train.py
  python/graphstorm/sagemaker/utils.py
  sagemaker/launch/launch_infer.py
  sagemaker/launch/launch_train.py
  sagemaker/run/infer_entry.py
  sagemaker/run/train_entry.py
Labels: ready

#666 [BugFix] Avoid mistakenly printing keep alive failure error message in SageMaker
  python/graphstorm/sagemaker/sagemaker_infer.py
  python/graphstorm/sagemaker/sagemaker_partition.py
  python/graphstorm/sagemaker/sagemaker_train.py
  python/graphstorm/sagemaker/utils.py
Labels: ready
