Repository awslabs/graphstorm, pull requests merged in 2023-07, with the labels that each got.

#227 Add random partitioning on SageMaker. Update run and compose scripts along with instructions.
  docker/build_docker_oss4local.sh
  docker/build_docker_sagemaker.sh
  docker/sagemaker/Dockerfile.sm
  python/graphstorm/sagemaker/partition_algorithm.py
  python/graphstorm/sagemaker/s3_utils.py
  python/graphstorm/sagemaker/sagemaker_partition.py
  python/graphstorm/sagemaker/utils.py
  sagemaker/README.md
  sagemaker/launch/launch_partition.py
  sagemaker/local/generate_sagemaker_docker_compose.py
  sagemaker/run/partition_entry.py
  tests/lint/pylintrc
Labels: v0.2

#349 [BugFix] Fix link prediction inference when the graph does not have train/val/test split
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
Labels: bug

#341 Handle empty edges in graph construction pipelines
  python/graphstorm/gconstruct/id_map.py
  tests/unit-tests/gconstruct/test_construct_graph.py
Labels: v0.1.2

#350 [SageMaker] Allow passing of SageMaker Estimator arguments during job…
  python/graphstorm/sagemaker/utils.py
  sagemaker/README.md
  sagemaker/launch/common_parser.py
  sagemaker/launch/launch_gconstruct.py
  sagemaker/launch/launch_infer.py
  sagemaker/launch/launch_partition.py
  sagemaker/launch/launch_train.py
Labels: v0.2, v0.1.2

#300 [New feature] CPU enablement
  .github/workflow_scripts/e2e_cpu_check.sh
  examples/customized_models/HGT/hgt_nc.py
  python/graphstorm/dataloading/utils.py
  python/graphstorm/gconstruct/transform.py
  python/graphstorm/gsf.py
  python/graphstorm/inference/ep_infer.py
  python/graphstorm/inference/graphstorm_infer.py
  python/graphstorm/inference/lp_infer.py
  python/graphstorm/inference/np_infer.py
  python/graphstorm/model/gnn_encoder_base.py
  python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
  python/graphstorm/run/gsgnn_ep/ep_infer_lm.py
  python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
  python/graphstorm/run/gsgnn_ep/gsgnn_lm_ep.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
  python/graphstorm/run/gsgnn_np/gsgnn_np.py
  python/graphstorm/run/gsgnn_np/np_infer_gnn.py
  python/graphstorm/trainer/ep_trainer.py
  python/graphstorm/trainer/glem_np_trainer.py
  python/graphstorm/trainer/gsgnn_trainer.py
  python/graphstorm/trainer/lp_trainer.py
  python/graphstorm/trainer/np_trainer.py
  python/graphstorm/utils.py
  tests/end2end-tests/custom-gnn/train.py
  tests/end2end-tests/graphstorm-ec/test-cpu.sh
  tests/end2end-tests/graphstorm-lp/test-cpu.sh
  tests/end2end-tests/graphstorm-nc/test-cpu.sh
  tests/unit-tests/test_dist_eval.py
  tests/unit-tests/test_utils.py
Labels: v0.1.2

#356 Change the location of input data and output data of sagemaker training/inference tasks to /tmp/
  python/graphstorm/sagemaker/sagemaker_infer.py
  python/graphstorm/sagemaker/sagemaker_train.py
  sagemaker/run/gconstruct_entry.py
  sagemaker/run/infer_entry.py
  sagemaker/run/train_entry.py
Labels: v0.1.2
