Repository awslabs/graphstorm, pull requests merged in 2024-06, with the labels that each got.

#864 Relax the train/val/test mask check for multi-task learning
  python/graphstorm/gconstruct/construct_graph.py
  python/graphstorm/gconstruct/transform.py
Labels: 0.3, ready

#863 [Multi-task learning] Support reconstruct node feature supervision
  python/graphstorm/__init__.py
  python/graphstorm/config/__init__.py
  python/graphstorm/config/argument.py
  python/graphstorm/config/config.py
  python/graphstorm/eval/__init__.py
  python/graphstorm/eval/evaluator.py
  python/graphstorm/gsf.py
  python/graphstorm/model/gnn.py
  python/graphstorm/model/gnn_encoder_base.py
  python/graphstorm/model/hgt_encoder.py
  python/graphstorm/model/multitask_gnn.py
  python/graphstorm/model/node_decoder.py
  python/graphstorm/model/rgat_encoder.py
  python/graphstorm/model/rgcn_encoder.py
  python/graphstorm/run/gsgnn_mt/gsgnn_mt.py
  python/graphstorm/trainer/mt_trainer.py
  tests/end2end-tests/graphstorm-mt/mgpu_test.sh
  tests/unit-tests/test_config.py
  tests/unit-tests/test_gnn.py
  tests/unit-tests/test_trainer.py
  training_scripts/gsgnn_mt/ml_nc_ec_er_lp.yaml
Labels: 0.3, ready

#860 Update gsgnn_node_emb for multi-task learning
  python/graphstorm/config/argument.py
  python/graphstorm/run/gsgnn_emb/gsgnn_node_emb.py
  python/graphstorm/run/gsgnn_mt/gsgnn_mt.py
  tests/end2end-tests/graphstorm-mt/mgpu_test.sh
Labels: 0.3, ready

#868 [Bug Fix] Fix the wholegraph version
  .github/workflow_scripts/e2e_mgpu_check.sh
Labels: ready

#857 [GSProcessing] Add structure for saving transformation JSON files.
  graphstorm-processing/graphstorm_processing/constants.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_feature_transformer.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/base_dist_transformation.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_category_transformation.py
  graphstorm-processing/graphstorm_processing/distributed_executor.py
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
  graphstorm-processing/graphstorm_processing/graph_loaders/heterogeneous_graphloader.py
  graphstorm-processing/graphstorm_processing/graph_loaders/loader_base.py
  graphstorm-processing/tests/conftest.py
  graphstorm-processing/tests/resources/small_heterogeneous_graph/gsprocessing-config.json
  graphstorm-processing/tests/resources/small_heterogeneous_graph/nodes/user.csv
  graphstorm-processing/tests/test_dist_category_transformation.py
  graphstorm-processing/tests/test_dist_executor.py
  graphstorm-processing/tests/test_dist_heterogenous_loader.py
Labels: 0.3, ready, gsprocessing

#872 Make IP config argument for distpart consistent with the rest of GSF
  python/graphstorm/gpartition/dist_partition_graph.py
Labels: 0.3, ready

#875 [Fix] Fix save_model_frequency None error in trainer
  python/graphstorm/trainer/ep_trainer.py
  python/graphstorm/trainer/lp_trainer.py
  python/graphstorm/trainer/np_trainer.py
Labels: bug, 0.3, ready

#871 Update multi-task evaluation logic to avoid information leakage issue in lp and nfeat reconstruct task evaluation.
  python/graphstorm/model/__init__.py
  python/graphstorm/model/multitask_gnn.py
  python/graphstorm/run/gsgnn_mt/gsgnn_mt.py
  python/graphstorm/trainer/mt_trainer.py
  tests/unit-tests/test_gnn.py
  tests/unit-tests/test_trainer.py
  tests/unit-tests/util.py
  training_scripts/gsgnn_mt/ml_nc_ec_er_lp.yaml
Labels: 0.3, ready

#876 [Doc] Update gconstruct configuration doc to clarify the usage of two boolean arguments
  docs/source/configuration/configuration-gconstruction.rst
Labels: documentation, 0.3, ready

#870 [GSProcessing] Add pre-computed categorical transformation loading
  docs/source/gs-processing/gs-processing-getting-started.rst
  docs/source/gs-processing/usage/example.rst
  graphstorm-processing/graphstorm_processing/data_transformations/dist_feature_transformer.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/base_dist_transformation.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_category_transformation.py
  graphstorm-processing/graphstorm_processing/distributed_executor.py
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
  graphstorm-processing/pyproject.toml
  graphstorm-processing/tests/resources/precomputed_transformations/user_state_categorical_transformation.json
  graphstorm-processing/tests/test_dist_category_transformation.py
  graphstorm-processing/tests/test_dist_executor.py
  graphstorm-processing/tests/test_dist_heterogenous_loader.py
Labels: 0.3, ready, gsprocessing

#861 Support multi-task inference.
  inference_scripts/mt_infer/README.md
  inference_scripts/mt_infer/ml_nc_ec_er_lp_only_infer.yaml
  inference_scripts/mt_infer/ml_nc_ec_er_lp_with_mask_infer.yaml
  python/graphstorm/__init__.py
  python/graphstorm/dataloading/dataset.py
  python/graphstorm/eval/evaluator.py
  python/graphstorm/gconstruct/remap_result.py
  python/graphstorm/gsf.py
  python/graphstorm/inference/__init__.py
  python/graphstorm/inference/mt_infer.py
  python/graphstorm/model/gnn.py
  python/graphstorm/run/gs_multi_task_learning.py
  python/graphstorm/run/gsgnn_mt/gsgnn_mt.py
  python/graphstorm/run/gsgnn_mt/mt_infer_gnn.py
  python/graphstorm/trainer/ep_trainer.py
  tests/end2end-tests/data_process/check_edge_predict_remap.py
  tests/end2end-tests/data_process/check_node_predict_remap.py
  tests/end2end-tests/data_process/gen_multi_task_remap_test.py
  tests/end2end-tests/data_process/test.sh
  tests/end2end-tests/graphstorm-mt/mgpu_test.sh
  tests/unit-tests/gconstruct/test_remap_result.py
  tests/unit-tests/test_inferrer.py
  tests/unit-tests/util.py
Labels: 0.3, ready

#877 Fix ParMETIS call so it uses all workers in cluster.
  python/graphstorm/gpartition/metis_partition.py
Labels: bug, 0.3, ready

#885 Update Readme to add a link to graphstorm paper
  README.md
Labels: documentation, 0.3

#886 [Doc] Fix the type error in example Notebook 2
  docs/source/notebooks/Notebook_2_LP_Pipeline.ipynb
Labels: documentation, 0.3, ready

#888 Reduce the number of warning prints of heterogeneous GNN encoders when some nodes do not have in edges
  python/graphstorm/model/hgt_encoder.py
  python/graphstorm/model/rgat_encoder.py
  python/graphstorm/model/rgcn_encoder.py
Labels: ready, 0.3.1

#887 [Documentation] Add doc for multi-task learning
  docs/source/advanced/multi-task-learning.rst
  docs/source/tutorials/own-data.rst
Labels: documentation, 0.3

#896 Add more information in the error message when the training set is empty or too small.
  python/graphstorm/dataloading/dataset.py
Labels: ready, 0.3.1

#880 [GPartition/SageMaker] Improvements to gpartition and SageMaker partition.
  python/graphstorm/gpartition/__init__.py
  python/graphstorm/gpartition/dist_partition_graph.py
  python/graphstorm/gpartition/random_partition.py
  python/graphstorm/sagemaker/sagemaker_partition.py
  tests/unit-tests/gpartition/conftest.py
  tests/unit-tests/gpartition/test_random_partition.py
Labels: ready, 0.3.1

#891 Print unknown arguments when executing GraphStorm command-lines.
  python/graphstorm/run/gsgnn_dt/distill_gnn.py
  python/graphstorm/run/gsgnn_emb/gsgnn_node_emb.py
  python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
  python/graphstorm/run/gsgnn_ep/ep_infer_lm.py
  python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
  python/graphstorm/run/gsgnn_ep/gsgnn_lm_ep.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
  python/graphstorm/run/gsgnn_mt/gsgnn_mt.py
  python/graphstorm/run/gsgnn_mt/mt_infer_gnn.py
  python/graphstorm/run/gsgnn_np/gsgnn_np.py
  python/graphstorm/run/gsgnn_np/np_infer_gnn.py
Labels: ready, 0.3.1

#869 [Bugfix] Fix WholeGraph import issue
  python/graphstorm/wholegraph/utils.py
Labels: ready, 0.3.1

#903 [CI] Ci profiling on lp + multitask
  .github/workflow_scripts/e2e_mgpu_check.sh
  .github/workflow_scripts/e2e_mgpu_multitask_check.sh
Labels: ready

#901 Add some test for testing ID remapping after link prediction training
  python/graphstorm/gconstruct/remap_result.py
  tests/end2end-tests/check_infer.py
  tests/end2end-tests/create_data.sh
  tests/end2end-tests/data_gen/process_movielens.py
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
Labels: ready, 0.3.1

#893 [Fix] Modify model saving behavior and unify all check do evaluation behavior
  python/graphstorm/trainer/ep_trainer.py
  python/graphstorm/trainer/glem_np_trainer.py
  python/graphstorm/trainer/gsgnn_trainer.py
  python/graphstorm/trainer/lp_trainer.py
  python/graphstorm/trainer/mt_trainer.py
  python/graphstorm/trainer/np_trainer.py
  tests/end2end-tests/graphstorm-ec/mgpu_test.sh
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
  tests/end2end-tests/graphstorm-nc/mgpu_test.sh
Labels: enhancement, ready, 0.3.1
