Repository awslabs/graphstorm, pull requests merged in 2024-10, with the labels that each got.

#1049 [Doc] GraphStorm API example notebook 6 converting API examples to run with GraphStorm CLIs
  docs/source/api/notebooks/Notebook_6_API2CLI.ipynb
  docs/source/api/notebooks/demo_run_infer.py
  docs/source/api/notebooks/demo_run_train.py
  docs/source/api/notebooks/index.rst
  docs/source/cli/model-training-inference/single-machine-training-inference.rst
  examples/use_your_own_data/acm_nc.yaml
Labels: documentation, ready, 0.4

#1053 Fix version to conform to semver
  graphstorm-processing/docker/0.4.0/emr-serverless/Dockerfile.cpu
  graphstorm-processing/docker/0.4.0/emr/Dockerfile.cpu
  graphstorm-processing/docker/0.4.0/sagemaker/Dockerfile.cpu
  graphstorm-processing/pyproject.toml
  python/graphstorm/__init__.py
Labels: ready, 0.4

#1050 [GSProcessing] Fix to make graph_name optional again
  graphstorm-processing/graphstorm_processing/distributed_executor.py
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
  graphstorm-processing/tests/test_dist_executor.py
Labels: ready, 0.4

#1054 [Bugfix] Fix the case when the input value of wd_l2norm is using scientific notation.
  python/graphstorm/config/argument.py
  tests/unit-tests/test_config.py
Labels: ready, 0.4

#1055 [Documentation] Documentation for loss functions.
  docs/source/api/references/graphstorm.model.rst
  docs/source/api/references/index.rst
  python/graphstorm/model/__init__.py
  python/graphstorm/model/loss_func.py
Labels: documentation, ready, 0.4

#1039 [GSProcessing] PR2 - Custom Data Split for MT
  graphstorm-processing/graphstorm_processing/config/label_config_base.py
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
  graphstorm-processing/tests/test_dist_heterogenous_loader.py
Labels: ready

#1056 [Feature] Support edge feat reconstruct in multi-task learning.
  docs/source/_templates/configtemplate.rst
  inference_scripts/mt_infer/ml_lp_no_prediction.yaml
  inference_scripts/mt_infer/ml_nc_ec_er_lp_only_infer.yaml
  inference_scripts/mt_infer/ml_nc_ec_er_lp_with_mask_infer.yaml
  python/graphstorm/__init__.py
  python/graphstorm/config/__init__.py
  python/graphstorm/config/argument.py
  python/graphstorm/config/config.py
  python/graphstorm/gsf.py
  python/graphstorm/inference/mt_infer.py
  python/graphstorm/model/edge_decoder.py
  python/graphstorm/model/multitask_gnn.py
  python/graphstorm/run/gsgnn_mt/gsgnn_mt.py
  python/graphstorm/run/gsgnn_mt/mt_infer_gnn.py
  python/graphstorm/trainer/mt_trainer.py
  tests/end2end-tests/data_gen/movielens_multi_task.json
  tests/end2end-tests/data_gen/process_movielens.py
  tests/unit-tests/test_config.py
  tests/unit-tests/test_gnn.py
  tests/unit-tests/test_inferrer.py
  tests/unit-tests/test_trainer.py
  training_scripts/gsgnn_mt/ml_lp_rnf.yaml
  training_scripts/gsgnn_mt/ml_nc_ec_er_lp.yaml
Labels: ready, 0.4

#1057 [Feature] Add arguments for using edge feature
  python/graphstorm/config/argument.py
  python/graphstorm/config/config.py
  tests/unit-tests/test_config.py
Labels: enhancement, ready, 0.4

#1059 Add more tests for edge feature reconstruction.
  tests/end2end-tests/data_process/gen_multi_task_remap_test.py
  tests/end2end-tests/graphstorm-mt/mgpu_test.sh
  tests/unit-tests/test_trainer.py
Labels: ready, 0.4

#1064 [Bugfix] Fix CI pipeline error caused by merging #1059
  tests/end2end-tests/data_process/gen_multi_task_remap_test.py
Labels: bug, ready, 0.4

#1063 [Enhancement] Improve the error report in gconstruct when files do not exist.
  python/graphstorm/gconstruct/file_io.py
Labels: ready, 0.4

#1058 [Documentation] Update documents for edge feature reconstruction support.
  docs/source/advanced/multi-task-learning.rst
  docs/source/api/references/graphstorm.model.rst
  docs/source/cli/graph-construction/single-machine-gconstruct.rst
  inference_scripts/mt_infer/README.md
  training_scripts/gsgnn_mt/README.md
Labels: documentation, 0.4

#1066 Fix flaky `test_fp_min_max_transform` test.
  tests/unit-tests/gconstruct/test_transform.py
Labels: ready, 0.4

#1060 Add gsf.py to lint checks and fix linting errors in file.
  .github/workflow_scripts/lint_check.sh
  python/graphstorm/gsf.py
Labels: ready, 0.4

#1069 [Doc Fix] Update Docker Container setup in Doc
  docs/source/install/env-setup.rst
Labels: ready

#1062 [Config] Add an argument out_emb_size.
  python/graphstorm/config/argument.py
  python/graphstorm/gsf.py
  tests/unit-tests/test_config.py
  tests/unit-tests/test_gnn.py
Labels: ready, 0.4

#1071 [Enhancement] Add sort to filename wildcard extension for GConstruct
  python/graphstorm/gconstruct/file_io.py
Labels: ready

#1070 [Feature] Edge Feature Support on gsf.py and embed.py
  python/graphstorm/__init__.py
  python/graphstorm/dataloading/dataset.py
  python/graphstorm/gsf.py
  python/graphstorm/model/__init__.py
  python/graphstorm/model/embed.py
  python/graphstorm/model/gnn.py
  tests/unit-tests/data_utils.py
  tests/unit-tests/test_dataloading.py
  tests/unit-tests/test_embed.py
  tests/unit-tests/test_gsf.py
Labels: enhancement, ready, 0.4, API update

#1073 [GSProcessing] Replace colons in edge feature paths with underscores to ensure EFS compatibility.
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
Labels: ready, gsprocessing, 0.4

#1061 Add Adjusted Mean Ranking Index metric for Link Prediction
  .github/workflow_scripts/pytest_check.sh
  inference_scripts/mt_infer/ml_nc_ec_er_lp_only_infer.yaml
  inference_scripts/mt_infer/ml_nc_ec_er_lp_with_mask_infer.yaml
  python/graphstorm/eval/eval_func.py
  python/graphstorm/eval/evaluator.py
  python/graphstorm/gsf.py
  python/graphstorm/inference/graphstorm_infer.py
  python/graphstorm/inference/lp_infer.py
  python/graphstorm/inference/mt_infer.py
  python/graphstorm/model/edge_decoder.py
  python/graphstorm/model/lp_gnn.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/trainer/gsgnn_trainer.py
  python/graphstorm/trainer/lp_trainer.py
  python/graphstorm/trainer/mt_trainer.py
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
  tests/end2end-tests/graphstorm-mt/mgpu_test.sh
  tests/unit-tests/test_eval_func.py
  tests/unit-tests/test_inferrer.py
  tests/unit-tests/test_trainer.py
Labels: ready, 0.4, API update

#1079 Allow using multiple metrics when using early stop.
  python/graphstorm/eval/evaluator.py
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
Labels: bug, ready, 0.4

#1075 Add documentation for AMRI and other LP eval metrics
  docs/source/advanced/link-prediction.rst
  docs/source/cli/model-training-inference/configuration-run.rst
  python/graphstorm/eval/evaluator.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
Labels: documentation, ready, 0.4

#1074 [Feature] RGCN encoder to support edge feature
  python/graphstorm/config/__init__.py
  python/graphstorm/model/gnn_encoder_base.py
  python/graphstorm/model/rgcn_encoder.py
  tests/unit-tests/data_utils.py
  tests/unit-tests/test_nn_encoder.py
  tests/unit-tests/test_nn_model.py
Labels: enhancement, break back compatibility, ready, 0.4
