Repository awslabs/graphstorm, pull requests merged in 2024-03, with the labels that each got.

#758 add infer_batch_size to get a small batch size for LLM.
  python/graphstorm/inference/emb_infer.py
  python/graphstorm/inference/lp_infer.py
Labels: ready

#763 [Doc]Modify Document to reflect the changes in v0.2.2
  docs/source/advanced/own-models.rst
  docs/source/install/env-setup.rst
  docs/source/tutorials/own-data.rst
  docs/source/tutorials/quick-start.rst
Labels: documentation, 0.2.2

#764 Allow running of local partitioners on local clusters
  .github/workflow_scripts/lint_check.sh
  python/graphstorm/gpartition/__init__.py
  python/graphstorm/gpartition/dist_partition_graph.py
  python/graphstorm/gpartition/partition_algo_base.py
  python/graphstorm/gpartition/random_partition.py
  python/graphstorm/sagemaker/sagemaker_partition.py
  python/graphstorm/sagemaker/sm_partition_algorithm.py
  tests/unit-tests/gpartition/test_random_partition.py
Labels: 0.3, ready

#768 [Bug Fix] Fix vulnerability on Pyarrow and Transformer version
  graphstorm-processing/pyproject.toml
  setup.py
Labels: ready

#765 steps for running experiments on amazon review
  examples/paper_experiments/README.md
  examples/paper_experiments/construct_AR_items.py
  examples/paper_experiments/construct_AR_reviews.py
  examples/paper_experiments/gconstruct_configs/AR_construction_full.json
  examples/paper_experiments/training_configs/main_experiments/AR_lp_ft.yaml
  examples/paper_experiments/training_configs/main_experiments/AR_lp_gnn.yaml
  examples/paper_experiments/training_configs/main_experiments/AR_nc_ft.yaml
  examples/paper_experiments/training_configs/main_experiments/AR_nc_gnn.yaml
  examples/paper_experiments/training_configs/main_experiments/mag_lp_ft.yaml
  examples/paper_experiments/training_configs/main_experiments/mag_lp_gnn.yaml
  examples/paper_experiments/training_configs/main_experiments/mag_nc_ft.yaml
  examples/paper_experiments/training_configs/main_experiments/mag_nc_gnn.yaml
Labels: ready

#781 Update graphstorm.initialize.
  python/graphstorm/gsf.py
Labels: 0.3, ready

#739 [GSProcessing] Allow custom out_dtype in feature transformation
  docs/source/gs-processing/developer/input-configuration.rst
  graphstorm-processing/graphstorm_processing/config/config_conversion/gconstruct_converter.py
  graphstorm-processing/graphstorm_processing/config/feature_config_base.py
  graphstorm-processing/graphstorm_processing/config/numerical_configs.py
  graphstorm-processing/graphstorm_processing/constants.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_noop_transformation.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_numerical_transformation.py
  graphstorm-processing/tests/resources/small_heterogeneous_graph/gsprocessing-config.json
  graphstorm-processing/tests/test_converter.py
  graphstorm-processing/tests/test_dist_numerical_transformation.py
Labels: 0.3, ready, gsprocessing

#783 Move setup_device into gs.initialize()
  docs/source/advanced/own-models.rst
  docs/source/api/graphstorm.rst
  examples/customized_models/HGT/hgt_nc.py
  examples/peft_llm_gnn/main_lp.py
  examples/peft_llm_gnn/main_nc.py
  examples/temporal_graph_learning/main_nc.py
  python/graphstorm/gsf.py
  python/graphstorm/run/gsgnn_dt/distill_gnn.py
  python/graphstorm/run/gsgnn_emb/gsgnn_node_emb.py
  python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
  python/graphstorm/run/gsgnn_ep/ep_infer_lm.py
  python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
  python/graphstorm/run/gsgnn_ep/gsgnn_lm_ep.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
  python/graphstorm/run/gsgnn_np/gsgnn_np.py
  python/graphstorm/run/gsgnn_np/np_infer_gnn.py
  python/graphstorm/utils.py
  tests/end2end-tests/custom-gnn/train.py
Labels: 0.3, ready

#782 Change logic of setup device
  examples/customized_models/HGT/hgt_nc.py
  examples/peft_llm_gnn/main_lp.py
  examples/peft_llm_gnn/main_nc.py
  examples/standalone_mode_demo.ipynb
  examples/temporal_graph_learning/main_nc.py
  python/graphstorm/dataloading/dataloading.py
  python/graphstorm/dataloading/dataset.py
  python/graphstorm/dataloading/utils.py
  python/graphstorm/distiller/distiller.py
  python/graphstorm/inference/graphstorm_infer.py
  python/graphstorm/model/edge_decoder.py
  python/graphstorm/run/gsgnn_dt/distill_gnn.py
  python/graphstorm/run/gsgnn_emb/gsgnn_node_emb.py
  python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
  python/graphstorm/run/gsgnn_ep/ep_infer_lm.py
  python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
  python/graphstorm/run/gsgnn_ep/gsgnn_lm_ep.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
  python/graphstorm/run/gsgnn_np/gsgnn_np.py
  python/graphstorm/run/gsgnn_np/np_infer_gnn.py
  python/graphstorm/trainer/gsgnn_trainer.py
  python/graphstorm/trainer/np_trainer.py
  tests/end2end-tests/custom-gnn/train.py
  tests/unit-tests/data_utils.py
  tests/unit-tests/test_dataloading.py
  tests/unit-tests/test_gnn.py
Labels: 0.3, ready

#790 [Partition Image] Add dependency for gs partition
  docker/Dockerfile.local
  python/graphstorm/gpartition/dist_partition_graph.py
Labels: ready
