Repository awslabs/graphstorm, pull requests merged in 2024-11, with the labels that each got.

#1082 [Documentation] Add multi-task learning CLI notebook example
  docs/source/cli/notebooks/Notebook_4_MT_CLI.ipynb
  examples/use_your_own_data/acm_mt.yaml
Labels: documentation, 0.4

#1084 [Feature] Edge Feature Support in GNN and base models
  python/graphstorm/gsf.py
  python/graphstorm/model/edge_gnn.py
  python/graphstorm/model/embed.py
  python/graphstorm/model/gnn.py
  python/graphstorm/model/gnn_encoder_base.py
  python/graphstorm/model/lp_gnn.py
  python/graphstorm/model/node_gnn.py
  python/graphstorm/model/rgcn_encoder.py
  tests/unit-tests/test_embed.py
  tests/unit-tests/test_gnn.py
  tests/unit-tests/test_gsf.py
  tests/unit-tests/test_nn_encoder.py
Labels: enhancement, ready, 0.4

#1083 [SageMaker] [GraphBolt] Add support for launching GraphBolt jobs on SageMaker
  .github/workflow_scripts/pytest_check.sh
  .gitignore
  docker/push_gsf_container.sh
  docker/sagemaker/Dockerfile.sm
  docker/sagemaker/build_artifacts/start_with_right_hostname.sh
  docs/source/advanced/using-graphbolt.rst
  python/graphstorm/gpartition/convert_to_graphbolt.py
  python/graphstorm/sagemaker/sagemaker_partition.py
  python/graphstorm/sagemaker/utils.py
  sagemaker/launch/common_parser.py
  sagemaker/launch/launch_gconstruct.py
  sagemaker/launch/launch_graphbolt_convert.py
  sagemaker/launch/launch_infer.py
  sagemaker/launch/launch_train.py
  sagemaker/run/gb_convert_entry.py
  sagemaker/run/gconstruct_entry.py
  sagemaker/run/train_entry.py
  tests/sagemaker-tests/test_sagemaker_args.py
Labels: ready, 0.4, sagemaker

#1087 Add CLI Notebook examples in the doc
  docs/source/cli/notebooks/Notebook_CLI_MT.ipynb
  docs/source/cli/notebooks/index.rst
  docs/source/index.rst
Labels: documentation, 0.4

#1089 [Doc] gs_gen_node_embedding task command tutorial for SageMaker
  docs/source/cli/model-training-inference/distributed/sagemaker.rst
Labels: 0.4

#1090 Fix GConstruct file parsing when input is a list with a single wildcard path
  python/graphstorm/gconstruct/file_io.py
  tests/unit-tests/gconstruct/test_gconstruct_utils.py
Labels: bug, ready, 0.4

#1085 [GSProcessing] Add saving and re-applying for numerical transforms.
  docs/source/cli/graph-construction/distributed/example.rst
  graphstorm-processing/graphstorm_processing/data_transformations/dist_feature_transformer.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_bucket_numerical_transformation.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_numerical_transformation.py
  graphstorm-processing/tests/test_dist_executor.py
  graphstorm-processing/tests/test_dist_feature_transformer.py
  graphstorm-processing/tests/test_dist_numerical_transformation.py
Labels: ready, gsprocessing, 0.4

#1091 [GSProcessing] Fix parsing of file paths that start with "./"
  graphstorm-processing/graphstorm_processing/config/data_config_base.py
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
  graphstorm-processing/tests/resources/small_heterogeneous_graph/gsprocessing-config.json
Labels: ready, gsprocessing, 0.4

#1092 [Bugfix] Fix the bug when _get_sparse_emb_range return a start larger than num-of-embs
  python/graphstorm/model/utils.py
  tests/unit-tests/test_model_save_load.py
Labels: bug, ready, 0.4

#1080 [GSProcessing&GSPartition] Support Hard Negative
  docs/source/advanced/link-prediction.rst
  docs/source/cli/graph-construction/distributed/gsprocessing/input-configuration.rst
  graphstorm-processing/graphstorm_processing/config/config_conversion/gconstruct_converter.py
  graphstorm-processing/graphstorm_processing/config/config_parser.py
  graphstorm-processing/graphstorm_processing/config/hard_negative_configs.py
  graphstorm-processing/graphstorm_processing/constants.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_feature_transformer.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/__init__.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_hard_negative_transformation.py
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
  graphstorm-processing/tests/test_converter.py
  graphstorm-processing/tests/test_dist_hard_negative_transformation.py
  python/graphstorm/gconstruct/utils.py
  python/graphstorm/gpartition/__init__.py
  python/graphstorm/gpartition/dist_partition_graph.py
  python/graphstorm/gpartition/post_hard_negative.py
  python/graphstorm/model/utils.py
  tests/unit-tests/gpartition/config/gsprocessing_hard_negative_config.json
  tests/unit-tests/gpartition/config/gsprocessing_non_hard_negative_config.json
  tests/unit-tests/gpartition/test_hard_negative_post_partition.py
Labels: ready

#1088 [Feature] Edge Feature Support in Trainer and Inferrer Pipeline
  python/graphstorm/gsf.py
  python/graphstorm/model/gnn.py
  python/graphstorm/model/node_gnn.py
  python/graphstorm/model/rgcn_encoder.py
  python/graphstorm/trainer/ep_trainer.py
  python/graphstorm/trainer/lp_trainer.py
  python/graphstorm/trainer/np_trainer.py
  tests/unit-tests/test_inferrer.py
  tests/unit-tests/test_trainer.py
Labels: enhancement, ready, 0.4

#1096 [Feature] Run config for using edge features
  examples/acm_data.py
  python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
  python/graphstorm/run/gsgnn_ep/ep_infer_lm.py
  python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
  python/graphstorm/run/gsgnn_ep/gsgnn_lm_ep.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
  python/graphstorm/run/gsgnn_np/gsgnn_np.py
  python/graphstorm/run/gsgnn_np/np_infer_gnn.py
  tests/end2end-tests/create_data.sh
  tests/end2end-tests/data_gen/movielens_ef_er.json
  tests/end2end-tests/data_gen/movielens_ef_lp.json
  tests/end2end-tests/data_gen/movielens_ef_nc_ec.json
  tests/end2end-tests/graphstorm-ec/mgpu_test.sh
  tests/end2end-tests/graphstorm-er/test.sh
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
  tests/end2end-tests/graphstorm-nc/mgpu_test.sh
Labels: enhancement, ready, 0.4

#1100 Add unit tests for load_sparse_emb and save_sparse_emb
  tests/unit-tests/test_model_save_load.py
Labels: bug, ready, 0.4
