Repository awslabs/graphstorm, pull requests merged in 2024-09, with the labels that each got.

#998 [Doc] Add back GSProcessing EMR EC2 document for spark-submit
  docs/source/advanced/gsprocessing-emr-ec2.rst
  docs/source/cli/graph-construction/distributed/gsprocessing/aws-infra/emr.rst
  docs/source/index.rst
Labels: ready

#1000 [Doc] Fix Notebooks' typos
  docs/source/api/notebooks/Notebook_1_NC_Pipeline.ipynb
  docs/source/api/notebooks/Notebook_2_LP_Pipeline.ipynb
  docs/source/api/notebooks/Notebook_3_Model_Variants.ipynb
  docs/source/api/notebooks/Notebook_4_Customized_Models.ipynb
Labels: documentation, ready, 0.4

#1005 [CI] Remove hard-coded bert model cache
  tests/end2end-tests/data_process/data_gen.py
Labels: ready

#1002 Move minimum Python version to 3.8 for GraphStorm
  README.md
  docs/source/install/env-setup.rst
  setup.py
Labels: ready, 0.4

#1001 Support for launching jobs with GraphBolt enabled (GraphBolt support PR1)
  docs/source/cli/model-training-inference/configuration-run.rst
  python/graphstorm/config/argument.py
  python/graphstorm/gsf.py
  python/graphstorm/run/gsgnn_dt/distill_gnn.py
  python/graphstorm/run/gsgnn_emb/gsgnn_node_emb.py
  python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
  python/graphstorm/run/gsgnn_ep/ep_infer_lm.py
  python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
  python/graphstorm/run/gsgnn_ep/gsgnn_lm_ep.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
  python/graphstorm/run/gsgnn_mt/gsgnn_mt.py
  python/graphstorm/run/gsgnn_mt/mt_infer_gnn.py
  python/graphstorm/run/gsgnn_np/gsgnn_np.py
  python/graphstorm/run/gsgnn_np/np_infer_gnn.py
Labels: ready, 0.4

#1012 [Doc] Reformat equations in doc.
  docs/source/advanced/link-prediction.rst
Labels: documentation, ready, 0.4

#995 Add adversarial negative option to cross-entropy loss for link prediction tasks
  docs/source/advanced/link-prediction.rst
  docs/source/cli/model-training-inference/configuration-run.rst
  examples/paper_experiments/README.md
  examples/paper_experiments/training_configs/link_prediction/lp_also_buy_1_layer_rgcn_dot_adversarial_entropy_loss_joint_32_negative.yaml
  python/graphstorm/config/argument.py
  python/graphstorm/gsf.py
  python/graphstorm/model/loss_func.py
  tests/end2end-tests/graphstorm-lp/test.sh
  tests/unit-tests/test_config.py
  tests/unit-tests/test_loss.py
Labels: ready, 0.4

#1013 [CI] Add another workflow for GraphBolt
  .github/workflow_scripts/e2e_gb_check.sh
  .github/workflows/continuous-integration.yml
  submitJob.py
Labels: ready

#1015 [Bugfix] Excluding valid/test edges during link prediction training in multi-task learning setting
  python/graphstorm/dataloading/dataloading.py
  python/graphstorm/run/gsgnn_mt/gsgnn_mt.py
Labels: bug, ready, 0.4

#1020 [Version] Update main repo version to V0.4
  graphstorm-processing/docker/0.4/emr-serverless/Dockerfile.cpu
  graphstorm-processing/docker/0.4/emr/Dockerfile.cpu
  graphstorm-processing/docker/0.4/sagemaker/Dockerfile.cpu
  graphstorm-processing/pyproject.toml
  python/graphstorm/__init__.py
Labels: ready

#1021 [Enhancement] Add a `super-node` graph prediction example
  examples/graph_prediction/README.md
  examples/graph_prediction/dummy_supernode_data.py
  examples/graph_prediction/gen_ogbg_supernode.py
  examples/graph_prediction/supernode_gc.yaml
Labels: enhancement, ready, 0.4

#999 [New Feature] Add Focal loss for imbalanced binary classification tasks.
  docs/source/cli/model-training-inference/configuration-run.rst
  python/graphstorm/config/__init__.py
  python/graphstorm/config/argument.py
  python/graphstorm/config/config.py
  python/graphstorm/eval/eval_func.py
  python/graphstorm/gsf.py
  python/graphstorm/model/edge_decoder.py
  python/graphstorm/model/loss_func.py
  python/graphstorm/model/node_decoder.py
  tests/end2end-tests/graphstorm-ec/test.sh
  tests/end2end-tests/graphstorm-nc/test.sh
  tests/unit-tests/test_config.py
  tests/unit-tests/test_eval_func.py
  tests/unit-tests/test_gsf.py
  tests/unit-tests/test_loss.py
Labels: ready, 0.4

#1019 [CI Fix] Test fix for node/edge remapping
  tests/end2end-tests/data_process/test.sh
Labels: ready

#1022 [Bugfix] Fix the bug when the first fanout of the fanout list is -1
  python/graphstorm/config/argument.py
  tests/unit-tests/test_config.py
Labels: bug, ready, 0.4

#1011 [GraphBolt] Add GraphBolt graph construction for GConstruct and GPartition (GraphBolt PR2)
  .github/workflow_scripts/e2e_check.sh
  .github/workflow_scripts/e2e_gb_check.sh
  docs/source/cli/graph-construction/distributed/gspartition/ec2-clusters.rst
  docs/source/cli/graph-construction/single-machine-gconstruct.rst
  python/graphstorm/gconstruct/construct_graph.py
  python/graphstorm/gconstruct/utils.py
  python/graphstorm/gpartition/dist_partition_graph.py
  python/graphstorm/gsf.py
  python/graphstorm/run/launch.py
  setup.py
  tests/end2end-tests/create_data.sh
  tests/end2end-tests/data_gen/process_movielens.py
  tests/end2end-tests/data_process/gpartition_test.sh
  tests/end2end-tests/data_process/movielens_test.sh
  tests/end2end-tests/graphbolt-gs-integration/graphbolt-graph-construction.sh
Labels: ready, 0.4

#1026 [Doc] API Notebook example for Graph Prediction Solution
  docs/source/api/notebooks/Notebook_5_GP_solution.ipynb
  docs/source/api/notebooks/index.rst
  examples/standalone_mode_demo.ipynb
  tutorial/GP_data_conversion.png
  tutorial/GP_layer_agg.png
  tutorial/GP_readout.png
  tutorial/GP_supernode.png
Labels: documentation, ready, 0.4

#1024 Add entry point for standalone GraphBolt conversion.
  python/graphstorm/gconstruct/utils.py
  python/graphstorm/gpartition/convert_to_graphbolt.py
  python/graphstorm/gpartition/dist_partition_graph.py
  tests/end2end-tests/graphbolt-gs-integration/graphbolt-graph-construction.sh
Labels: ready, 0.4

#1025 [GraphBolt] Add example for using GraphBolt
  docs/source/advanced/using-graphbolt.rst
  docs/source/cli/graph-construction/distributed/gspartition/ec2-clusters.rst
  docs/source/cli/graph-construction/single-machine-gconstruct.rst
  docs/source/cli/model-training-inference/configuration-run.rst
  docs/source/index.rst
  docs/source/tutorials/own-data.rst
Labels: documentation, 0.4

#1028 [Doc] Refactor configuration doc and release config.get_argument_parser API
  docs/source/api/references/graphstorm.config.rst
  docs/source/api/references/index.rst
  docs/source/cli/model-training-inference/configuration-run.rst
  python/graphstorm/config/argument.py
Labels: documentation, ready, 0.4

#1032 Add debug print in loss functions for link prediction debugging
  python/graphstorm/model/loss_func.py
  tests/end2end-tests/graphstorm-lp/test.sh
Labels: ready, 0.4

#994 [GSProcessing] Initial support for multi-task mask generation
  docs/source/advanced/multi-task-learning.rst
  docs/source/cli/graph-construction/distributed/gsprocessing/input-configuration.rst
  graphstorm-processing/graphstorm_processing/config/config_conversion/gconstruct_converter.py
  graphstorm-processing/graphstorm_processing/config/label_config_base.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_label_loader.py
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
  graphstorm-processing/graphstorm_processing/repartition_files.py
  graphstorm-processing/tests/resources/repartitioning/partitioned_metadata.json
  graphstorm-processing/tests/test_converter.py
  graphstorm-processing/tests/test_dist_heterogenous_loader.py
  graphstorm-processing/tests/test_dist_label_loader.py
  graphstorm-processing/tests/test_repartition_files.py
Labels: ready, gsprocessing, 0.4

#1034 [Bugfix] Link prediction contrastive loss does not work with edge weight for lp loss
  python/graphstorm/config/argument.py
  tests/unit-tests/test_config.py
Labels: bug, ready, 0.4

#1030 [Bug Fix] Fix Backward Compatibility Problem for DGL 2.0.0+
  python/graphstorm/dataloading/dataloading.py
  python/graphstorm/model/node_gnn.py
  tests/end2end-tests/custom-gnn/train.py
  tests/end2end-tests/graphstorm-ec/test.sh
  tests/end2end-tests/graphstorm-lp/test.sh
  tests/end2end-tests/graphstorm-nc/test.sh
  tests/unit-tests/test_gnn.py
Labels: ready

#1036 [Doc] Release graphstorm.config GSConfig api
  docs/source/_templates/configtemplate.rst
  docs/source/api/references/graphstorm.config.rst
  docs/source/cli/model-training-inference/configuration-run.rst
  python/graphstorm/config/argument.py
  tests/unit-tests/test_config.py
Labels: documentation, ready, 0.4

#1031 [New Feature] Add support of TransE for link prediction.
  python/graphstorm/config/__init__.py
  python/graphstorm/config/argument.py
  python/graphstorm/config/config.py
  python/graphstorm/eval/utils.py
  python/graphstorm/gsf.py
  python/graphstorm/model/__init__.py
  python/graphstorm/model/edge_decoder.py
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
  tests/end2end-tests/graphstorm-lp/test.sh
  tests/unit-tests/test_config.py
  tests/unit-tests/test_decoder.py
Labels: ready, 0.4

#1042 [Doc] Add docs for TransE.
  docs/source/advanced/link-prediction.rst
  docs/source/api/references/graphstorm.model.rst
  docs/source/cli/model-training-inference/configuration-run.rst
  python/graphstorm/config/argument.py
Labels: documentation, ready, 0.4

#1029 [GraphBolt] Add integration tests for LP and NC training and inference.
  .github/workflow_scripts/e2e_gb_check.sh
  tests/end2end-tests/graphbolt-gs-integration/graphbolt-graph-construction.sh
  tests/end2end-tests/graphbolt-gs-integration/graphbolt-training-inference.sh
Labels: ready, 0.4

#1045 [GSProcessing Docker] Update push script for GSProcessing Docker Image
  graphstorm-processing/docker/push_gsprocessing_image.sh
Labels: ready

#1043 [New Feature] New evaluator to support MRR and Hits metrics simultaneously for link prediction.
  python/graphstorm/__init__.py
  python/graphstorm/eval/__init__.py
  python/graphstorm/eval/eval_func.py
  python/graphstorm/eval/evaluator.py
  python/graphstorm/gsf.py
  python/graphstorm/inference/lp_infer.py
  python/graphstorm/model/edge_decoder.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
  tests/unit-tests/test_evaluator.py
Labels: ready, 0.4

#1044 [Enhancement] Add a strict naming rule for graph names
  docs/source/cli/graph-construction/single-machine-gconstruct.rst
  docs/source/cli/model-training-inference/distributed/sagemaker.rst
  graphstorm-processing/graphstorm_processing/distributed_executor.py
  python/graphstorm/gconstruct/construct_graph.py
  python/graphstorm/utils.py
  tests/unit-tests/test_gsf.py
Labels: enhancement, ready, 0.4

#1046 [Doc] Add annotations for RotatE and TransE.
  python/graphstorm/model/edge_decoder.py
Labels: documentation, 0.4
