Repository awslabs/graphstorm, pull requests merged in 2024-12, with the labels that each got.

#1098 [Feature] Add Edge Feature as Inputs for Message Passing Computation
  examples/acm_data.py
  python/graphstorm/__init__.py
  python/graphstorm/config/__init__.py
  python/graphstorm/dataloading/dataset.py
  python/graphstorm/gsf.py
  python/graphstorm/model/__init__.py
  python/graphstorm/model/edge_gnn.py
  python/graphstorm/model/embed.py
  python/graphstorm/model/gnn.py
  python/graphstorm/model/gnn_encoder_base.py
  python/graphstorm/model/lp_gnn.py
  python/graphstorm/model/node_gnn.py
  python/graphstorm/model/rgcn_encoder.py
  python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
  python/graphstorm/run/gsgnn_ep/ep_infer_lm.py
  python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
  python/graphstorm/run/gsgnn_ep/gsgnn_lm_ep.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
  python/graphstorm/run/gsgnn_np/gsgnn_np.py
  python/graphstorm/run/gsgnn_np/np_infer_gnn.py
  python/graphstorm/trainer/ep_trainer.py
  python/graphstorm/trainer/lp_trainer.py
  python/graphstorm/trainer/np_trainer.py
  tests/end2end-tests/create_data.sh
  tests/end2end-tests/data_gen/movielens_ef_er.json
  tests/end2end-tests/data_gen/movielens_ef_lp.json
  tests/end2end-tests/data_gen/movielens_ef_nc_ec.json
  tests/end2end-tests/graphstorm-ec/mgpu_test.sh
  tests/end2end-tests/graphstorm-er/test.sh
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
  tests/end2end-tests/graphstorm-nc/mgpu_test.sh
  tests/unit-tests/data_utils.py
  tests/unit-tests/test_dataloading.py
  tests/unit-tests/test_embed.py
  tests/unit-tests/test_gnn.py
  tests/unit-tests/test_gsf.py
  tests/unit-tests/test_inferrer.py
  tests/unit-tests/test_nn_encoder.py
  tests/unit-tests/test_nn_model.py
  tests/unit-tests/test_trainer.py
Labels: enhancement, ready, 0.4

#1106 [Example] Fix ACM data JSON content inconsistency
  docs/source/tutorials/own-data.rst
  examples/acm_data.py
  tutorial/ACM_raw_parquet.png
Labels: bug, ready, 0.4

#1105 [Fix] Fix issue #1052
  docs/source/cli/model-training-inference/configuration-run.rst
  docs/source/tutorials/quick-start.rst
Labels: enhancement, ready, 0.4

#1104 [Doc] Add edge feature configurations doc
  docs/source/cli/model-training-inference/configuration-run.rst
Labels: documentation, ready, 0.4

#1101 Add standard transform for gconstruct
  docs/source/cli/graph-construction/single-machine-gconstruct.rst
  python/graphstorm/gconstruct/transform.py
  tests/end2end-tests/data_process/data_gen.py
  tests/end2end-tests/data_process/test_data.py
  tests/unit-tests/gconstruct/test_construct_graph.py
  tests/unit-tests/gconstruct/test_transform.py
Labels: ready, 0.4

#1110 [Document] Handle Issue #1027
  docs/source/advanced/language-models.rst
  docs/source/tutorials/own-data.rst
  docs/source/tutorials/quick-start.rst
Labels: documentation, ready, 0.4

#1112 Fix for error introduced by DGL's dependencies for Docker images
  docker/local/Dockerfile.local
  docker/parmetis/Dockerfile.parmetis
  docker/sagemaker/Dockerfile.sm
Labels: bug, dependencies, 0.4

#1109 [Example] Using GraphStorm API for Synthetic Air Transportation Network Prediciton
  examples/network_traffic_prediction/AirTrafficPrediction.ipynb
  examples/network_traffic_prediction/Air_Traffic_Data_Exp&Gc.ipynb
  examples/network_traffic_prediction/README.md
  examples/network_traffic_prediction/Synthetic_Airport_Traffic_wAirlines.ipynb
  examples/network_traffic_prediction/config.json
  examples/network_traffic_prediction/nr_models.py
  examples/network_traffic_prediction/world_airlines.png
Labels: documentation, ready, 0.4

#1103 Add build scripts for single-command build and push for local and sagemaker GS images
  docker/build_graphstorm_image.sh
  docker/parmetis/Dockerfile.parmetis
  docker/push_graphstorm_image.sh
  docker/sagemaker/Dockerfile.sm
  docs/source/cli/model-training-inference/distributed/sagemaker.rst
  docs/source/install/env-setup.rst
Labels: documentation, 0.4, API update, sagemaker

#1114 [Bug] Fix Notebook JSON Format Error in AirTrans Example
  examples/network_traffic_prediction/Synthetic_Airport_Traffic_wAirlines.ipynb
Labels: bug, ready, 0.4

#1113 [GSPartition] Adjust Process timeout
  docs/source/cli/graph-construction/distributed/gspartition/ec2-clusters.rst
  python/graphstorm/gpartition/dist_partition_graph.py
  tests/end2end-tests/graphbolt-gs-integration/graphbolt-graph-construction.sh
Labels: ready, 0.4

#1116 [SageMaker] Add SageMaker GraphBolt internal implementation
  python/graphstorm/sagemaker/sagemaker_gb_convert.py
Labels: ready, 0.4, sagemaker
