Repository awslabs/graphstorm, pull requests merged in 2024-08, with the labels that each got.

#937 [GSProcessing] Supplement for GConstruct Config Check for GSProcessing
  graphstorm-processing/graphstorm_processing/config/config_conversion/gconstruct_converter.py
  graphstorm-processing/tests/test_converter.py
Labels: ready

#951 [Bug] Report child process running errors in gconstruct
  python/graphstorm/gconstruct/utils.py
Labels: bug, ready, 0.3.1

#944 [GSProcessing] Add default argument values for optional numerical transformation kwargs
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_numerical_transformation.py
  graphstorm-processing/tests/test_dist_numerical_transformation.py
Labels: ready, gsprocessing, 0.3.1

#941 [Doc] API doc string refactor for graphstorm.eval
  docs/source/_templates/evaltemplate.rst
  docs/source/api/references/graphstorm.eval.rst
  docs/source/api/references/graphstorm.rst
  docs/source/configuration/configuration-run.rst
  python/graphstorm/eval/__init__.py
  python/graphstorm/eval/evaluator.py
  python/graphstorm/gsf.py
Labels: documentation, ready, 0.3.1

#938 [Bugfix] Fix the case when there is no prediction task defined in multitask learning inference.
  inference_scripts/mt_infer/ml_lp_no_prediction.yaml
  python/graphstorm/inference/mt_infer.py
  tests/end2end-tests/graphstorm-mt/mgpu_test.sh
  training_scripts/gsgnn_mt/ml_lp_rnf.yaml
Labels: ready, 0.3.1

#950 [Doc] API doc string refactor for graphstorm.model
  docs/source/_templates/modeltemplate.rst
  docs/source/api/references/graphstorm.model.rst
  python/graphstorm/dataloading/dataloading.py
  python/graphstorm/dataloading/sampler.py
  python/graphstorm/model/__init__.py
  python/graphstorm/model/edge_decoder.py
  python/graphstorm/model/edge_gnn.py
  python/graphstorm/model/embed.py
  python/graphstorm/model/gat_encoder.py
  python/graphstorm/model/gatv2_encoder.py
  python/graphstorm/model/gnn.py
  python/graphstorm/model/gnn_with_reconstruct.py
  python/graphstorm/model/hgt_encoder.py
  python/graphstorm/model/lm_embed.py
  python/graphstorm/model/lm_model/hf_bert.py
  python/graphstorm/model/lm_model/lm_model.py
  python/graphstorm/model/lm_model/utils.py
  python/graphstorm/model/lp_gnn.py
  python/graphstorm/model/node_decoder.py
  python/graphstorm/model/node_gnn.py
  python/graphstorm/model/rgat_encoder.py
  python/graphstorm/model/rgcn_encoder.py
  python/graphstorm/model/sage_encoder.py
  tests/unit-tests/test_gnn.py
Labels: documentation, ready, 0.3.1

#948 [New feature] Support hit@k for link prediction
  docs/source/api/references/graphstorm.eval.rst
  docs/source/configuration/configuration-run.rst
  inference_scripts/lp_infer/ml_lp_none_train_etype_infer.yaml
  python/graphstorm/config/argument.py
  python/graphstorm/eval/__init__.py
  python/graphstorm/eval/eval_func.py
  python/graphstorm/eval/evaluator.py
  python/graphstorm/inference/lp_infer.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
  python/graphstorm/trainer/lp_trainer.py
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
  tests/unit-tests/test_eval_func.py
  tests/unit-tests/test_evaluator.py
Labels: enhancement, ready, 0.3.1

#952 [Doc] API doc string refactor for graphstorm.trainer/inferrer
  docs/source/_templates/inferencetemplate.rst
  docs/source/_templates/trainertemplate.rst
  docs/source/api/references/graphstorm.inference.rst
  docs/source/api/references/graphstorm.trainer.rst
  docs/source/api/references/index.rst
  python/graphstorm/inference/emb_infer.py
  python/graphstorm/inference/ep_infer.py
  python/graphstorm/inference/graphstorm_infer.py
  python/graphstorm/inference/lp_infer.py
  python/graphstorm/inference/np_infer.py
  python/graphstorm/model/node_glem.py
  python/graphstorm/trainer/ep_trainer.py
  python/graphstorm/trainer/glem_np_trainer.py
  python/graphstorm/trainer/lp_trainer.py
  python/graphstorm/trainer/np_trainer.py
Labels: documentation, ready, 0.3.1

#956 [Doc] Reorg doc structure
  docs/source/cli/graph-construction/distributed/example.rst
  docs/source/cli/graph-construction/distributed/gspartition/ec2-clusters.rst
  docs/source/cli/graph-construction/distributed/gspartition/index.rst
  docs/source/cli/graph-construction/distributed/gspartition/sagemaker.rst
  docs/source/cli/graph-construction/distributed/gsprocessing/aws-infra/amazon-sagemaker.rst
  docs/source/cli/graph-construction/distributed/gsprocessing/aws-infra/emr-serverless.rst
  docs/source/cli/graph-construction/distributed/gsprocessing/aws-infra/emr.rst
  docs/source/cli/graph-construction/distributed/gsprocessing/aws-infra/index.rst
  docs/source/cli/graph-construction/distributed/gsprocessing/aws-infra/row-count-alignment.rst
  docs/source/cli/graph-construction/distributed/gsprocessing/developer-guide.rst
  docs/source/cli/graph-construction/distributed/gsprocessing/distributed-processing-setup.rst
  docs/source/cli/graph-construction/distributed/gsprocessing/gs-processing-getting-started.rst
  docs/source/cli/graph-construction/distributed/gsprocessing/index.rst
  docs/source/cli/graph-construction/distributed/gsprocessing/input-configuration.rst
  docs/source/cli/graph-construction/distributed/index.rst
  docs/source/cli/graph-construction/index.rst
  docs/source/cli/graph-construction/single-machine-gconstruct.rst
  docs/source/cli/model-training-inference/distributed/cluster.rst
  docs/source/cli/model-training-inference/distributed/sagemaker.rst
  docs/source/cli/model-training-inference/index.rst
  docs/source/cli/model-training-inference/output-remapping.rst
  docs/source/cli/model-training-inference/single-machine-training-inference.rst
  docs/source/configuration/configuration-partition.rst
  docs/source/configuration/index.rst
  docs/source/graph-construction/gs-processing/aws-infra/index.rst
  docs/source/graph-construction/gs-processing/gspartition/index.rst
  docs/source/graph-construction/gs-processing/index.rst
  docs/source/graph-construction/gs-processing/prerequisites/index.rst
  docs/source/graph-construction/index.rst
  docs/source/index.rst
Labels: documentation, ready, 0.3.1

#955 [GSProcessing] Fix isinstance check for numerical features
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
Labels: bug, ready, gsprocessing, 0.3.1

#965 Merge main to V0.3.1_doc_dev
  docs/source/_templates/inferencetemplate.rst
  docs/source/_templates/modeltemplate.rst
  docs/source/_templates/trainertemplate.rst
  docs/source/api/references/graphstorm.eval.rst
  docs/source/api/references/graphstorm.inference.rst
  docs/source/api/references/graphstorm.model.rst
  docs/source/api/references/graphstorm.trainer.rst
  docs/source/api/references/index.rst
  docs/source/configuration/configuration-run.rst
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
  inference_scripts/lp_infer/ml_lp_none_train_etype_infer.yaml
  python/graphstorm/config/argument.py
  python/graphstorm/dataloading/dataloading.py
  python/graphstorm/dataloading/sampler.py
  python/graphstorm/eval/__init__.py
  python/graphstorm/eval/eval_func.py
  python/graphstorm/eval/evaluator.py
  python/graphstorm/inference/emb_infer.py
  python/graphstorm/inference/ep_infer.py
  python/graphstorm/inference/graphstorm_infer.py
  python/graphstorm/inference/lp_infer.py
  python/graphstorm/inference/np_infer.py
  python/graphstorm/model/__init__.py
  python/graphstorm/model/edge_decoder.py
  python/graphstorm/model/edge_gnn.py
  python/graphstorm/model/embed.py
  python/graphstorm/model/gat_encoder.py
  python/graphstorm/model/gatv2_encoder.py
  python/graphstorm/model/gnn.py
  python/graphstorm/model/gnn_with_reconstruct.py
  python/graphstorm/model/hgt_encoder.py
  python/graphstorm/model/lm_embed.py
  python/graphstorm/model/lm_model/hf_bert.py
  python/graphstorm/model/lm_model/lm_model.py
  python/graphstorm/model/lm_model/utils.py
  python/graphstorm/model/lp_gnn.py
  python/graphstorm/model/node_decoder.py
  python/graphstorm/model/node_glem.py
  python/graphstorm/model/node_gnn.py
  python/graphstorm/model/rgat_encoder.py
  python/graphstorm/model/rgcn_encoder.py
  python/graphstorm/model/sage_encoder.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
  python/graphstorm/trainer/ep_trainer.py
  python/graphstorm/trainer/glem_np_trainer.py
  python/graphstorm/trainer/lp_trainer.py
  python/graphstorm/trainer/np_trainer.py
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
  tests/unit-tests/test_eval_func.py
  tests/unit-tests/test_evaluator.py
  tests/unit-tests/test_gnn.py
Labels: documentation, 0.3.1

#940 Update doc for hard negative
  docs/source/advanced/link-prediction.rst
Labels: documentation, 0.3.1

#967 [Bugfix] Fix --return-proba argument
  python/graphstorm/config/argument.py
Labels: ready, 0.3.1

#964 [Doc] Update doc of training and inference output.
  docs/source/advanced/multi-task-learning.rst
  docs/source/cli/model-training-inference/index.rst
  docs/source/cli/model-training-inference/output.rst
Labels: documentation, 0.3.1

#969 [Doc] V0.3.1 doc refactor of Single Machine Model Training and Inference
  README.md
  docs/source/cli/model-training-inference/configuration-run.rst
  docs/source/cli/model-training-inference/distributed/cluster.rst
  docs/source/cli/model-training-inference/index.rst
  docs/source/cli/model-training-inference/single-machine-training-inference.rst
  docs/source/configuration/index.rst
  docs/source/index.rst
Labels: documentation, ready, 0.3.1

#968 Fix the bug when the number of val/test samples is small
  python/graphstorm/dataloading/dataset.py
  python/graphstorm/model/multitask_gnn.py
  tests/end2end-tests/create_data.sh
  tests/end2end-tests/data_gen/movielens_small_val.json
  tests/end2end-tests/graphstorm-ec/mgpu_test.sh
  tests/end2end-tests/graphstorm-nc/mgpu_test.sh
  tests/unit-tests/data_utils.py
  tests/unit-tests/test_dataloading.py
Labels: bug, ready, 0.3.1

#966 [Doc] V0.3.1 doc refactor for single machine graph construction
  docs/source/cli/graph-construction/index.rst
  docs/source/cli/graph-construction/raw_data.rst
  docs/source/cli/graph-construction/single-machine-gconstruct.rst
  docs/source/cli/model-training-inference/configuration-run.rst
  docs/source/index.rst
  docs/source/tutorials/own-data.rst
Labels: documentation, ready, 0.3.1

#970 [Doc] Doc for Node ID remapping.
  docs/source/cli/model-training-inference/output-remapping.rst
  docs/source/cli/model-training-inference/output.rst
Labels: documentation, 0.3.1

#973 [Doc] V0.3.1 Documentation and Tutorial update
  README.md
  docs/source/advanced/link-prediction.rst
  docs/source/advanced/multi-task-learning.rst
  docs/source/cli/graph-construction/distributed/example.rst
  docs/source/cli/graph-construction/distributed/gspartition/ec2-clusters.rst
  docs/source/cli/graph-construction/distributed/gspartition/index.rst
  docs/source/cli/graph-construction/distributed/gspartition/sagemaker.rst
  docs/source/cli/graph-construction/distributed/gsprocessing/aws-infra/amazon-sagemaker.rst
  docs/source/cli/graph-construction/distributed/gsprocessing/aws-infra/emr-serverless.rst
  docs/source/cli/graph-construction/distributed/gsprocessing/aws-infra/emr.rst
  docs/source/cli/graph-construction/distributed/gsprocessing/aws-infra/index.rst
  docs/source/cli/graph-construction/distributed/gsprocessing/aws-infra/row-count-alignment.rst
  docs/source/cli/graph-construction/distributed/gsprocessing/developer-guide.rst
  docs/source/cli/graph-construction/distributed/gsprocessing/distributed-processing-setup.rst
  docs/source/cli/graph-construction/distributed/gsprocessing/gs-processing-getting-started.rst
  docs/source/cli/graph-construction/distributed/gsprocessing/index.rst
  docs/source/cli/graph-construction/distributed/gsprocessing/input-configuration.rst
  docs/source/cli/graph-construction/distributed/index.rst
  docs/source/cli/graph-construction/index.rst
  docs/source/cli/graph-construction/raw_data.rst
  docs/source/cli/graph-construction/single-machine-gconstruct.rst
  docs/source/cli/model-training-inference/configuration-run.rst
  docs/source/cli/model-training-inference/distributed/cluster.rst
  docs/source/cli/model-training-inference/distributed/sagemaker.rst
  docs/source/cli/model-training-inference/index.rst
  docs/source/cli/model-training-inference/output-remapping.rst
  docs/source/cli/model-training-inference/output.rst
  docs/source/cli/model-training-inference/single-machine-training-inference.rst
  docs/source/configuration/configuration-gconstruction.rst
  docs/source/configuration/configuration-partition.rst
  docs/source/configuration/index.rst
  docs/source/graph-construction/gs-processing/aws-infra/index.rst
  docs/source/graph-construction/gs-processing/gspartition/index.rst
  docs/source/graph-construction/gs-processing/index.rst
  docs/source/graph-construction/gs-processing/prerequisites/index.rst
  docs/source/graph-construction/index.rst
  docs/source/index.rst
  docs/source/tutorials/own-data.rst
Labels: documentation, ready, 0.3.1

#978 [Bug Fix] Trim leading/tailing space for `node_feat_name`
  docs/source/cli/model-training-inference/configuration-run.rst
  python/graphstorm/config/argument.py
  tests/unit-tests/test_config.py
Labels: bug, ready, 0.4

#979 [BugFix] Fix distmult evaluation score calculation
  python/graphstorm/model/edge_decoder.py
  tests/unit-tests/test_decoder.py
Labels: bug, ready, 0.4

#987 [Doc] Update readme files for training_scripts and inference_scripts samples
  inference_scripts/ep_infer/README.md
  inference_scripts/lp_infer/README.md
  inference_scripts/mt_infer/README.md
  inference_scripts/np_infer/README.md
  training_scripts/gsgnn_ep/README.md
  training_scripts/gsgnn_lp/README.md
  training_scripts/gsgnn_mt/README.md
  training_scripts/gsgnn_np/README.md
  training_scripts/gsgnn_np/ml_nc_mgpu.yaml
Labels: documentation, 0.4

#986 Add support of RotatE for link prediction.
  python/graphstorm/config/__init__.py
  python/graphstorm/config/config.py
  python/graphstorm/eval/utils.py
  python/graphstorm/gsf.py
  python/graphstorm/inference/lp_infer.py
  python/graphstorm/model/__init__.py
  python/graphstorm/model/edge_decoder.py
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
  tests/end2end-tests/graphstorm-lp/test.sh
  tests/unit-tests/test_decoder.py
Labels: ready, 0.4

#991 [Doc] Add doc for RotatE
  docs/source/advanced/link-prediction.rst
  docs/source/api/references/graphstorm.model.rst
  docs/source/cli/model-training-inference/configuration-run.rst
  python/graphstorm/eval/utils.py
  python/graphstorm/model/edge_decoder.py
Labels: documentation, ready, 0.4
