Repository awslabs/graphstorm, pull requests merged in 2024-07, with the labels that each got.

#902 [GSProcessing] Increment version. Add a simplified launch script for EMR on EC2.
  docs/source/gs-processing/usage/emr.rst
  graphstorm-processing/docker/0.3.1/emr-serverless/Dockerfile.cpu
  graphstorm-processing/docker/0.3.1/emr/Dockerfile.cpu
  graphstorm-processing/docker/0.3.1/sagemaker/Dockerfile.cpu
  graphstorm-processing/graphstorm_processing/constants.py
  graphstorm-processing/graphstorm_processing/data_transformations/spark_utils.py
  graphstorm-processing/graphstorm_processing/distributed_executor.py
  graphstorm-processing/pyproject.toml
  graphstorm-processing/scripts/submit_gsp_emr_step.py
Labels: ready, gsprocessing, 0.3.1

#908 Add feature name in the error reports of feature transformations.
  python/graphstorm/gconstruct/transform.py
Labels: ready, 0.3.1

#909 [Bugfix] Loss funcs for multitask learning should also be added as torch nn.module
  python/graphstorm/model/multitask_gnn.py
  tests/unit-tests/test_gnn.py
Labels: bug, ready, 0.3.1

#904 [Doc] Document and Tutorial Structure Reorg for v0.3.1
  docs/source/api/notebooks/Notebook_0_Data_Prepare.ipynb
  docs/source/api/notebooks/Notebook_1_NC_Pipeline.ipynb
  docs/source/api/notebooks/Notebook_2_LP_Pipeline.ipynb
  docs/source/api/notebooks/demo_models.py
  docs/source/api/notebooks/index.rst
  docs/source/api/references/graphstorm.dataloading.rst
  docs/source/api/references/graphstorm.eval.rst
  docs/source/api/references/graphstorm.inference.rst
  docs/source/api/references/graphstorm.model.rst
  docs/source/api/references/graphstorm.rst
  docs/source/api/references/graphstorm.trainer.rst
  docs/source/api/references/index.rst
  docs/source/index.rst
Labels: ready, 0.3.1

#911 [New feature] Support hit@k for classification tasks
  docs/source/configuration/configuration-run.rst
  python/graphstorm/config/argument.py
  python/graphstorm/eval/__init__.py
  python/graphstorm/eval/eval_func.py
  python/graphstorm/eval/evaluator.py
  tests/unit-tests/test_config.py
  tests/unit-tests/test_eval_func.py
Labels: enhancement, ready, 0.3.1

#913 [Bugfix] Fix EntityRegression.out_dims() dimension mismatch
  python/graphstorm/model/node_decoder.py
  tests/unit-tests/test_decoder.py
Labels: bug, ready, 0.3.1

#914 [Doc] Fix `demo_models.py` link
  docs/source/api/notebooks/index.rst
Labels: documentation, ready, 0.3.1

#912 Support layer norm and batch norm in classification and regression decoders.
  docs/source/configuration/configuration-run.rst
  python/graphstorm/config/argument.py
  python/graphstorm/gsf.py
  python/graphstorm/model/edge_decoder.py
  python/graphstorm/model/node_decoder.py
  tests/end2end-tests/graphstorm-ec/test.sh
  tests/end2end-tests/graphstorm-er/test.sh
  tests/end2end-tests/graphstorm-nc/test.sh
  tests/unit-tests/test_decoder.py
Labels: enhancement, break back compatibility, ready, 0.3.1

#916 Add support to deduplicate same input features when computing rank gauss norm.
  docs/source/configuration/configuration-gconstruction.rst
  python/graphstorm/gconstruct/transform.py
  tests/unit-tests/gconstruct/test_construct_graph.py
  tests/unit-tests/gconstruct/test_transform.py
Labels: ready, 0.3.1

#915 [GSProcessing] Fix bug in repartition on leader, fix mypy errors and latent bugs
  graphstorm-processing/graphstorm_processing/config/label_config_base.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_bucket_numerical_transformation.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_category_transformation.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_hf_transformation.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_label_transformation.py
  graphstorm-processing/graphstorm_processing/data_transformations/spark_utils.py
  graphstorm-processing/graphstorm_processing/distributed_executor.py
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
  graphstorm-processing/graphstorm_processing/repartition_files.py
  graphstorm-processing/mypy.ini
Labels: ready, gsprocessing, 0.3.1

#907 [Doc] Graph Construction PR Refactor - PR1: GSProcessing Doc Refactor
  docs/source/graph-construction/gs-processing/aws-infra/amazon-sagemaker.rst
  docs/source/graph-construction/gs-processing/aws-infra/emr-serverless.rst
  docs/source/graph-construction/gs-processing/aws-infra/emr.rst
  docs/source/graph-construction/gs-processing/aws-infra/index.rst
  docs/source/graph-construction/gs-processing/aws-infra/row-count-alignment.rst
  docs/source/graph-construction/gs-processing/example.rst
  docs/source/graph-construction/gs-processing/index.rst
  docs/source/graph-construction/gs-processing/input-configuration.rst
  docs/source/graph-construction/gs-processing/prerequisites/developer-guide.rst
  docs/source/graph-construction/gs-processing/prerequisites/distributed-processing-setup.rst
  docs/source/graph-construction/gs-processing/prerequisites/gs-processing-getting-started.rst
  docs/source/graph-construction/gs-processing/prerequisites/index.rst
  docs/source/graph-construction/index.rst
  docs/source/index.rst
Labels: documentation, 0.3.1

#920 [Enhancement] Enable edge feature and edge input encoder for experimental edage feature support
  python/graphstorm/model/gnn.py
Labels: enhancement, ready, 0.3.1

#921 [SageMaker] Add launch script to multi-task
  docs/source/advanced/multi-task-learning.rst
  python/graphstorm/config/__init__.py
  python/graphstorm/config/config.py
  python/graphstorm/sagemaker/sagemaker_infer.py
  python/graphstorm/sagemaker/sagemaker_train.py
  sagemaker/launch/common_parser.py
Labels: ready

#924 Make warning information of graph_sanity_check.py more informative.
  tools/graph_sanity_check.py
Labels: good first issue, 0.3.1

#923 Update doc of link prediction
  docs/source/advanced/advanced-usages.rst
  docs/source/advanced/link-prediction.rst
  docs/source/index.rst
  python/graphstorm/model/loss_func.py
Labels: documentation, 0.3.1

#919 [Doc] New API Example Notebook 3 - Model Variant
  docs/source/api/notebooks/Notebook_1_NC_Pipeline.ipynb
  docs/source/api/notebooks/Notebook_2_LP_Pipeline.ipynb
  docs/source/api/notebooks/Notebook_3_Model_Variants.ipynb
  docs/source/api/notebooks/demo_models.py
  docs/source/api/notebooks/index.rst
Labels: documentation, 0.3.1

#922 [GSProcessing] Add option to truncate vectors with no-op transformation.
  docs/source/configuration/configuration-gconstruction.rst
  docs/source/graph-construction/gs-processing/input-configuration.rst
  graphstorm-processing/graphstorm_processing/config/feature_config_base.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_noop_transformation.py
  graphstorm-processing/graphstorm_processing/distributed_executor.py
  graphstorm-processing/tests/resources/small_heterogeneous_graph/gsprocessing-config.json
  graphstorm-processing/tests/test_dist_heterogenous_loader.py
  graphstorm-processing/tests/test_dist_noop_transformation.py
  python/graphstorm/gconstruct/transform.py
  tests/unit-tests/gconstruct/test_transform.py
Labels: ready, gsprocessing, 0.3.1

#931 [GPartition] Rename the input argument for dispatch
  python/graphstorm/gpartition/dist_partition_graph.py
Labels: break back compatibility, ready

#929 [Doc] New API example notebook 4 - Customized Models
  docs/source/api/notebooks/Notebook_0_Data_Prepare.ipynb
  docs/source/api/notebooks/Notebook_1_NC_Pipeline.ipynb
  docs/source/api/notebooks/Notebook_2_LP_Pipeline.ipynb
  docs/source/api/notebooks/Notebook_3_Model_Variants.ipynb
  docs/source/api/notebooks/Notebook_4_Customized_Models.ipynb
  docs/source/api/notebooks/index.rst
Labels: documentation, ready, 0.3.1

#936 Ensure extra env vars are propagated to remap command
  python/graphstorm/run/launch.py
Labels: bug, ready, 0.3.1

#943 [GSProcessing] Update EMRS image to 7.1.0, add file in image to ensure we recognize execution env.
  graphstorm-processing/docker/0.3.1/emr-serverless/Dockerfile.cpu
  graphstorm-processing/graphstorm_processing/distributed_executor.py
Labels: ready, gsprocessing, 0.3.1

#934 [Doc] API doc string refactor for graphstorm.dataloading
  docs/source/_templates/dataloadertemplate.rst
  docs/source/_templates/datasettemplate.rst
  docs/source/api/references/graphstorm.dataloading.rst
  docs/source/graph-construction/index.rst
  python/graphstorm/dataloading/dataloading.py
  python/graphstorm/dataloading/dataset.py
  python/graphstorm/trainer/lp_trainer.py
  python/graphstorm/trainer/mt_trainer.py
Labels: documentation, break back compatibility, ready, 0.3.1

#926 [BugFix] Fix missing node normalization for link prediction tasks in multi-task learning
  inference_scripts/mt_infer/ml_nc_lp_norm_with_mask_infer.yaml
  python/graphstorm/gconstruct/remap_result.py
  python/graphstorm/inference/mt_infer.py
  python/graphstorm/model/multitask_gnn.py
  python/graphstorm/run/gsgnn_mt/gsgnn_mt.py
  python/graphstorm/run/gsgnn_mt/mt_infer_gnn.py
  python/graphstorm/trainer/mt_trainer.py
  tests/end2end-tests/graphstorm-mt/mgpu_test.sh
  tests/unit-tests/gconstruct/test_remap_result.py
  tests/unit-tests/test_gnn.py
  tests/unit-tests/util.py
  training_scripts/gsgnn_mt/ml_nc_lp_norm.yaml
Labels: ready, 0.3.1

#918 [Doc] Graph Construction PR Refactor - PR2: GPartition Doc
  docs/source/graph-construction/gs-processing/example.rst
  docs/source/graph-construction/gs-processing/gspartition/ec2-clusters.rst
  docs/source/graph-construction/gs-processing/gspartition/index.rst
  docs/source/graph-construction/gs-processing/gspartition/sagemaker.rst
  docs/source/graph-construction/gs-processing/index.rst
  docs/source/graph-construction/gs-processing/prerequisites/index.rst
  tutorial/distributed_construction.png
Labels: ready
