Repository awslabs/graphstorm, pull requests merged in 2024-02, with the labels that each got.

#719 [Enhancement] Move get_graph_name from graphstorm.config.utils to graphstorm.utils
  python/graphstorm/config/argument.py
  python/graphstorm/config/utils.py
  python/graphstorm/utils.py
  tests/unit-tests/test_config.py
  tests/unit-tests/test_utils.py
Labels: enhancement, ready, 0.2.2

#717 [Enhance] Support float64 as output type in graph construction
  docs/source/configuration/configuration-gconstruction.rst
  python/graphstorm/gconstruct/transform.py
  tests/unit-tests/gconstruct/test_transform.py
Labels: bug, ready, 0.2.2

#700 [GSProcessing] BERT Tokenizer
  docs/source/gs-processing/developer/input-configuration.rst
  docs/source/gs-processing/usage/distributed-processing-setup.rst
  docs/source/gs-processing/usage/emr-serverless.rst
  graphstorm-processing/docker/0.2.2/emr-serverless/Dockerfile.cpu
  graphstorm-processing/docker/0.2.2/sagemaker/Dockerfile.cpu
  graphstorm-processing/docker/build_gsprocessing_image.sh
  graphstorm-processing/graphstorm_processing/config/config_conversion/gconstruct_converter.py
  graphstorm-processing/graphstorm_processing/config/config_parser.py
  graphstorm-processing/graphstorm_processing/config/hf_configs.py
  graphstorm-processing/graphstorm_processing/constants.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_feature_transformer.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/__init__.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_hf_transformation.py
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
  graphstorm-processing/graphstorm_processing/graph_loaders/schema_utils.py
  graphstorm-processing/pyproject.toml
  graphstorm-processing/tests/resources/small_heterogeneous_graph/gconstruct-config.json
  graphstorm-processing/tests/resources/small_heterogeneous_graph/gsprocessing-config.json
  graphstorm-processing/tests/test_converter.py
  graphstorm-processing/tests/test_dist_heterogenous_loader.py
  graphstorm-processing/tests/test_dist_huggingface_transformation.py
Labels: ready, gsprocessing, 0.2.2

#720 [Enhancement] Add get_node_feat_size to GSgnnData
  examples/temporal_graph_learning/model_nc.py
  python/graphstorm/__init__.py
  python/graphstorm/dataloading/dataset.py
  python/graphstorm/gsf.py
  python/graphstorm/model/embed.py
  python/graphstorm/model/gat_encoder.py
  python/graphstorm/model/hgt_encoder.py
  python/graphstorm/model/lm_embed.py
  python/graphstorm/model/rgat_encoder.py
  python/graphstorm/model/rgcn_encoder.py
  python/graphstorm/model/sage_encoder.py
  tests/end2end-tests/custom-gnn/train.py
  tests/unit-tests/data_utils.py
  tests/unit-tests/test_dataloading.py
  tests/unit-tests/test_embed.py
  tests/unit-tests/test_gnn.py
  tests/unit-tests/test_model_save_load.py
  tests/unit-tests/test_utils.py
Labels: enhancement, ready, 0.2.2

#729 [Bug Fix] Local Docker Build
  docker/Dockerfile.local
Labels: ready

#721 [Enhancement] Add default values for sparse_optimizer_lr and weight_decay
  docs/source/configuration/configuration-run.rst
  python/graphstorm/model/gnn.py
  python/graphstorm/model/node_glem.py
Labels: enhancement, ready, 0.2.2

#677 Add the support of using WholeGraph distributed embedding to store/update sparse_emb
  python/graphstorm/config/argument.py
  python/graphstorm/gsf.py
  python/graphstorm/model/embed.py
  python/graphstorm/model/gnn.py
  python/graphstorm/model/utils.py
  python/graphstorm/run/gsgnn_emb/gsgnn_node_emb.py
  python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/run/gsgnn_np/gsgnn_np.py
  python/graphstorm/wholegraph/__init__.py
  python/graphstorm/wholegraph/utils.py
  python/graphstorm/wholegraph/wholegraph.py
  tests/unit-tests/test_wg_sparse_emb.py
  tests/unit-tests/test_wg_sparse_opt.py
Labels: ready

#724 [GSProcessing] Bert Embedding
  docs/source/gs-processing/developer/input-configuration.rst
  graphstorm-processing/docker/0.2.2/emr-serverless/Dockerfile.cpu
  graphstorm-processing/docker/0.2.2/sagemaker/Dockerfile.cpu
  graphstorm-processing/graphstorm_processing/config/config_conversion/gconstruct_converter.py
  graphstorm-processing/graphstorm_processing/config/hf_configs.py
  graphstorm-processing/graphstorm_processing/constants.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_hf_transformation.py
  graphstorm-processing/pyproject.toml
  graphstorm-processing/tests/resources/small_heterogeneous_graph/gsprocessing-config.json
  graphstorm-processing/tests/test_converter.py
  graphstorm-processing/tests/test_dist_huggingface_transformation.py
Labels: ready, gsprocessing, 0.2.2

#726 [Enhancement] Add default task tracker in trainers and inferrers
  docs/source/_templates/datasettemplate.rst
  python/graphstorm/eval/evaluator.py
  python/graphstorm/inference/graphstorm_infer.py
  python/graphstorm/tracker/graphstorm_tracker.py
  python/graphstorm/trainer/gsgnn_trainer.py
  tests/unit-tests/test_inferrer.py
  tests/unit-tests/test_trainer.py
Labels: enhancement, ready, 0.2.2

#731 [GSProcessing] Make SageMaker image build faster and smaller.
  graphstorm-processing/docker/0.2.2/emr-serverless/Dockerfile.cpu
  graphstorm-processing/docker/0.2.2/sagemaker/Dockerfile.cpu
  graphstorm-processing/docker/README.md
  graphstorm-processing/docker/build_gsprocessing_image.sh
  graphstorm-processing/docker/push_gsprocessing_image.sh
Labels: ready, gsprocessing, 0.2.2

#736 [Bug fix] Add NCCL test for save embedding during training and fix device bugs.
  python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
  python/graphstorm/run/gsgnn_ep/gsgnn_lm_ep.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/run/gsgnn_np/gsgnn_np.py
  tests/end2end-tests/graphstorm-ec/mgpu_test.sh
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
  tests/end2end-tests/graphstorm-nc/mgpu_test.sh
Labels: ready, 0.2.2

#738 [Doc Fix] Sync doc for Remap
  docs/source/configuration/configuration-gconstruction.rst
  docs/source/scale/sagemaker.rst
  docs/source/tutorials/own-data.rst
Labels: documentation, 0.2.2

#732 Add end2end CI test for wholegraph
  .github/workflow_scripts/e2e_mgpu_check.sh
  python/graphstorm/model/embed.py
  python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_np/np_infer_gnn.py
  tests/end2end-tests/check_np_infer_emb.py
  tests/end2end-tests/graphstorm-ec/mgpu_test.sh
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
  tests/end2end-tests/graphstorm-nc/mgpu_test.sh
Labels: ready, 0.2.2

#740 [WholeGraph] Setup CI for WholeGraph support
  .github/workflow_scripts/e2e_mgpu_check.sh
  python/graphstorm/model/embed.py
  python/graphstorm/model/gnn.py
  python/graphstorm/model/utils.py
  python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_np/np_infer_gnn.py
  python/graphstorm/wholegraph/wholegraph.py
  tests/end2end-tests/check_np_infer_emb.py
  tests/end2end-tests/graphstorm-ec/mgpu_test.sh
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
  tests/end2end-tests/graphstorm-nc/mgpu_test.sh
Labels: ready, 0.2.2

#735 [GSProcessing] Documentation updates for 0.2.2
  .gitignore
  docs/source/gs-processing/developer/input-configuration.rst
  docs/source/gs-processing/usage/amazon-sagemaker.rst
  docs/source/gs-processing/usage/distributed-processing-setup.rst
  docs/source/gs-processing/usage/emr-serverless.rst
  docs/source/gs-processing/usage/example.rst
  docs/source/gs-processing/usage/row-count-alignment.rst
  graphstorm-processing/docker/README.md
  graphstorm-processing/docker/build_gsprocessing_image.sh
Labels: documentation, gsprocessing, 0.2.2

#741 Fix a bug in balancing training/valid/test in graph partitioning.
  python/graphstorm/gconstruct/utils.py
  tests/unit-tests/gconstruct/test_construct_graph.py
Labels: ready

#744 [WholeGraph] Rename the flag for wholegraph sparse embedding
  python/graphstorm/config/argument.py
  python/graphstorm/gsf.py
  python/graphstorm/run/gsgnn_emb/gsgnn_node_emb.py
  python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
  python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_np/gsgnn_np.py
  python/graphstorm/run/gsgnn_np/np_infer_gnn.py
  tests/end2end-tests/graphstorm-ec/mgpu_test.sh
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
  tests/end2end-tests/graphstorm-nc/mgpu_test.sh
Labels: ready, 0.2.2

#746 [GSProcessing Bug Fix] Fix a bug for GConstruct Config Converter
  graphstorm-processing/graphstorm_processing/config/config_conversion/gconstruct_converter.py
  graphstorm-processing/tests/test_converter.py
Labels: 0.3, ready, gsprocessing

#749 [GSProcessing CI Update] Add black check to GSProcessing Lint Check
  .github/workflow_scripts/gsprocessing_lint.sh
  graphstorm-processing/graphstorm_processing/config/categorical_configs.py
  graphstorm-processing/graphstorm_processing/config/config_conversion/__init__.py
  graphstorm-processing/graphstorm_processing/config/config_conversion/converter_base.py
  graphstorm-processing/graphstorm_processing/config/config_conversion/meta_configuration.py
  graphstorm-processing/graphstorm_processing/config/feature_config_base.py
  graphstorm-processing/graphstorm_processing/config/label_config_base.py
  graphstorm-processing/graphstorm_processing/config/numerical_configs.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_label_loader.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/base_dist_transformation.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_bucket_numerical_transformation.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_category_transformation.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_label_transformation.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_noop_transformation.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_numerical_transformation.py
  graphstorm-processing/graphstorm_processing/data_transformations/s3_utils.py
  graphstorm-processing/graphstorm_processing/data_transformations/spark_utils.py
  graphstorm-processing/graphstorm_processing/distributed_executor.py
  graphstorm-processing/graphstorm_processing/graph_loaders/heterogeneous_graphloader.py
  graphstorm-processing/graphstorm_processing/graph_loaders/loader_base.py
  graphstorm-processing/graphstorm_processing/graph_loaders/row_count_utils.py
  graphstorm-processing/graphstorm_processing/repartition_files.py
  graphstorm-processing/pyproject.toml
  graphstorm-processing/scripts/convert_gconstruct_config.py
  graphstorm-processing/scripts/run_distributed_processing.py
  graphstorm-processing/scripts/run_repartitioning.py
  graphstorm-processing/scripts/script_utils.py
  graphstorm-processing/tests/conftest.py
  graphstorm-processing/tests/test_dist_bucket_transformation.py
  graphstorm-processing/tests/test_dist_category_transformation.py
  graphstorm-processing/tests/test_dist_label_loader.py
  graphstorm-processing/tests/test_dist_noop_transformation.py
  graphstorm-processing/tests/test_dist_numerical_transformation.py
  graphstorm-processing/tests/test_repartition_files.py
Labels: 0.3, ready, gsprocessing

#762 [Bug Fix] Fix GConstruct Lint error
  python/graphstorm/gconstruct/utils.py
Labels: ready
