Repository awslabs/graphstorm, pull requests merged in 2024-05, with the labels that each got.

#810 [Enhancement] Remove GSF dependency on lint check CI
  .github/workflow_scripts/lint_check.sh
Labels: ready

#825 Refactor gsf.py to make the code of creating decoders and creating link prediction dataloders reusable.
  python/graphstorm/__init__.py
  python/graphstorm/gsf.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
Labels: 0.3, ready

#828 [Multi-task Learning] Update GraphStorm input config to support multi-task learning
  python/graphstorm/config/__init__.py
  python/graphstorm/config/argument.py
  python/graphstorm/config/config.py
  tests/unit-tests/test_config.py
Labels: 0.3, ready

#830 [Doc] New API example notebook 1
  docs/source/index.rst
  docs/source/notebooks/Notebook_0_Data_Prepare.ipynb
  docs/source/notebooks/Notebook_1_NC_Pipeline.ipynb
  docs/source/notebooks/demo_models.py
  python/graphstorm/gsf.py
Labels: documentation, 0.3, ready

#832 [Docker] Move the Amazon ECR Public Gallery auth to only the CPU branch of the local build script.
  docker/build_docker_oss4local.sh
Labels: bug, 0.3

#831 [Bug] Minor issues fixed for new example notebook 2.
  python/graphstorm/eval/evaluator.py
  python/graphstorm/trainer/ep_trainer.py
  python/graphstorm/trainer/lp_trainer.py
  python/graphstorm/trainer/np_trainer.py
Labels: 0.3, ready

#836 [Doc] Minor doc fix
  docs/source/advanced/own-models.rst
  docs/source/configuration/configuration-run.rst
  docs/source/install/env-setup.rst
Labels: documentation, 0.3, ready

#840 [Fix] Fix the error on prospector
  .github/workflow_scripts/lint_check.sh
  python/graphstorm/run/launch.py
  tools/convert_feat_to_wholegraph.py
Labels: ready

#839 [Bug] Fix error of reconstruct embed encoder when use_mini_batch_infer=true
  python/graphstorm/model/gnn_with_reconstruct.py
  python/graphstorm/trainer/lp_trainer.py
  tests/end2end-tests/graphstorm-lp/test.sh
Labels: bug, 0.3, ready

#834 [Multi-task Learning] Add multi-task Dataloader for multi-task learning
  python/graphstorm/dataloading/__init__.py
  python/graphstorm/dataloading/dataloading.py
  tests/unit-tests/data_utils.py
  tests/unit-tests/test_dataloading.py
Labels: 0.3, ready

#837 [Multi-task Learning] Add multi-task evaluator for multi-task learning
  python/graphstorm/eval/__init__.py
  python/graphstorm/eval/evaluator.py
  tests/unit-tests/test_evaluator.py
Labels: 0.3, ready

#843 [Multi-task Learning] Add Multi-task test dataset
  tests/end2end-tests/create_data.sh
  tests/end2end-tests/data_gen/movielens_multi_task.json
  tests/end2end-tests/data_gen/process_movielens.py
  training_scripts/gsgnn_mt/README.md
  training_scripts/gsgnn_mt/ml_nc_ec_er_lp.yaml
Labels: 0.3

#844 [Doc] Update the Notebook 0 to reflect the changes in v0.3
  docs/source/notebooks/Notebook_0_Data_Prepare.ipynb
Labels: documentation, 0.3, ready

#847 [GSProcessing] Fix arg parsing error in push_gsprocessing_image
  graphstorm-processing/docker/push_gsprocessing_image.sh
Labels: 0.3, gsprocessing

#850 [BugFix] Fix node class full graph infer
  python/graphstorm/model/node_gnn.py
  tests/unit-tests/test_gnn.py
Labels: bug, 0.3

#845 Update docstring of remove_target_edge_type
  python/graphstorm/config/argument.py
Labels: 0.3, ready

#827 [GSProcessing] Custom split for GSProcessing
  docs/source/gs-processing/developer/input-configuration.rst
  graphstorm-processing/graphstorm_processing/config/config_conversion/gconstruct_converter.py
  graphstorm-processing/graphstorm_processing/config/label_config_base.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_label_loader.py
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
  graphstorm-processing/tests/test_converter.py
  graphstorm-processing/tests/test_dist_heterogenous_loader.py
Labels: ready

#846 [Doc] New API example Notebook 2 - Link Prediction
  docs/source/notebooks/Notebook_2_LP_Pipeline.ipynb
  docs/source/notebooks/demo_models.py
Labels: documentation, 0.3, ready

#852 [Multi-task Learning] Refactor graphstorm.model for multi-task learning.
  python/graphstorm/model/__init__.py
  python/graphstorm/model/edge_gnn.py
  python/graphstorm/model/lp_gnn.py
  python/graphstorm/model/node_gnn.py
  tests/unit-tests/test_gnn.py
Labels: 0.3, ready

#853 [Enhancement] Change save new gconstruct configuration file behavior
  docs/source/configuration/configuration-gconstruction.rst
  python/graphstorm/gconstruct/construct_graph.py
Labels: enhancement, 0.3, ready

#856 [Doc] Fix notebook 2 is not listed in index page issue
  docs/source/index.rst
Labels: documentation, 0.3, ready

#855 [Multi-task Learning] Add GSgnnMultiTaskSharedEncoderModel
  python/graphstorm/dataloading/dataloading.py
  python/graphstorm/model/__init__.py
  python/graphstorm/model/multitask_gnn.py
  tests/unit-tests/test_gnn.py
Labels: 0.3, ready

#838 [GSProcessing] Improve Spark config to better support EMR/EMRS, small optimizations
  graphstorm-processing/docker/push_gsprocessing_image.sh
  graphstorm-processing/graphstorm_processing/constants.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_hf_transformation.py
  graphstorm-processing/graphstorm_processing/data_transformations/spark_utils.py
  graphstorm-processing/graphstorm_processing/distributed_executor.py
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
  graphstorm-processing/graphstorm_processing/repartition_files.py
  graphstorm-processing/tests/test_repartition_files.py
Labels: 0.3, ready, gsprocessing

#842 [Multi-task Learning] Add support for multi-task learning
  .github/workflow_scripts/e2e_mgpu_check.sh
  python/graphstorm/__init__.py
  python/graphstorm/config/__init__.py
  python/graphstorm/config/argument.py
  python/graphstorm/config/config.py
  python/graphstorm/dataloading/__init__.py
  python/graphstorm/dataloading/dataloading.py
  python/graphstorm/eval/__init__.py
  python/graphstorm/eval/evaluator.py
  python/graphstorm/gsf.py
  python/graphstorm/inference/lp_infer.py
  python/graphstorm/model/__init__.py
  python/graphstorm/model/edge_gnn.py
  python/graphstorm/model/lp_gnn.py
  python/graphstorm/model/multitask_gnn.py
  python/graphstorm/model/node_gnn.py
  python/graphstorm/run/gs_multi_task_learning.py
  python/graphstorm/run/gsgnn_mt/__init__.py
  python/graphstorm/run/gsgnn_mt/gsgnn_mt.py
  python/graphstorm/trainer/__init__.py
  python/graphstorm/trainer/mt_trainer.py
  python/graphstorm/trainer/np_trainer.py
  tests/end2end-tests/create_data.sh
  tests/end2end-tests/data_gen/movielens_multi_task.json
  tests/end2end-tests/data_gen/process_movielens.py
  tests/end2end-tests/graphstorm-mt/mgpu_test.sh
  tests/unit-tests/data_utils.py
  tests/unit-tests/test_config.py
  tests/unit-tests/test_dataloading.py
  tests/unit-tests/test_evaluator.py
  tests/unit-tests/test_gnn.py
  tests/unit-tests/test_trainer.py
  training_scripts/gsgnn_mt/README.md
  training_scripts/gsgnn_mt/ml_nc_ec_er_lp.yaml
Labels: 0.3, ready
