Repository awslabs/graphstorm, pull requests merged in 2024-04, with the labels that each got.

#767 [GSProcessing] Allow re-partitioning to run on the Spark leader
  docs/source/gs-processing/gs-processing-getting-started.rst
  docs/source/gs-processing/usage/amazon-sagemaker.rst
  docs/source/gs-processing/usage/emr-serverless.rst
  docs/source/gs-processing/usage/example.rst
  docs/source/gs-processing/usage/row-count-alignment.rst
  graphstorm-processing/docker/push_gsprocessing_image.sh
  graphstorm-processing/graphstorm_processing/data_transformations/spark_utils.py
  graphstorm-processing/graphstorm_processing/distributed_executor.py
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
  graphstorm-processing/graphstorm_processing/graph_loaders/row_count_utils.py
  graphstorm-processing/graphstorm_processing/repartition_files.py
  graphstorm-processing/scripts/run_distributed_processing.py
  graphstorm-processing/scripts/run_repartitioning.py
  graphstorm-processing/tests/resources/repartitioning/partitioned_metadata.json
  graphstorm-processing/tests/test_repartition_files.py
Labels: 0.3, ready, gsprocessing

#791 [GSProcessing] Move to Spark 3.5, bump version to 0.3.0, add homogeneous edge mapping optimization
  graphstorm-processing/docker/0.3.0/emr-serverless/Dockerfile.cpu
  graphstorm-processing/docker/0.3.0/sagemaker/Dockerfile.cpu
  graphstorm-processing/docker/push_gsprocessing_image.sh
  graphstorm-processing/graphstorm_processing/distributed_executor.py
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
  graphstorm-processing/pyproject.toml
  graphstorm-processing/scripts/run_distributed_processing.py
Labels: 0.3, ready, gsprocessing

#769 [GConstruct] Add Customized Edge split
  docs/source/configuration/configuration-gconstruction.rst
  docs/source/tutorials/own-data.rst
  python/graphstorm/gconstruct/file_io.py
  python/graphstorm/gconstruct/transform.py
  tests/end2end-tests/data_process/data_gen.py
  tests/end2end-tests/data_process/test_data.py
  tests/unit-tests/gconstruct/test_construct_graph.py
  tests/unit-tests/gconstruct/test_transform.py
Labels: ready

#800 Update logging info of remap result
  python/graphstorm/gconstruct/remap_result.py
Labels: 0.3, ready

#795 Refactor Dataloading and Dataset
  docs/source/tutorials/own-data.rst
  python/graphstorm/config/argument.py
  python/graphstorm/dataloading/__init__.py
  python/graphstorm/dataloading/dataloading.py
  python/graphstorm/dataloading/dataset.py
  python/graphstorm/dataloading/utils.py
  python/graphstorm/eval/evaluator.py
  python/graphstorm/inference/emb_infer.py
  python/graphstorm/inference/ep_infer.py
  python/graphstorm/inference/np_infer.py
  python/graphstorm/model/edge_gnn.py
  python/graphstorm/model/node_gnn.py
  python/graphstorm/run/gsgnn_emb/gsgnn_node_emb.py
  python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
  python/graphstorm/run/gsgnn_ep/ep_infer_lm.py
  python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
  python/graphstorm/run/gsgnn_ep/gsgnn_lm_ep.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
  python/graphstorm/run/gsgnn_np/gsgnn_np.py
  python/graphstorm/run/gsgnn_np/np_infer_gnn.py
  python/graphstorm/trainer/ep_trainer.py
  python/graphstorm/trainer/glem_np_trainer.py
  python/graphstorm/trainer/lp_trainer.py
  python/graphstorm/trainer/np_trainer.py
  tests/end2end-tests/custom-gnn/train.py
  tests/unit-tests/data_utils.py
  tests/unit-tests/test_dataloading.py
  tests/unit-tests/test_gnn.py
Labels: 0.3, ready

#803 James c levaluator
  docs/source/advanced/own-models.rst
  docs/source/api/graphstorm.eval.rst
  examples/customized_models/HGT/hgt_nc.py
  examples/peft_llm_gnn/main_nc.py
  examples/standalone_mode_demo.ipynb
  examples/temporal_graph_learning/main_nc.py
  python/graphstorm/eval/__init__.py
  python/graphstorm/eval/evaluator.py
  python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
  python/graphstorm/run/gsgnn_ep/ep_infer_lm.py
  python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
  python/graphstorm/run/gsgnn_ep/gsgnn_lm_ep.py
  python/graphstorm/run/gsgnn_np/gsgnn_np.py
  python/graphstorm/run/gsgnn_np/np_infer_gnn.py
  tests/unit-tests/test_dist_eval.py
  tests/unit-tests/test_evaluator.py
  tests/unit-tests/test_inferrer.py
  tests/unit-tests/test_trainer.py
Labels: enhancement, 0.3, ready

#798 [GConstruct] Allow parquet file as input for customized edge split
  docs/source/tutorials/own-data.rst
  python/graphstorm/gconstruct/file_io.py
  python/graphstorm/gconstruct/transform.py
  tests/unit-tests/gconstruct/test_gconstruct_utils.py
Labels: ready

#808 [Docker] Move local image to CUDA 12.1. Add option for CPU local image.
  docker/Dockerfile.local
  docker/build_docker_oss4local.sh
  docker/build_docker_sagemaker.sh
  docs/source/install/env-setup.rst
  docs/source/scale/distributed.rst
  docs/source/scale/sagemaker.rst
Labels: 0.3, ready

#811 [GSProcessing] Add support for EMR on EC2 execution.
  docs/source/gs-processing/gs-processing-getting-started.rst
  docs/source/gs-processing/usage/distributed-processing-setup.rst
  docs/source/gs-processing/usage/emr-serverless.rst
  graphstorm-processing/docker/0.3.0/emr/Dockerfile.cpu
  graphstorm-processing/docker/build_gsprocessing_image.sh
  graphstorm-processing/docker/push_gsprocessing_image.sh
Labels: ready, gsprocessing

#812 Update GPeft example Readme
  examples/peft_llm_gnn/README.md
Labels: documentation

#804 [GConstruct] Allow users define train/validation/test masks
  python/graphstorm/gconstruct/construct_graph.py
  python/graphstorm/gconstruct/transform.py
  python/graphstorm/gconstruct/utils.py
  tests/end2end-tests/data_process/data_gen.py
  tests/end2end-tests/data_process/test.sh
  tests/end2end-tests/data_process/test_custom_mask_data.py
  tests/unit-tests/gconstruct/test_construct_graph.py
  tests/unit-tests/gconstruct/test_transform.py
Labels: 0.3, ready

#818 Add MAG construction code and description for GraphStorm Paper
  examples/paper_experiments/MAG_parser_v0.2.ipynb
  examples/paper_experiments/README.md
  examples/paper_experiments/gconstruct_configs/MAG_construction_full.json
Labels: documentation

#807 [Refactor] Regression, LP, and PerEtypeLP evaluators
  docs/source/api/graphstorm.eval.rst
  examples/peft_llm_gnn/main_lp.py
  python/graphstorm/config/argument.py
  python/graphstorm/eval/__init__.py
  python/graphstorm/eval/eval_func.py
  python/graphstorm/eval/evaluator.py
  python/graphstorm/inference/graphstorm_infer.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
  python/graphstorm/trainer/ep_trainer.py
  python/graphstorm/trainer/gsgnn_trainer.py
  python/graphstorm/trainer/lp_trainer.py
  python/graphstorm/trainer/np_trainer.py
  tests/unit-tests/test_dist_eval.py
  tests/unit-tests/test_evaluator.py
Labels: enhancement, 0.3, ready

#805 Update GSgnnData for examples
  docs/source/api/graphstorm.dataloading.rst
  examples/customized_models/HGT/README.md
  examples/customized_models/HGT/hgt_nc.py
  examples/peft_llm_gnn/main_lp.py
  examples/peft_llm_gnn/main_nc.py
  examples/temporal_graph_learning/graphstorm_train_script_nc_config.yaml
  examples/temporal_graph_learning/main_nc.py
  python/graphstorm/model/embed.py
  python/graphstorm/model/gat_encoder.py
  python/graphstorm/model/gatv2_encoder.py
  python/graphstorm/model/hgt_encoder.py
  python/graphstorm/model/lm_embed.py
  python/graphstorm/model/rgat_encoder.py
  python/graphstorm/model/rgcn_encoder.py
  python/graphstorm/model/sage_encoder.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
  tests/unit-tests/test_dataloading.py
  tests/unit-tests/test_gnn.py
Labels: 0.3, ready

#813 Support construct a graph for multi-task learning
  python/graphstorm/gconstruct/construct_graph.py
  python/graphstorm/gconstruct/transform.py
  tests/end2end-tests/data_process/multitask_data_gen.py
  tests/end2end-tests/data_process/test.sh
  tests/end2end-tests/data_process/test_multitask_data.py
  tests/unit-tests/gconstruct/test_construct_graph.py
  tests/unit-tests/gconstruct/test_transform.py
Labels: 0.3, ready

#819 [Doc] Final refine documents and tutorial for evaluator refactoring
  docs/source/api/graphstorm.eval.rst
Labels: documentation, 0.3, ready

#822 [Refactor] Refactor Evaluator
  docs/source/advanced/own-models.rst
  docs/source/api/graphstorm.eval.rst
  examples/customized_models/HGT/hgt_nc.py
  examples/peft_llm_gnn/main_lp.py
  examples/peft_llm_gnn/main_nc.py
  examples/standalone_mode_demo.ipynb
  examples/temporal_graph_learning/main_nc.py
  python/graphstorm/config/argument.py
  python/graphstorm/eval/__init__.py
  python/graphstorm/eval/eval_func.py
  python/graphstorm/eval/evaluator.py
  python/graphstorm/inference/graphstorm_infer.py
  python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
  python/graphstorm/run/gsgnn_ep/ep_infer_lm.py
  python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
  python/graphstorm/run/gsgnn_ep/gsgnn_lm_ep.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
  python/graphstorm/run/gsgnn_np/gsgnn_np.py
  python/graphstorm/run/gsgnn_np/np_infer_gnn.py
  python/graphstorm/trainer/ep_trainer.py
  python/graphstorm/trainer/gsgnn_trainer.py
  python/graphstorm/trainer/lp_trainer.py
  python/graphstorm/trainer/np_trainer.py
  tests/unit-tests/test_dist_eval.py
  tests/unit-tests/test_evaluator.py
  tests/unit-tests/test_inferrer.py
  tests/unit-tests/test_trainer.py
Labels: break back compatibility, 0.3, ready

#821 Update docs for Dataset and DataLoader
  docs/source/advanced/own-models.rst
  python/graphstorm/dataloading/dataloading.py
  python/graphstorm/dataloading/dataset.py
Labels: break back compatibility, 0.3, ready

#817 [Docs] Add documentation for EMR on EC2 for GSProcessing
  docs/source/gs-processing/usage/emr.rst
  docs/source/index.rst
Labels: documentation, 0.3, gsprocessing

#820 Refactor dataloading
  docs/source/advanced/own-models.rst
  docs/source/api/graphstorm.dataloading.rst
  docs/source/tutorials/own-data.rst
  examples/customized_models/HGT/README.md
  examples/customized_models/HGT/hgt_nc.py
  examples/peft_llm_gnn/main_lp.py
  examples/peft_llm_gnn/main_nc.py
  examples/temporal_graph_learning/main_nc.py
  python/graphstorm/config/argument.py
  python/graphstorm/dataloading/__init__.py
  python/graphstorm/dataloading/dataloading.py
  python/graphstorm/dataloading/dataset.py
  python/graphstorm/dataloading/utils.py
  python/graphstorm/eval/evaluator.py
  python/graphstorm/inference/emb_infer.py
  python/graphstorm/inference/ep_infer.py
  python/graphstorm/inference/np_infer.py
  python/graphstorm/model/edge_gnn.py
  python/graphstorm/model/embed.py
  python/graphstorm/model/gat_encoder.py
  python/graphstorm/model/gatv2_encoder.py
  python/graphstorm/model/hgt_encoder.py
  python/graphstorm/model/lm_embed.py
  python/graphstorm/model/node_gnn.py
  python/graphstorm/model/rgat_encoder.py
  python/graphstorm/model/rgcn_encoder.py
  python/graphstorm/model/sage_encoder.py
  python/graphstorm/run/gsgnn_emb/gsgnn_node_emb.py
  python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
  python/graphstorm/run/gsgnn_ep/ep_infer_lm.py
  python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
  python/graphstorm/run/gsgnn_ep/gsgnn_lm_ep.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
  python/graphstorm/run/gsgnn_np/gsgnn_np.py
  python/graphstorm/run/gsgnn_np/np_infer_gnn.py
  python/graphstorm/trainer/ep_trainer.py
  python/graphstorm/trainer/glem_np_trainer.py
  python/graphstorm/trainer/lp_trainer.py
  python/graphstorm/trainer/np_trainer.py
  tests/end2end-tests/custom-gnn/train.py
  tests/unit-tests/data_utils.py
  tests/unit-tests/test_dataloading.py
  tests/unit-tests/test_gnn.py
Labels: break back compatibility, 0.3, ready
