Repository awslabs/graphstorm, pull requests merged in 2024-01, with the labels that each got.

#691 [Feature] New ACM data and a notebook for data prepare
  docs/requirements.txt
  docs/source/conf.py
  docs/source/index.rst
  docs/source/notebooks/Notebook_0_Data_Prepare.ipynb
  docs/source/tutorials/own-data.rst
  examples/acm_data.py
  tutorial/ACM_raw_parquet.png
  tutorial/ACM_w_text.png
Labels: ready

#699 [Enhancement] change the input argument of GSTaskTrackerAbc to be an integer
  docs/source/advanced/own-models.rst
  docs/source/configuration/configuration-run.rst
  examples/customized_models/HGT/hgt_nc.py
  examples/peft_llm_gnn/main_nc.py
  examples/peft_llm_gnn/nc_config_Video_Games.yaml
  python/graphstorm/gsf.py
  python/graphstorm/tracker/graphstorm_tracker.py
  python/graphstorm/tracker/sagemaker_tracker.py
Labels: ready

#678 Add edge hard negative support.
  python/graphstorm/config/argument.py
  python/graphstorm/dataloading/__init__.py
  python/graphstorm/dataloading/dataloading.py
  python/graphstorm/dataloading/sampler.py
  python/graphstorm/gconstruct/transform.py
  python/graphstorm/model/edge_decoder.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
  tests/end2end-tests/create_data.sh
  tests/end2end-tests/data_gen/movielens_lp_hard.json
  tests/end2end-tests/data_gen/process_movielens.py
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
  tests/unit-tests/test_dataloading.py
Labels: ready, 0.2.2

#698 [SageMaker] Upgrade DGL Tool Version
  docker/sagemaker/Dockerfile.sm
Labels: ready

#697 [WholeGraph] Refactor code to separate WholeGraph-related functions
  python/graphstorm/dataloading/dataset.py
  python/graphstorm/dataloading/utils.py
  python/graphstorm/gsf.py
  python/graphstorm/wholegraph/__init__.py
  python/graphstorm/wholegraph/utils.py
  python/graphstorm/wholegraph/wholegraph.py
  tools/convert_feat_to_wholegraph.py
Labels: ready, 0.2.2

#641 Refactor the way we save and load ID mappings for GConstruct.
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
  graphstorm-processing/graphstorm_processing/graph_loaders/row_count_utils.py
  graphstorm-processing/tests/test_dist_category_transformation.py
  graphstorm-processing/tests/test_dist_heterogenous_loader.py
  python/graphstorm/gconstruct/README.md
  python/graphstorm/gconstruct/construct_graph.py
  python/graphstorm/gconstruct/file_io.py
  python/graphstorm/gconstruct/id_map.py
  python/graphstorm/gconstruct/remap_result.py
  python/graphstorm/sagemaker/sagemaker_infer.py
  python/graphstorm/sagemaker/utils.py
  python/graphstorm/utils.py
  sagemaker/launch/common_parser.py
  sagemaker/launch/launch_infer.py
  sagemaker/launch/launch_partition.py
  sagemaker/launch/launch_train.py
  sagemaker/local/generate_sagemaker_docker_compose.py
  sagemaker/run/infer_entry.py
  tests/end2end-tests/data_gen/gen_multilabel.py
  tests/end2end-tests/data_gen/remove_mask.py
  tests/end2end-tests/data_gen/remove_test_mask.py
  tests/end2end-tests/data_process/gen_edge_predict_remap_test.py
  tests/end2end-tests/data_process/gen_emb_predict_remap_test.py
  tests/end2end-tests/data_process/gen_node_predict_remap_test.py
  tests/end2end-tests/data_process/test_data.py
  tests/unit-tests/gconstruct/test_construct_graph.py
  tests/unit-tests/gconstruct/test_remap_result.py
Labels: break back compatibility, ready

#708 BugFix: Fix the bug when fixed_test_size is set while the number of testing edges are smaller than fixed_test_size
  python/graphstorm/dataloading/dataloading.py
  tests/unit-tests/test_dataloading.py
Labels: bug, ready, 0.2.2

#703 Support Hard Negative sampling in training and evaluation
  docs/source/advanced/advanced-usages.rst
  python/graphstorm/config/argument.py
  python/graphstorm/dataloading/__init__.py
  python/graphstorm/dataloading/dataloading.py
  python/graphstorm/dataloading/sampler.py
  python/graphstorm/gconstruct/construct_graph.py
  python/graphstorm/gconstruct/file_io.py
  python/graphstorm/gconstruct/id_map.py
  python/graphstorm/gconstruct/transform.py
  python/graphstorm/gconstruct/utils.py
  python/graphstorm/model/edge_decoder.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
  python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
  python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
  python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
  tests/end2end-tests/create_data.sh
  tests/end2end-tests/data_gen/movielens_lp_hard.json
  tests/end2end-tests/data_gen/process_movielens.py
  tests/end2end-tests/data_process/data_gen.py
  tests/end2end-tests/data_process/test_data.py
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
  tests/unit-tests/gconstruct/test_construct_graph.py
  tests/unit-tests/gconstruct/test_gconstruct_utils.py
  tests/unit-tests/gconstruct/test_transform.py
  tests/unit-tests/test_dataloading.py
Labels: ready, 0.2.2

#710 [Bugfix] Fix a bug in launch.py when it is lauching remap commands.
  python/graphstorm/run/launch.py
Labels: bug, ready, 0.2.2

#707 [GSProcessing] Fix support for large integer values for noop transfomation
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_noop_transformation.py
  graphstorm-processing/graphstorm_processing/graph_loaders/schema_utils.py
  graphstorm-processing/tests/test_dist_noop_transformation.py
Labels: ready, gsprocessing, 0.2.2

#712 Run training jobs without ssh in the local machine.
  docs/source/install/env-setup.rst
  docs/source/tutorials/own-data.rst
  docs/source/tutorials/quick-start.rst
  python/graphstorm/run/launch.py
  tests/end2end-tests/graphstorm-nc/test.sh
Labels: ready

#711 [Bug Fix] Fix errors in binary cases for roc_auc, precision_recall, and f1 score.
  python/graphstorm/eval/eval_func.py
  tests/end2end-tests/data_gen/gen_multilabel.py
  tests/end2end-tests/data_gen/process_movielens.py
  tests/end2end-tests/graphstorm-ec/mgpu_test.sh
  tests/end2end-tests/graphstorm-ec/test-cpu.sh
  tests/end2end-tests/graphstorm-ec/test.sh
  tests/end2end-tests/graphstorm-nc/test.sh
  tests/unit-tests/test_eval_func.py
  training_scripts/gsgnn_ep/ml_ec.yaml
  training_scripts/gsgnn_ep/ml_ec_homogeneous.yaml
  training_scripts/gsgnn_ep/ml_ec_text.yaml
  training_scripts/gsgnn_ep/ml_lm_ec.yaml
  training_scripts/gsgnn_np/ml_nc_multi_target_ntypes_multilabel.yaml
Labels: bug, break back compatibility, ready, 0.2.2

#714 Balance the training set in graph partitioning
  python/graphstorm/gconstruct/utils.py
  tests/unit-tests/gconstruct/test_construct_graph.py
Labels: ready

#716 Set default node embedding normalization method of contrastive loss to l2 norm.
  python/graphstorm/config/argument.py
  tests/unit-tests/test_config.py
Labels: enhancement, ready, 0.2.2
