Repository awslabs/graphstorm, pull requests merged in 2025-07, with the labels that each got.

#1296 [Docker] Add Credential to Dockerfile
  docker/build_graphstorm_image.sh
Labels: bug, ready, 0.5

#1292 [Feature] NP entry point file
  .github/workflow_scripts/pytest_check.sh
  python/graphstorm/__init__.py
  python/graphstorm/config/__init__.py
  python/graphstorm/config/argument.py
  python/graphstorm/config/config.py
  python/graphstorm/dataloading/dataloading.py
  python/graphstorm/dataloading/metadata.py
  python/graphstorm/gconstruct/__init__.py
  python/graphstorm/gconstruct/construct_graph.py
  python/graphstorm/gconstruct/construct_payload_graph.py
  python/graphstorm/gsf.py
  python/graphstorm/inference/np_infer.py
  python/graphstorm/sagemaker/__init__.py
  python/graphstorm/sagemaker/realtime_http_response.py
  sagemaker/launch/launch_realtime_endpoint.py
  sagemaker/run/realtime_entry_points/node_prediction_entry.py
  tests/end2end-tests/data_gen/movielens_realtime_payload.json
  tests/sagemaker-tests/test_sagemaker_entry.py
  tests/unit-tests/config_utils.py
  tests/unit-tests/data_utils.py
  tests/unit-tests/gconstruct/test_gconstruct_json_payload.py
  tests/unit-tests/test_config.py
  tests/unit-tests/test_dataloading.py
  tests/unit-tests/test_gsf.py
  tests/unit-tests/test_metadata.py
  tests/unit-tests/test_rt_infer_response.py
Labels: enhancement, ready, 0.5

#1299 [BugFix] Fix a bug in remapping node embeddings, when shared fs is not avaliable
  python/graphstorm/gconstruct/remap_result.py
  tests/end2end-tests/data_process/test.sh
Labels: bug, ready, 0.5

#1306 [GSProcessing] Fix docker script&doc
  graphstorm-processing/docker/build_gsprocessing_image.sh
  graphstorm-processing/docker/push_gsprocessing_image.sh
Labels: bug, ready, gsprocessing

#1303 [Bug Fix] Save transformed config before repartition
  graphstorm-processing/graphstorm_processing/distributed_executor.py
Labels: enhancement, ready, 0.5

#1310 [Feature] Enable the Config "fixed-test-size" for LM training with Link Prediction.
  python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
Labels: ready, 0.5
