Repository awslabs/graphstorm, pull requests merged in 2025-03, with the labels that each got.

#1199 Fix the error case when the label is a 1D tensor for regression tasks
  python/graphstorm/eval/eval_func.py
  tests/unit-tests/test_eval_func.py
Labels: ready, 0.4.1

#1186 [GSProcessing] Remove requirement to have poetry installed for GSP im…
  graphstorm-processing/docker/push_gsprocessing_image.sh
Labels: gsprocessing, dependencies, 0.4.1

#1196 [Fix] Fix an HGT Encoder Corner Case: 0 edge in a block
  python/graphstorm/model/hgt_encoder.py
  tests/unit-tests/test_nn_model.py
Labels: bug, enhancement, ready, 0.4.1

#1201 [GSProcessing] Have 'mean' default imputation when converting GConstr…
  graphstorm-processing/graphstorm_processing/config/config_conversion/gconstruct_converter.py
  graphstorm-processing/tests/test_converter.py
Labels: ready, gsprocessing

#1197 Add end2end test for load saved learnable embeddings with different numbers of trainers
  tests/end2end-tests/graphstorm-nc/mgpu_test.sh
Labels: ready, 0.4.1

#1200 [GSProcessing] Reduce SageMaker logging
  graphstorm-processing/docker/0.4.1/sagemaker/Dockerfile.cpu
  graphstorm-processing/docker/0.4.1/sagemaker/log4j.properties
  graphstorm-processing/docker/build_gsprocessing_image.sh
  graphstorm-processing/graphstorm_processing/data_transformations/spark_utils.py
Labels: ready, 0.4.1

#1192 [GSProcessing] Enforce re-order for edge label processing during classification
  graphstorm-processing/graphstorm_processing/data_transformations/dist_label_loader.py
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
  graphstorm-processing/tests/test_dist_heterogenous_loader.py
Labels: bug, ready, gsprocessing, 0.4.1

#1185 [Feature] Support edge features in RGAT model.
  docs/source/api/references/graphstorm.model.rst
  python/graphstorm/gsf.py
  python/graphstorm/model/__init__.py
  python/graphstorm/model/gnn_encoder_base.py
  python/graphstorm/model/rgat_encoder.py
  python/graphstorm/model/rgcn_encoder.py
  tests/unit-tests/data_utils.py
  tests/unit-tests/test_nn_encoder.py
  tests/unit-tests/test_nn_model.py
  tests/unit-tests/test_trainer.py
Labels: enhancement, break back compatibility, ready, 0.4.1

#1204 [Tests] End2end tests for RGAT using edge features
  tests/end2end-tests/graphstorm-ec/mgpu_test.sh
  tests/end2end-tests/graphstorm-er/test.sh
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
  tests/end2end-tests/graphstorm-nc/mgpu_test.sh
Labels: ready, 0.4.1

#1206 [Bug Fix] Fix the case when input graph is a homogeneous graph without any mask, gconstruct will fail.
  python/graphstorm/gconstruct/utils.py
  tests/unit-tests/gconstruct/test_construct_graph.py
Labels: ready, 0.4.1

#1209 Bump version to 0.4.1 in __init__.py
  python/graphstorm/__init__.py
Labels: ready, 0.4.1

#1203 [Docker] Ensure hostname fix is at right place for SageMaker image. Use recommended paths for code
  docker/sagemaker/Dockerfile.sm
  docker/sagemaker/build_artifacts/start_with_right_hostname.sh
Labels: 0.4.1

#1208 [Bug] Sagemaker Launch Script fix for Inference
  sagemaker/launch/launch_infer.py
Labels: bug, ready, 0.4.1

#1210 [Dependencies] Add torchdata and pydantic dependencies for GraphStorm
  setup.py
Labels: ready, dependencies

#1207 [Docs] Add SageMaker pipeline docs
  docs/source/advanced/sagemaker-pipelines.rst
  sagemaker/pipeline/pipeline_parameters.py
Labels: documentation

#1214 [Examples] Sagemaker example fixes
  examples/sagemaker-pipelines-graphbolt/README.md
  examples/sagemaker-pipelines-graphbolt/analyze_training_time.py
  examples/sagemaker-pipelines-graphbolt/build_and_push_papers100M_image.sh
Labels: ready, 0.4.1

#1216 [Examples] Updating Customized Model/HGT Example
  examples/customized_models/HGT/README.md
  examples/customized_models/HGT/hgt_nc.py
Labels: ready

#1223 [BugFix] Fix the case when early stopping does not work with report_eval_per_type
  python/graphstorm/eval/evaluator.py
  tests/end2end-tests/graphstorm-lp/test.sh
  tests/unit-tests/test_evaluator.py
Labels: ready, 0.5

#1225 [GConstruct] [GSProcessing] Allow no-op operation in gconstruct to read strings of delimited numbers as vectors
  docs/source/cli/graph-construction/single-machine-gconstruct.rst
  graphstorm-processing/graphstorm_processing/config/config_conversion/gconstruct_converter.py
  graphstorm-processing/tests/test_converter.py
  python/graphstorm/gconstruct/transform.py
  python/graphstorm/gconstruct/utils.py
  tests/unit-tests/gconstruct/test_construct_graph.py
  tests/unit-tests/gconstruct/test_transform.py
Labels: ready, 0.5

#1227 Don't print torchdata deprecation warnings
  python/graphstorm/__init__.py
Labels: ready
