Repository awslabs/graphstorm, pull requests merged in 2025-04, with the labels that each got.

#1228 Apply suggestions for Noop transformation
  docs/source/cli/graph-construction/single-machine-gconstruct.rst
  graphstorm-processing/graphstorm_processing/config/config_conversion/gconstruct_converter.py
  python/graphstorm/__init__.py
  python/graphstorm/gconstruct/transform.py
  tests/unit-tests/gconstruct/test_construct_graph.py
Labels: ready

#1232 [Docs] Add missing link to SM Pipelines doc
  docs/source/index.rst
Labels: documentation, 0.4.1

#1233 [Docs] Add missing link to SM Pipelines doc (#1232)
  docs/source/index.rst
Labels: documentation, 0.5

#1231 Change decoder output definition so that focal loss does not require setting num_classes to 1.
  docs/source/advanced/imbalanced-labels.rst
  python/graphstorm/gsf.py
  python/graphstorm/model/loss_func.py
  tests/end2end-tests/graphstorm-ec/test.sh
  tests/end2end-tests/graphstorm-nc/test.sh
  tests/unit-tests/test_gsf.py
Labels: ready

#1234 [GSProcessing] Support `:` in label column names
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_label_transformation.py
  graphstorm-processing/tests/test_dist_label_loader.py
Labels: bug, ready, gsprocessing

#1236 [Ehancement] Refactor `return_proba` warning message and document
  docs/source/cli/model-training-inference/configuration-run.rst
  python/graphstorm/trainer/ep_trainer.py
  python/graphstorm/trainer/np_trainer.py
Labels: documentation, ready, 0.5

#1235 [Enhancement] Add Precision, Recall, and Fscore_at_beta for issue #1217
  docs/source/cli/model-training-inference/configuration-run.rst
  python/graphstorm/config/argument.py
  python/graphstorm/eval/__init__.py
  python/graphstorm/eval/eval_func.py
  python/graphstorm/eval/utils.py
  python/graphstorm/gsf.py
  tests/end2end-tests/graphstorm-nc/mgpu_test.sh
  tests/unit-tests/test_config.py
  tests/unit-tests/test_eval_func.py
Labels: enhancement, ready, 0.5

#1230 [GConstruct/GSProcessing] Allow GConstruct accept GSProcessing Config
  docs/source/cli/graph-construction/single-machine-gconstruct.rst
  python/graphstorm/gconstruct/config_conversion/__init__.py
  python/graphstorm/gconstruct/config_conversion/converter_base.py
  python/graphstorm/gconstruct/config_conversion/gsprocessing_converter.py
  python/graphstorm/gconstruct/config_conversion/meta_configuration.py
  python/graphstorm/gconstruct/construct_graph.py
  sagemaker/README.md
  tests/end2end-tests/data_gen/movielens_gsp.json
  tests/end2end-tests/data_process/movielens_test.sh
  tests/unit-tests/gconstruct/config/gsp_config.json
  tests/unit-tests/gconstruct/test_converter.py
Labels: ready, 0.5, gconstruct

#1249 [SageMaker] Support HyperBand optimization strategy
  docs/source/cli/model-training-inference/distributed/sagemaker.rst
  sagemaker/launch/launch_hyperparameter_tuning.py
Labels: sagemaker, 0.4.2

#1250 [Fix Bug] Fix the bug of setting num_classes to 1 does not trigger an error for cross entropy
  python/graphstorm/config/argument.py
  python/graphstorm/gsf.py
  tests/unit-tests/test_config.py
  tests/unit-tests/test_gsf.py
Labels: bug, ready, 0.4.2

#1251 [Feature] Pack model artifact func for realtime inference
  sagemaker/launch/launch_utils.py
  tests/sagemaker-tests/test_sagemaker_utils.py
  tests/unit-tests/test_utils.py
Labels: enhancement, ready, 0.5

#1257 [CI] Reduce the LM model candidate
  tests/unit-tests/test_hfbert.py
Labels: CI

#1254 [GConstruct] Allow featureless nodes to not have node files
  python/graphstorm/gconstruct/construct_graph.py
  tests/end2end-tests/data_process/data_gen.py
  tests/end2end-tests/data_process/test_data.py
  tests/unit-tests/gconstruct/test_construct_graph.py
Labels: ready, 0.4.2

#1253 Add infer-all-target-nodes argument to trigger inference on all nodes in target node types
  docs/source/cli/model-training-inference/configuration-run.rst
  python/graphstorm/config/argument.py
  python/graphstorm/run/gsgnn_np/np_infer_gnn.py
  python/graphstorm/sagemaker/sagemaker_infer.py
  tests/end2end-tests/graphstorm-nc/check_emb.py
  tests/end2end-tests/graphstorm-nc/test.sh
  tests/unit-tests/test_np_infer_gnn.py
Labels: ready, 0.4.2

#1246 [GConstruct] Save Feature Dimension to GConstruct transformed config
  python/graphstorm/gconstruct/construct_graph.py
  python/graphstorm/gconstruct/transform.py
  python/graphstorm/gconstruct/utils.py
  tests/end2end-tests/data_process/test_data.py
  tests/unit-tests/gconstruct/test_construct_graph.py
  tests/unit-tests/gconstruct/test_gconstruct_utils.py
  tests/unit-tests/gconstruct/test_transform.py
Labels: ready, 0.5, gconstruct
