Repository awslabs/graphstorm, pull requests merged in 2025-02, with the labels that each got.

#1154 Airport data update
  examples/network_traffic_prediction/README.md
  examples/network_traffic_prediction/Synthetic_Airport_Traffic_wAirlines.ipynb
Labels: 0.4.1

#1152 [Doc] Highlight inference in `eval_fanout` explanation
  docs/source/cli/model-training-inference/configuration-run.rst
Labels: documentation, ready, 0.4.1

#1157 Add Shrinkage Loss to handle regression label imbalance problem.
  .github/workflow_scripts/e2e_check.sh
  docs/source/api/references/graphstorm.model.rst
  docs/source/cli/model-training-inference/configuration-run.rst
  python/graphstorm/config/__init__.py
  python/graphstorm/config/argument.py
  python/graphstorm/config/config.py
  python/graphstorm/gsf.py
  python/graphstorm/model/__init__.py
  python/graphstorm/model/loss_func.py
  tests/end2end-tests/data_gen/movielens.json
  tests/end2end-tests/data_gen/process_movielens.py
  tests/end2end-tests/graphstorm-er/test.sh
  tests/end2end-tests/graphstorm-nr/test.sh
  tests/unit-tests/test_config.py
  tests/unit-tests/test_gsf.py
  tests/unit-tests/test_loss.py
Labels: enhancement, ready, 0.4.1

#1161 [Examples] Editing readme
  examples/sagemaker-pipelines-graphbolt/README.md
Labels: ready, 0.4.1

#1159 [Dependent Bot] Fix transformer version
  setup.py
Labels: ready

#1149 Add Bayesian Personalized Ranking Loss for link prediction
  docs/source/advanced/link-prediction.rst
  docs/source/cli/model-training-inference/configuration-run.rst
  python/graphstorm/config/__init__.py
  python/graphstorm/config/config.py
  python/graphstorm/gsf.py
  python/graphstorm/model/loss_func.py
  tests/end2end-tests/graphstorm-lp/test.sh
  tests/unit-tests/test_config.py
  tests/unit-tests/test_gsf.py
  tests/unit-tests/test_loss.py
Labels: ready, 0.4.1

#1164 [Doc] Revise loss functions location in the configuration page
  docs/source/cli/model-training-inference/configuration-run.rst
Labels: documentation, ready, 0.4.1

#1165 Validate the numerical values of input features in GConstruct.
  docs/source/cli/graph-construction/single-machine-gconstruct.rst
  python/graphstorm/gconstruct/construct_graph.py
  python/graphstorm/gconstruct/transform.py
  python/graphstorm/gconstruct/utils.py
  tests/unit-tests/gconstruct/test_gconstruct_utils.py
  tests/unit-tests/gconstruct/test_transform.py
Labels: ready, 0.4.1

#1163 Save relation_embeddings for models trained with link prediction in gs_gen_node_embedding
  python/graphstorm/inference/emb_infer.py
  python/graphstorm/model/gnn.py
  python/graphstorm/run/gsgnn_emb/gsgnn_node_emb.py
  tests/end2end-tests/graphstorm-ec/mgpu_test.sh
  tests/end2end-tests/graphstorm-er/test.sh
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
  tests/end2end-tests/graphstorm-mt/mgpu_test.sh
  tests/end2end-tests/graphstorm-nc/mgpu_test.sh
Labels: bug, ready, 0.4.1

#1171 [Examples] Revise GS-GB-SM example
  examples/sagemaker-pipelines-graphbolt/README.md
  examples/sagemaker-pipelines-graphbolt/deploy_arxiv_pipeline.sh
  examples/sagemaker-pipelines-graphbolt/deploy_papers100M_pipeline.sh
Labels: ready, 0.4.1

#1169 [GSProcessing] Change default quoting and parsing for CSV input
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
Labels: ready, gsprocessing, 0.4.1

#1133 [SageMaker] Add launcher and support for SageMaker HPO jobs
  docs/source/cli/model-training-inference/distributed/sagemaker.rst
  python/graphstorm/sagemaker/sagemaker_train.py
  python/graphstorm/sagemaker/utils.py
  sagemaker/launch/launch_hyperparameter_tuning.py
  sagemaker/run/train_entry.py
Labels: sagemaker, 0.4.1

#1172 [GSProcessing] Bump GSProcessing version to 0.4.1
  graphstorm-processing/docker/0.4.1/emr-serverless/Dockerfile.cpu
  graphstorm-processing/docker/0.4.1/emr/Dockerfile.cpu
  graphstorm-processing/docker/0.4.1/requirements.txt
  graphstorm-processing/docker/0.4.1/sagemaker/Dockerfile.cpu
  graphstorm-processing/pyproject.toml
Labels: gsprocessing, dependencies

#1175 [Enhancement] Save emb_dim to emb_info.json
  python/graphstorm/model/utils.py
  tests/unit-tests/test_utils.py
Labels: ready, 0.4.1

#1102 Add support for ParMETIS to local Dockerfile
  docker/README.md
  docker/build_docker_oss4local.sh
  docker/build_graphstorm_image.sh
  docker/local/Dockerfile.local
  docs/source/install/env-setup.rst
Labels: 0.4.1

#1174 [Tests] HGTLayerwithEdgeFeat tests
  tests/unit-tests/test_nn_model.py
  tests/unit-tests/test_trainer.py
Labels: ready, 0.4.1

#1176 [Doc] Add Imbalance label guide and reorg
  docs/source/advanced/advanced-usages.rst
  docs/source/advanced/imbalanced-labels.rst
  docs/source/advanced/multi-target-ntypes.rst
  docs/source/advanced/multi-task-learning.rst
  docs/source/cli/model-training-inference/configuration-run.rst
  docs/source/index.rst
Labels: documentation, ready, 0.4.1

#1184 [Tests] HGTEncoder tests
  python/graphstorm/model/hgt_encoder.py
  tests/unit-tests/test_nn_encoder.py
Labels: ready, 0.4.1

#1178 Fix overlapping IDs being written when ID map writes to multiple files
  python/graphstorm/data/constants.py
  python/graphstorm/gconstruct/id_map.py
  tests/unit-tests/gconstruct/test_remap_result.py
Labels: bug, ready, 0.4.1

#1189 [Doc] Fix cpu installation string format
  docs/source/install/env-setup.rst
Labels: documentation, ready, 0.4.1

#1170 Handle the cases when the input edge file(s) are empty
  python/graphstorm/gconstruct/construct_graph.py
  python/graphstorm/gconstruct/file_io.py
  python/graphstorm/gconstruct/utils.py
  tests/end2end-tests/data_process/data_gen.py
  tests/end2end-tests/data_process/test.sh
  tests/end2end-tests/data_process/test_data.py
  tests/unit-tests/gconstruct/test_construct_graph.py
  tests/unit-tests/gconstruct/test_gconstruct_utils.py
Labels: enhancement, ready, 0.4.1

#1188 [Feature] Enhance HGT Encoder with Edge Features
  docs/source/api/references/graphstorm.model.rst
  python/graphstorm/gsf.py
  python/graphstorm/model/__init__.py
  python/graphstorm/model/hgt_encoder.py
  tests/unit-tests/test_nn_encoder.py
  tests/unit-tests/test_nn_model.py
  tests/unit-tests/test_trainer.py
Labels: enhancement, break back compatibility, ready, 0.4.1

#1191 [Docker] Fix Gsprocessing docker build for base image
  graphstorm-processing/docker/0.4.0/emr-serverless/Dockerfile.cpu
  graphstorm-processing/docker/0.4.0/emr/Dockerfile.cpu
  graphstorm-processing/docker/0.4.1/emr-serverless/Dockerfile.cpu
  graphstorm-processing/docker/0.4.1/emr/Dockerfile.cpu
Labels: bug
