Repository awslabs/graphstorm, pull requests merged in 2025-05, with the labels that each got.

#1256 [GConstruct] Save homogenous graph flag in the transformation config
  python/graphstorm/gconstruct/construct_graph.py
  tests/end2end-tests/data_process/check_homogeneous.py
  tests/end2end-tests/data_process/homogeneous_test.sh
  tests/end2end-tests/data_process/test_data.py
  tests/unit-tests/gconstruct/test_construct_graph.py
Labels: ready, 0.5, gconstruct

#1264 [Documentation] Re-structure and update README
  .gitignore
  README.md
Labels: documentation, 0.4.2

#1259 [GSProcessing] Save Feat Dim for GSProcessing
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_hf_transformation.py
  graphstorm-processing/graphstorm_processing/distributed_executor.py
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
  graphstorm-processing/tests/resources/small_heterogeneous_graph/gsprocessing-config.json
  graphstorm-processing/tests/test_dist_executor.py
  graphstorm-processing/tests/test_dist_heterogenous_loader.py
Labels: ready, gsprocessing, 0.5

#1268 [GSProcessing] Handle `*` wildcards in filenames
  docs/source/cli/graph-construction/distributed/gsprocessing/input-configuration.rst
  graphstorm-processing/graphstorm_processing/config/config_conversion/gconstruct_converter.py
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
  graphstorm-processing/tests/resources/small_heterogeneous_graph/gconstruct-config.json
  graphstorm-processing/tests/test_converter.py
  graphstorm-processing/tests/test_dist_heterogenous_loader.py
Labels: ready, gsprocessing

#1272 Resolve warnings of NumPy library
  tools/partition_graph_lp.py
Labels: ready

#1260 Add support for Knowledge graph embedding training.
  docs/source/api/references/graphstorm.model.rst
  docs/source/cli/model-training-inference/configuration-run.rst
  python/graphstorm/config/__init__.py
  python/graphstorm/config/config.py
  python/graphstorm/gsf.py
  python/graphstorm/model/__init__.py
  python/graphstorm/model/embed.py
  tests/end2end-tests/graphstorm-lp/mgpu_test.sh
  tests/end2end-tests/graphstorm-lp/test-cpu.sh
  tests/unit-tests/test_embed.py
Labels: ready, 0.4.2

#1267 [SageMaker] Use SageMaker local mode to launch SageMaker jobs locally, remove custom Docker compose instructions.
  docs/source/cli/model-training-inference/distributed/sagemaker.rst
  sagemaker/README.md
  sagemaker/launch/common_parser.py
  sagemaker/launch/launch_gconstruct.py
  sagemaker/launch/launch_graphbolt_convert.py
  sagemaker/launch/launch_infer.py
  sagemaker/launch/launch_partition.py
  sagemaker/launch/launch_train.py
  sagemaker/local/generate_sagemaker_docker_compose.py
Labels: ready, sagemaker

#1269 [Feature] Add SageMaker Real-time Inference Endpoint Launch Script
  sagemaker/launch/launch_realtime_endpoint.py
  sagemaker/launch/launch_utils.py
  tests/sagemaker-tests/test_sagemaker_args.py
  tests/sagemaker-tests/test_sagemaker_utils.py
  tools/launch_custom_model_realtime_endpoint.py
Labels: enhancement, ready, sagemaker, 0.5

#1273 [Enhancement] Add precision_at_recall and recall_at_precision metrics
  docs/source/cli/model-training-inference/configuration-run.rst
  python/graphstorm/config/argument.py
  python/graphstorm/eval/__init__.py
  python/graphstorm/eval/eval_func.py
  tests/end2end-tests/create_data.sh
  tests/end2end-tests/data_gen/movielens_nc_binary.json
  tests/end2end-tests/data_gen/process_movielens.py
  tests/end2end-tests/graphstorm-nc/mgpu_test.sh
  tests/unit-tests/test_config.py
  tests/unit-tests/test_eval_func.py
Labels: enhancement, ready, 0.4.2

#1275 Add future warning for focal loss shape and clarify use in documentat…
  docs/source/cli/model-training-inference/configuration-run.rst
  python/graphstorm/config/argument.py
  python/graphstorm/model/loss_func.py
Labels: ready, 0.4.2

#1276 Bump version to 0.4.2
  graphstorm-processing/docker/0.4.2/emr-serverless/Dockerfile.cpu
  graphstorm-processing/docker/0.4.2/emr/Dockerfile.cpu
  graphstorm-processing/docker/0.4.2/requirements.txt
  graphstorm-processing/docker/0.4.2/sagemaker/Dockerfile.cpu
  graphstorm-processing/docker/0.4.2/sagemaker/log4j.properties
  graphstorm-processing/pyproject.toml
  python/graphstorm/__init__.py
Labels: 0.4.2

#1279 [Bugfix] Fix the case when the subtask name is too long in multi-task learning
  python/graphstorm/config/config.py
  tests/unit-tests/test_config.py
Labels: ready, 0.5
