Repository awslabs/graphstorm, pull requests merged in 2025-01, with the labels that each got.

#1122 Fix lint error in python/graphstorm/data/ogbn_datasets.py
  python/graphstorm/data/ogbn_datasets.py
Labels: bug, ready

#1111 [Feature] Add bias in node decoder
  python/graphstorm/config/argument.py
  python/graphstorm/gsf.py
  python/graphstorm/model/node_decoder.py
  tests/end2end-tests/graphstorm-nc/test.sh
  tests/unit-tests/test_decoder.py
  tests/unit-tests/test_gsf.py
Labels: ready, 0.4

#1128 [Bug Fix] Fix Edge Feature None block error
  python/graphstorm/model/gnn_encoder_base.py
Labels: ready, 0.4

#1117 [GSProcessing] Update GSProcessing custom split config parsing and documentation to match GConstruct.
  docs/source/cli/graph-construction/distributed/gsprocessing/input-configuration.rst
  graphstorm-processing/graphstorm_processing/config/config_conversion/gconstruct_converter.py
  graphstorm-processing/graphstorm_processing/config/config_parser.py
  graphstorm-processing/graphstorm_processing/config/label_config_base.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_label_loader.py
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
  graphstorm-processing/pyproject.toml
  graphstorm-processing/tests/test_converter.py
  graphstorm-processing/tests/test_dist_heterogenous_loader.py
  graphstorm-processing/tests/test_gsprocessing_config.py
  python/graphstorm/gconstruct/file_io.py
Labels: break back compatibility, ready, gsprocessing, 0.4

#1129 Fix typo in sagemaker launcher
  sagemaker/launch/common_parser.py
Labels: bug, ready, 0.4

#1130 [GConstruct] Allow directory paths as input to GConstruct
  python/graphstorm/gconstruct/file_io.py
  tests/unit-tests/gconstruct/test_gconstruct_utils.py
Labels: ready, 0.4

#1125 [Feature] Add bias to edge decoder
  python/graphstorm/config/argument.py
  python/graphstorm/gsf.py
  python/graphstorm/model/__init__.py
  python/graphstorm/model/edge_decoder.py
  python/graphstorm/model/node_decoder.py
  tests/unit-tests/data_utils.py
  tests/unit-tests/test_decoder.py
  tests/unit-tests/test_gsf.py
Labels: ready, 0.4

#1131 [GSProcessing] Prevent poetry-core 2.0 from being used.
  graphstorm-processing/pyproject.toml
Labels: ready, gsprocessing, dependencies

#1108 [SageMaker] Add GraphStorm SageMaker Pipeline creation and execution
  docs/source/cli/graph-construction/single-machine-gconstruct.rst
  python/graphstorm/gconstruct/construct_graph.py
  sagemaker/pipeline/README.md
  sagemaker/pipeline/create_sm_pipeline.py
  sagemaker/pipeline/execute_sm_pipeline.py
  sagemaker/pipeline/pipeline_parameters.py
  sagemaker/run/infer_entry.py
  sagemaker/run/partition_entry.py
  sagemaker/run/train_entry.py
Labels: ready, 0.4, sagemaker

#1132 [SageMaker] Fix download location for model inference
  python/graphstorm/sagemaker/sagemaker_infer.py
  sagemaker/launch/launch_infer.py
  sagemaker/launch/launch_train.py
Labels: 0.4, sagemaker

#1134 [SageMaker] Make default region value be None, so AWS config takes precedence
  sagemaker/launch/common_parser.py
Labels: 0.4, sagemaker

#1126 [Examples] SageMaker Pipelines distributed training
  .github/workflow_scripts/lint_check.sh
  examples/sagemaker-pipelines-graphbolt/Dockerfile.processing
  examples/sagemaker-pipelines-graphbolt/README.md
  examples/sagemaker-pipelines-graphbolt/analyze_training_time.py
  examples/sagemaker-pipelines-graphbolt/build_and_push_papers100M_image.sh
  examples/sagemaker-pipelines-graphbolt/convert_arxiv_to_gconstruct.py
  examples/sagemaker-pipelines-graphbolt/convert_ogb_papers100m_to_gconstruct.py
  examples/sagemaker-pipelines-graphbolt/deploy_arxiv_pipeline.sh
  examples/sagemaker-pipelines-graphbolt/deploy_papers100M_pipeline.sh
  examples/sagemaker-pipelines-graphbolt/process_papers100M.sh
  examples/sagemaker-pipelines-graphbolt/sagemaker_convert_papers100m.py
  training_scripts/gsgnn_np/papers100M_nc.yaml
Labels: documentation, 0.4, sagemaker

#1009 [Workaround] Align DataLoader Import with DGL 2.5
  python/graphstorm/dataloading/dataloading.py
Labels: ready

#1143 [CI] Update Github workflow for Semgrep version after 2.103.0
  .github/workflows/semgrep.yml
Labels: ready

#1076 [GSProcessing] Remove poetry as a requirement for building images.
  docs/source/cli/graph-construction/distributed/gsprocessing/distributed-processing-setup.rst
  graphstorm-processing/docker/0.4.0/emr-serverless/Dockerfile.cpu
  graphstorm-processing/docker/0.4.0/emr/Dockerfile.cpu
  graphstorm-processing/docker/0.4.0/requirements.txt
  graphstorm-processing/docker/0.4.0/sagemaker/Dockerfile.cpu
  graphstorm-processing/docker/build_gsprocessing_image.sh
Labels: gsprocessing, dependencies, 0.4.1

#1142 [GSProcessing] Add standard numerical transformation to gconstruct config converter.
  graphstorm-processing/graphstorm_processing/config/config_conversion/gconstruct_converter.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_hf_transformation.py
  graphstorm-processing/tests/test_converter.py
Labels: ready, gsprocessing, 0.4.1

#1140 [GSProcessing] Fix ParquetRowCounter bug when different types had same-name features
  graphstorm-processing/graphstorm_processing/graph_loaders/row_count_utils.py
  graphstorm-processing/tests/test_row_count_utils.py
Labels: bug, ready, gsprocessing, 0.4.1

#1141 [DGL Integration] Set Torch.MP to spawn for GConstruct
  python/graphstorm/gconstruct/utils.py
Labels: ready, 0.4.1

#1146 Add an optional requirement of tensorboard package in graphstorm dependency
  setup.py
Labels: 0.4.1

#1144 Support dumping training logs for TensorBoard visualization toolkit.
  .github/workflow_scripts/pytest_check.sh
  docs/source/cli/model-training-inference/configuration-run.rst
  python/graphstorm/config/__init__.py
  python/graphstorm/config/argument.py
  python/graphstorm/config/config.py
  python/graphstorm/gsf.py
  python/graphstorm/tracker/__init__.py
  python/graphstorm/tracker/graphstorm_tracker.py
  python/graphstorm/tracker/tensorboard_tracker.py
  tests/end2end-tests/graphstorm-nc/test.sh
  tests/unit-tests/test_config.py
  tests/unit-tests/test_task_tracker.py
Labels: ready, 0.4.1

#1148 [Examples] Small change to number of airports
  examples/network_traffic_prediction/Air_Traffic_Data_Exp&Gc.ipynb
  examples/network_traffic_prediction/Synthetic_Airport_Traffic_wAirlines.ipynb
Labels: 0.4.1

#1136 [GSProcessing] Enforce re-order for node label processing during classification
  graphstorm-processing/graphstorm_processing/config/label_config_base.py
  graphstorm-processing/graphstorm_processing/constants.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_label_loader.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_category_transformation.py
  graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_label_transformation.py
  graphstorm-processing/graphstorm_processing/distributed_executor.py
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
  graphstorm-processing/graphstorm_processing/graph_loaders/row_count_utils.py
  graphstorm-processing/graphstorm_processing/graph_loaders/schema_utils.py
  graphstorm-processing/graphstorm_processing/repartition_files.py
  graphstorm-processing/tests/test_dist_heterogenous_loader.py
  graphstorm-processing/tests/test_dist_label_loader.py
Labels: bug, ready, gsprocessing, 0.4.1

#1150 [GSProcessing] Make label transformation use Spark for output instead of Pyarrow when using custom masks.
  graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
  graphstorm-processing/graphstorm_processing/repartition_files.py
Labels: ready, gsprocessing, 0.4.1

#1151 Update train config for papers100M to include features, make missing feature message more descriptive.
  python/graphstorm/dataloading/dataset.py
  training_scripts/gsgnn_np/papers100M_nc.yaml
Labels: ready, 0.4.1
